# Generated by Django 6.0 on 2025-12-24 15:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('visits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('VITAL_SIGNS', 'Vital Signs Abnormal'), ('DRUG_INTERACTION', 'Drug Interaction'), ('ALLERGY', 'Allergy Warning'), ('LAB_CRITICAL', 'Critical Lab Value'), ('CONTRAINDICATION', 'Contraindication'), ('DOSAGE', 'Dosage Warning')], help_text='Type of clinical alert', max_length=50)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', help_text='Severity level of the alert', max_length=20)),
                ('title', models.CharField(help_text='Alert title', max_length=200)),
                ('message', models.TextField(help_text='Detailed alert message')),
                ('related_resource_type', models.CharField(blank=True, help_text="Type of related resource (e.g., 'prescription', 'vital_signs')", max_length=50, null=True)),
                ('related_resource_id', models.IntegerField(blank=True, help_text='ID of related resource', null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, help_text='When the alert was acknowledged', null=True)),
                ('is_resolved', models.BooleanField(default=False, help_text='Whether this alert has been resolved')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, help_text='User who acknowledged this alert', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts_acknowledged', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(help_text='Visit this alert is associated with', on_delete=django.db.models.deletion.CASCADE, related_name='clinical_alerts', to='visits.visit')),
            ],
            options={
                'verbose_name': 'Clinical Alert',
                'verbose_name_plural': 'Clinical Alerts',
                'db_table': 'clinical_alerts',
                'ordering': ['-severity', '-created_at'],
                'indexes': [models.Index(fields=['visit', '-created_at'], name='clinical_al_visit_i_3919c5_idx'), models.Index(fields=['alert_type', 'is_resolved'], name='clinical_al_alert_t_003294_idx'), models.Index(fields=['severity', 'is_resolved'], name='clinical_al_severit_6d0ad5_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClinicalTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Template name (e.g., 'Common Cold', 'Hypertension Follow-up')", max_length=200)),
                ('category', models.CharField(help_text="Template category (e.g., 'General', 'Cardiology', 'Pediatrics')", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of when to use this template')),
                ('history_template', models.TextField(blank=True, help_text='Pre-filled history section')),
                ('examination_template', models.TextField(blank=True, help_text='Pre-filled examination section')),
                ('diagnosis_template', models.TextField(blank=True, help_text='Pre-filled diagnosis section')),
                ('clinical_notes_template', models.TextField(blank=True, help_text='Pre-filled clinical notes section')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this template is active and available for use')),
                ('usage_count', models.IntegerField(default=0, help_text='Number of times this template has been used')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='User who created this template', on_delete=django.db.models.deletion.PROTECT, related_name='clinical_templates_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Clinical Template',
                'verbose_name_plural': 'Clinical Templates',
                'db_table': 'clinical_templates',
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='clinical_te_categor_173d6b_idx'), models.Index(fields=['created_by'], name='clinical_te_created_8f0215_idx')],
            },
        ),
        migrations.CreateModel(
            name='VitalSigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, help_text='Body temperature in Celsius', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(30.0), django.core.validators.MaxValueValidator(45.0)])),
                ('systolic_bp', models.IntegerField(blank=True, help_text='Systolic blood pressure (mmHg)', null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(300)])),
                ('diastolic_bp', models.IntegerField(blank=True, help_text='Diastolic blood pressure (mmHg)', null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(200)])),
                ('pulse', models.IntegerField(blank=True, help_text='Heart rate (beats per minute)', null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(250)])),
                ('respiratory_rate', models.IntegerField(blank=True, help_text='Respiratory rate (breaths per minute)', null=True, validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(50)])),
                ('oxygen_saturation', models.DecimalField(blank=True, decimal_places=2, help_text='Oxygen saturation (SpO2 %)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kilograms', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(500)])),
                ('height', models.DecimalField(blank=True, decimal_places=2, help_text='Height in centimeters', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(300)])),
                ('bmi', models.DecimalField(blank=True, decimal_places=2, help_text='Body Mass Index (calculated)', max_digits=5, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about vital signs')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, help_text='When vital signs were recorded')),
                ('recorded_by', models.ForeignKey(help_text='User who recorded these vital signs', on_delete=django.db.models.deletion.PROTECT, related_name='vital_signs_recorded', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(help_text='Visit this vital signs record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs', to='visits.visit')),
            ],
            options={
                'verbose_name': 'Vital Signs',
                'verbose_name_plural': 'Vital Signs',
                'db_table': 'vital_signs',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['visit', '-recorded_at'], name='vital_signs_visit_i_d107e4_idx'), models.Index(fields=['recorded_by'], name='vital_signs_recorde_db16b7_idx')],
            },
        ),
    ]
