# Generated by Django 5.2.7 on 2026-01-10 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_billinglineitem'),
        ('clinical', '0001_initial'),
        ('consultations', '0004_consultation_status_alter_consultation_created_by_and_more'),
        ('visits', '0005_migrate_old_payment_statuses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedureTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_name', models.CharField(help_text='Name of the procedure (snapshot from ServiceCatalog)', max_length=255)),
                ('procedure_description', models.TextField(blank=True, help_text='Description of the procedure')),
                ('clinical_indication', models.TextField(blank=True, help_text='Clinical reason for performing the procedure')),
                ('status', models.CharField(choices=[('ORDERED', 'Ordered'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ORDERED', help_text='Status of the procedure task', max_length=20)),
                ('execution_notes', models.TextField(blank=True, help_text='Notes from the nurse executing the procedure')),
                ('execution_date', models.DateTimeField(blank=True, help_text='When the procedure was executed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the procedure task was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the procedure task was last updated')),
                ('consultation', models.ForeignKey(help_text='Consultation this procedure belongs to. Procedures require consultation context.', on_delete=django.db.models.deletion.PROTECT, related_name='procedure_tasks', to='consultations.consultation')),
                ('executed_by', models.ForeignKey(blank=True, help_text='Nurse who executed the procedure', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedure_tasks_executed', to=settings.AUTH_USER_MODEL)),
                ('ordered_by', models.ForeignKey(help_text='Doctor who ordered the procedure. PROTECT prevents deletion.', on_delete=django.db.models.deletion.PROTECT, related_name='procedure_tasks_ordered', to=settings.AUTH_USER_MODEL)),
                ('service_catalog', models.ForeignKey(help_text='ServiceCatalog service that generated this procedure task', on_delete=django.db.models.deletion.PROTECT, related_name='procedure_tasks', to='billing.servicecatalog')),
                ('visit', models.ForeignKey(help_text='Visit this procedure belongs to. Procedures are visit-scoped.', on_delete=django.db.models.deletion.PROTECT, related_name='procedure_tasks', to='visits.visit')),
            ],
            options={
                'verbose_name': 'Procedure Task',
                'verbose_name_plural': 'Procedure Tasks',
                'db_table': 'procedure_tasks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['visit'], name='procedure_t_visit_i_ee7924_idx'), models.Index(fields=['consultation'], name='procedure_t_consult_2bcbeb_idx'), models.Index(fields=['service_catalog'], name='procedure_t_service_ec424a_idx'), models.Index(fields=['status'], name='procedure_t_status_1444c6_idx'), models.Index(fields=['ordered_by'], name='procedure_t_ordered_7d9b3b_idx'), models.Index(fields=['executed_by'], name='procedure_t_execute_1996db_idx')],
            },
        ),
    ]
