# Generated by Django 5.2.7 on 2026-01-26 08:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0003_make_procedure_consultation_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitalsigns',
            name='edd',
            field=models.DateField(blank=True, help_text='Expected Due Date (EDD)', null=True),
        ),
        migrations.AddField(
            model_name='vitalsigns',
            name='ega_days',
            field=models.IntegerField(blank=True, help_text='Estimated Gestational Age additional days (0-6)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AddField(
            model_name='vitalsigns',
            name='ega_weeks',
            field=models.IntegerField(blank=True, help_text='Estimated Gestational Age in weeks', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(45)]),
        ),
        migrations.AddField(
            model_name='vitalsigns',
            name='lmp',
            field=models.DateField(blank=True, help_text='Last Menstrual Period (LMP)', null=True),
        ),
        migrations.AddField(
            model_name='vitalsigns',
            name='muac',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Mid-Upper Arm Circumference (MUAC) in cm - for pediatrics', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AddField(
            model_name='vitalsigns',
            name='nutritional_status',
            field=models.CharField(blank=True, choices=[('NORMAL', 'Normal'), ('UNDERWEIGHT', 'Underweight'), ('OVERWEIGHT', 'Overweight'), ('OBESE', 'Obese'), ('SEVERELY_UNDERWEIGHT', 'Severely Underweight'), ('MALNOURISHED', 'Malnourished')], help_text='Nutritional status assessment', max_length=50),
        ),
        migrations.AddField(
            model_name='vitalsigns',
            name='urine_anc',
            field=models.CharField(blank=True, help_text='Urine test results for Antenatal Care (e.g., Protein, Glucose, Leukocytes)', max_length=100),
        ),
    ]
