# Generated by Django 6.0 on 2026-01-26 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0004_add_vital_signs_pediatric_anc_fields'),
        ('consultations', '0005_alter_consultation_visit'),
        ('visits', '0006_timelineevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('MAJOR_SURGERY', 'Major Surgery'), ('MINOR_SURGERY', 'Minor Surgery'), ('ENDOSCOPIC', 'Endoscopic Procedure'), ('LAPAROSCOPIC', 'Laparoscopic Procedure'), ('DIAGNOSTIC', 'Diagnostic Procedure'), ('THERAPEUTIC', 'Therapeutic Procedure'), ('OTHER', 'Other')], default='OTHER', help_text='Type of operation', max_length=50)),
                ('operation_name', models.CharField(help_text='Name of the operation/procedure', max_length=255)),
                ('preoperative_diagnosis', models.TextField(help_text='Preoperative diagnosis')),
                ('postoperative_diagnosis', models.TextField(blank=True, help_text='Postoperative diagnosis (if different)')),
                ('indication', models.TextField(help_text='Clinical indication for the operation')),
                ('anesthesia_type', models.CharField(choices=[('GENERAL', 'General Anesthesia'), ('REGIONAL', 'Regional Anesthesia'), ('LOCAL', 'Local Anesthesia'), ('SEDATION', 'Conscious Sedation'), ('NONE', 'No Anesthesia'), ('OTHER', 'Other')], default='GENERAL', help_text='Type of anesthesia used', max_length=50)),
                ('anesthesia_notes', models.TextField(blank=True, help_text='Additional anesthesia notes')),
                ('procedure_description', models.TextField(help_text='Detailed description of the procedure performed')),
                ('findings', models.TextField(blank=True, help_text='Intraoperative findings')),
                ('technique', models.TextField(blank=True, help_text='Surgical technique used')),
                ('complications', models.TextField(blank=True, help_text='Any complications encountered')),
                ('estimated_blood_loss', models.CharField(blank=True, help_text="Estimated blood loss (e.g., '200ml', 'Minimal')", max_length=100)),
                ('specimens_sent', models.TextField(blank=True, help_text='Specimens sent for pathology (if any)')),
                ('postoperative_plan', models.TextField(blank=True, help_text='Postoperative care plan')),
                ('postoperative_instructions', models.TextField(blank=True, help_text='Postoperative instructions for patient')),
                ('operation_date', models.DateTimeField(help_text='Date and time of the operation')),
                ('operation_duration_minutes', models.IntegerField(blank=True, help_text='Duration of operation in minutes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the operation note was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the operation note was last updated')),
                ('anesthetist', models.ForeignKey(blank=True, help_text='Anesthetist who administered anesthesia', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_anesthetized', to=settings.AUTH_USER_MODEL)),
                ('assistant_surgeon', models.ForeignKey(blank=True, help_text='Assistant surgeon (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_assisted', to=settings.AUTH_USER_MODEL)),
                ('consultation', models.ForeignKey(help_text='Consultation this operation belongs to. Required for clinical context.', on_delete=django.db.models.deletion.PROTECT, related_name='operation_notes', to='consultations.consultation')),
                ('surgeon', models.ForeignKey(help_text='Surgeon/Doctor who performed the operation. PROTECT prevents deletion.', on_delete=django.db.models.deletion.PROTECT, related_name='operations_performed', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(help_text='Visit this operation note belongs to. Visit-scoped per EMR rules.', on_delete=django.db.models.deletion.CASCADE, related_name='operation_notes', to='visits.visit')),
            ],
            options={
                'verbose_name': 'Operation Note',
                'verbose_name_plural': 'Operation Notes',
                'db_table': 'operation_notes',
                'ordering': ['-operation_date'],
                'indexes': [models.Index(fields=['visit', '-operation_date'], name='operation_n_visit_i_b16cd0_idx'), models.Index(fields=['consultation'], name='operation_n_consult_c08160_idx'), models.Index(fields=['surgeon'], name='operation_n_surgeon_e79ae2_idx'), models.Index(fields=['operation_type'], name='operation_n_operati_a32a79_idx')],
            },
        ),
    ]
