# Generated by Django 6.0 on 2026-05-11 08:35

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0005_add_operation_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitalsigns',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Height in centimeters', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.1')), django.core.validators.MaxValueValidator(Decimal('300'))]),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='muac',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Mid-Upper Arm Circumference (MUAC) in cm - for pediatrics', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.1')), django.core.validators.MaxValueValidator(Decimal('50'))]),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kilograms', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.1')), django.core.validators.MaxValueValidator(Decimal('500'))]),
        ),
    ]
