# Generated by Django 5.2.7 on 2026-06-29 20:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0006_alter_vitalsigns_height_alter_vitalsigns_muac_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitalsigns',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Height in centimeters', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(300)]),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='muac',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Mid-Upper Arm Circumference (MUAC) in cm - for pediatrics', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kilograms', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(500)]),
        ),
    ]
