# Generated by Django 5.2.7 on 2026-06-29 22:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0007_alter_vitalsigns_height_alter_vitalsigns_muac_and_more'),
        ('patients', '0012_remove_patient_patients_nationa_health_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImmunizationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine', models.CharField(choices=[('BCG', 'BCG'), ('OPV', 'OPV'), ('PENTA', 'Pentavalent'), ('PCV', 'PCV'), ('ROTA', 'Rotavirus'), ('MEASLES', 'Measles'), ('YELLOW_FEVER', 'Yellow Fever'), ('HPV', 'HPV'), ('TD', 'Tetanus-Diphtheria')], max_length=32)),
                ('dose_number', models.PositiveSmallIntegerField(default=1)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('administered_date', models.DateField(blank=True, null=True)),
                ('batch_number', models.CharField(blank=True, max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('administered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='immunizations_administered', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='immunization_records', to='patients.patient')),
            ],
            options={
                'db_table': 'clinical_immunization_records',
                'ordering': ['scheduled_date', 'vaccine'],
                'indexes': [models.Index(fields=['patient', 'vaccine'], name='clinical_im_patient_53ab79_idx'), models.Index(fields=['scheduled_date'], name='clinical_im_schedul_9b6026_idx')],
            },
        ),
    ]
