# Generated by Django 6.0 on 2026-07-15 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0008_immunizationrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immunizationrecord',
            name='vaccine',
            field=models.CharField(choices=[('BCG', 'BCG'), ('HEP_B', 'Hepatitis B birth dose'), ('OPV', 'OPV'), ('IPV', 'Inactivated Polio Vaccine'), ('PENTA', 'Pentavalent'), ('PCV', 'PCV'), ('ROTA', 'Rotavirus'), ('MEASLES', 'Measles'), ('YELLOW_FEVER', 'Yellow Fever'), ('MEN_A', 'Meningococcal A'), ('MALARIA', 'Malaria vaccine'), ('HPV', 'HPV'), ('TD', 'Tetanus-Diphtheria')], max_length=32),
        ),
    ]
