# Generated by Django 6.0 on 2025-12-25 18:32

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('visits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_type', models.CharField(choices=[('clinical_decision_support', 'Clinical Decision Support'), ('nlp_summarization', 'NLP Summarization'), ('nlp_extraction', 'NLP Extraction'), ('automated_coding', 'Automated Coding (ICD-10/CPT)'), ('drug_interaction_check', 'Drug Interaction Check'), ('diagnosis_suggestion', 'Diagnosis Suggestion'), ('documentation_assistance', 'Documentation Assistance'), ('image_analysis', 'Image Analysis')], help_text='AI feature type', max_length=50, unique=True)),
                ('default_provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('local', 'Local Model'), ('azure_openai', 'Azure OpenAI')], help_text='Default provider for this feature', max_length=50)),
                ('default_model', models.CharField(help_text='Default model for this feature', max_length=200)),
                ('enabled', models.BooleanField(default=True, help_text='Whether this feature is enabled')),
                ('max_tokens', models.IntegerField(default=4000, help_text='Maximum tokens for requests', validators=[django.core.validators.MinValueValidator(1)])),
                ('temperature', models.DecimalField(decimal_places=2, default=Decimal('0.7'), help_text='Temperature for AI responses (0.0-2.0)', max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MinValueValidator(Decimal('2.0'))])),
                ('rate_limit_per_minute', models.IntegerField(default=60, help_text='Rate limit per minute per user', validators=[django.core.validators.MinValueValidator(1)])),
                ('cost_per_1k_tokens', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), help_text='Cost per 1k tokens (for cost tracking)', max_digits=10)),
                ('configuration', models.JSONField(blank=True, default=dict, help_text='Additional provider-specific configuration')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'AI Configuration',
                'verbose_name_plural': 'AI Configurations',
            },
        ),
        migrations.CreateModel(
            name='AICache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_type', models.CharField(choices=[('clinical_decision_support', 'Clinical Decision Support'), ('nlp_summarization', 'NLP Summarization'), ('nlp_extraction', 'NLP Extraction'), ('automated_coding', 'Automated Coding (ICD-10/CPT)'), ('drug_interaction_check', 'Drug Interaction Check'), ('diagnosis_suggestion', 'Diagnosis Suggestion'), ('documentation_assistance', 'Documentation Assistance'), ('image_analysis', 'Image Analysis')], db_index=True, max_length=50)),
                ('prompt_hash', models.CharField(db_index=True, help_text='SHA-256 hash of the prompt', max_length=64)),
                ('response', models.JSONField(help_text='Cached AI response')),
                ('expires_at', models.DateTimeField(db_index=True, help_text='When this cache entry expires')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hit_count', models.IntegerField(default=0, help_text='Number of times this cache was hit')),
            ],
            options={
                'indexes': [models.Index(fields=['feature_type', 'prompt_hash'], name='ai_integrat_feature_632508_idx'), models.Index(fields=['expires_at'], name='ai_integrat_expires_eb5df5_idx')],
                'unique_together': {('feature_type', 'prompt_hash')},
            },
        ),
        migrations.CreateModel(
            name='AIRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role', models.CharField(help_text='Role of the user at time of request', max_length=50)),
                ('feature_type', models.CharField(choices=[('clinical_decision_support', 'Clinical Decision Support'), ('nlp_summarization', 'NLP Summarization'), ('nlp_extraction', 'NLP Extraction'), ('automated_coding', 'Automated Coding (ICD-10/CPT)'), ('drug_interaction_check', 'Drug Interaction Check'), ('diagnosis_suggestion', 'Diagnosis Suggestion'), ('documentation_assistance', 'Documentation Assistance'), ('image_analysis', 'Image Analysis')], help_text='Type of AI feature used', max_length=50)),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('local', 'Local Model'), ('azure_openai', 'Azure OpenAI')], help_text='AI provider used', max_length=50)),
                ('model_name', models.CharField(help_text="Specific model used (e.g., 'gpt-4', 'claude-3-opus')", max_length=200)),
                ('prompt_tokens', models.IntegerField(default=0, help_text='Number of tokens in the prompt', validators=[django.core.validators.MinValueValidator(0)])),
                ('completion_tokens', models.IntegerField(default=0, help_text='Number of tokens in the completion', validators=[django.core.validators.MinValueValidator(0)])),
                ('total_tokens', models.IntegerField(default=0, help_text='Total tokens used', validators=[django.core.validators.MinValueValidator(0)])),
                ('cost_usd', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), help_text='Cost in USD for this request', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))])),
                ('request_payload', models.JSONField(blank=True, default=dict, help_text='Request payload (sanitized, no PHI)')),
                ('response_payload', models.JSONField(blank=True, default=dict, help_text='Response payload (sanitized, no PHI)')),
                ('success', models.BooleanField(default=True, help_text='Whether the request was successful')),
                ('error_message', models.TextField(blank=True, help_text='Error message if request failed')),
                ('response_time_ms', models.IntegerField(blank=True, help_text='Response time in milliseconds', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When the request was made')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the request', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata')),
                ('user', models.ForeignKey(help_text='User who initiated the AI request', on_delete=django.db.models.deletion.PROTECT, related_name='ai_requests', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(help_text='Visit this AI request is associated with', on_delete=django.db.models.deletion.PROTECT, related_name='ai_requests', to='visits.visit')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['visit', '-timestamp'], name='ai_integrat_visit_i_4fa9ae_idx'), models.Index(fields=['user', '-timestamp'], name='ai_integrat_user_id_9c2265_idx'), models.Index(fields=['feature_type', '-timestamp'], name='ai_integrat_feature_dd09ee_idx'), models.Index(fields=['provider', '-timestamp'], name='ai_integrat_provide_3157b3_idx')],
            },
        ),
    ]
