# Generated by Django 5.2.7

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_integration', '0002_alter_aicache_feature_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('SOAP', 'SOAP'), ('summary', 'Summary'), ('discharge', 'Discharge')], help_text='Type of note (SOAP, summary, discharge)', max_length=20)),
                ('raw_transcript', models.TextField(blank=True, help_text='Original transcript or bullet notes used for generation')),
                ('ai_generated_note', models.TextField(blank=True, help_text='AI-generated structured note')),
                ('doctor_edited_note', models.TextField(blank=True, help_text='Final note after doctor edit/approval')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.ForeignKey(blank=True, help_text='Related appointment if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinical_notes', to='appointments.appointment')),
                ('doctor', models.ForeignKey(help_text='Doctor who created/approved the note', on_delete=django.db.models.deletion.PROTECT, related_name='clinical_notes_authored', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(help_text='Patient this note is for', on_delete=django.db.models.deletion.CASCADE, related_name='clinical_notes', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Clinical Note',
                'verbose_name_plural': 'Clinical Notes',
                'db_table': 'clinical_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='clinicalnote',
            index=models.Index(fields=['patient'], name='clinical_no_patient_6a8c0d_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalnote',
            index=models.Index(fields=['doctor'], name='clinical_no_doctor__b2e8f2_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalnote',
            index=models.Index(fields=['appointment'], name='clinical_no_appoint_9c4a1b_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalnote',
            index=models.Index(fields=['note_type'], name='clinical_no_note_ty_2d4e5f_idx'),
        ),
    ]
