# Generated by Django 5.2.7 on 2026-05-09 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_integration', '0003_clinical_note'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='clinicalnote',
            new_name='clinical_no_patient_0c8752_idx',
            old_name='clinical_no_patient_6a8c0d_idx',
        ),
        migrations.RenameIndex(
            model_name='clinicalnote',
            new_name='clinical_no_doctor__68136e_idx',
            old_name='clinical_no_doctor__b2e8f2_idx',
        ),
        migrations.RenameIndex(
            model_name='clinicalnote',
            new_name='clinical_no_appoint_e5bbad_idx',
            old_name='clinical_no_appoint_9c4a1b_idx',
        ),
        migrations.RenameIndex(
            model_name='clinicalnote',
            new_name='clinical_no_note_ty_54cd6d_idx',
            old_name='clinical_no_note_ty_2d4e5f_idx',
        ),
        migrations.AlterField(
            model_name='aicache',
            name='feature_type',
            field=models.CharField(choices=[('clinical_decision_support', 'Clinical Decision Support'), ('nlp_summarization', 'NLP Summarization'), ('nlp_extraction', 'NLP Extraction'), ('automated_coding', 'Automated Coding (ICD-11/CPT)'), ('drug_interaction_check', 'Drug Interaction Check'), ('diagnosis_suggestion', 'Diagnosis Suggestion'), ('documentation_assistance', 'Documentation Assistance'), ('image_analysis', 'Image Analysis'), ('clinical_note_generation', 'Clinical Note Generation')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='aiconfiguration',
            name='feature_type',
            field=models.CharField(choices=[('clinical_decision_support', 'Clinical Decision Support'), ('nlp_summarization', 'NLP Summarization'), ('nlp_extraction', 'NLP Extraction'), ('automated_coding', 'Automated Coding (ICD-11/CPT)'), ('drug_interaction_check', 'Drug Interaction Check'), ('diagnosis_suggestion', 'Diagnosis Suggestion'), ('documentation_assistance', 'Documentation Assistance'), ('image_analysis', 'Image Analysis'), ('clinical_note_generation', 'Clinical Note Generation')], help_text='AI feature type', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='airequest',
            name='feature_type',
            field=models.CharField(choices=[('clinical_decision_support', 'Clinical Decision Support'), ('nlp_summarization', 'NLP Summarization'), ('nlp_extraction', 'NLP Extraction'), ('automated_coding', 'Automated Coding (ICD-11/CPT)'), ('drug_interaction_check', 'Drug Interaction Check'), ('diagnosis_suggestion', 'Diagnosis Suggestion'), ('documentation_assistance', 'Documentation Assistance'), ('image_analysis', 'Image Analysis'), ('clinical_note_generation', 'Clinical Note Generation')], help_text='Type of AI feature used', max_length=50),
        ),
    ]
