# Generated by Django 6.0 on 2026-05-11 08:32

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_integration', '0004_rename_clinical_no_patient_6a8c0d_idx_clinical_no_patient_0c8752_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiconfiguration',
            name='temperature',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.7'), help_text='Temperature for AI responses (0.0-2.0)', max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('2.0'))]),
        ),
    ]
