# Generated by Django 5.2.7 on 2026-06-29 20:19

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_integration', '0005_alter_aiconfiguration_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiconfiguration',
            name='temperature',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.7'), help_text='Temperature for AI responses (0.0-2.0)', max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MinValueValidator(Decimal('2.0'))]),
        ),
        migrations.AlterField(
            model_name='clinicalnote',
            name='note_type',
            field=models.CharField(choices=[('SOAP', 'SOAP'), ('Antenatal', 'Antenatal'), ('summary', 'Summary'), ('discharge', 'Discharge')], help_text='Type of note (SOAP, summary, discharge)', max_length=20),
        ),
    ]
