# Generated by Django 6.0 on 2025-12-24 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0002_initial'),
        ('visits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(choices=[('CARDIOLOGY', 'Cardiology'), ('DERMATOLOGY', 'Dermatology'), ('ENDOCRINOLOGY', 'Endocrinology'), ('GASTROENTEROLOGY', 'Gastroenterology'), ('HEMATOLOGY', 'Hematology'), ('INFECTIOUS_DISEASE', 'Infectious Disease'), ('NEPHROLOGY', 'Nephrology'), ('NEUROLOGY', 'Neurology'), ('ONCOLOGY', 'Oncology'), ('OPHTHALMOLOGY', 'Ophthalmology'), ('ORTHOPEDICS', 'Orthopedics'), ('OTOLARYNGOLOGY', 'Otolaryngology'), ('PEDIATRICS', 'Pediatrics'), ('PSYCHIATRY', 'Psychiatry'), ('PULMONOLOGY', 'Pulmonology'), ('RHEUMATOLOGY', 'Rheumatology'), ('UROLOGY', 'Urology'), ('OTHER', 'Other')], help_text='Specialty to refer to', max_length=50)),
                ('specialist_name', models.CharField(help_text='Name of the specialist or clinic', max_length=200)),
                ('specialist_contact', models.CharField(blank=True, help_text='Contact information for the specialist', max_length=200)),
                ('reason', models.TextField(help_text='Reason for referral')),
                ('clinical_summary', models.TextField(blank=True, help_text='Clinical summary for the specialist')),
                ('urgency', models.CharField(choices=[('ROUTINE', 'Routine'), ('URGENT', 'Urgent'), ('EMERGENCY', 'Emergency')], default='ROUTINE', help_text='Urgency level of the referral', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Current status of the referral', max_length=20)),
                ('accepted_at', models.DateTimeField(blank=True, help_text='When the referral was accepted', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the referral was completed', null=True)),
                ('specialist_notes', models.TextField(blank=True, help_text='Notes from the specialist')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the referral was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the referral was last updated')),
                ('consultation', models.ForeignKey(help_text='Consultation that triggered this referral', on_delete=django.db.models.deletion.PROTECT, related_name='referrals', to='consultations.consultation')),
                ('referred_by', models.ForeignKey(help_text='Doctor who created the referral', on_delete=django.db.models.deletion.PROTECT, related_name='referrals_created', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(help_text='Visit this referral belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='visits.visit')),
            ],
            options={
                'verbose_name': 'Referral',
                'verbose_name_plural': 'Referrals',
                'db_table': 'referrals',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['visit'], name='referrals_visit_i_e14793_idx'), models.Index(fields=['consultation'], name='referrals_consult_059cfc_idx'), models.Index(fields=['status'], name='referrals_status_135a0e_idx'), models.Index(fields=['specialty'], name='referrals_special_d7d77c_idx'), models.Index(fields=['created_at'], name='referrals_created_995256_idx')],
            },
        ),
    ]
