# Generated by Django 6.0 on 2025-12-24 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('visits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('APPOINTMENT_REMINDER', 'Appointment Reminder'), ('APPOINTMENT_CONFIRMED', 'Appointment Confirmed'), ('APPOINTMENT_CANCELLED', 'Appointment Cancelled'), ('LAB_RESULT_READY', 'Lab Result Ready'), ('RADIOLOGY_RESULT_READY', 'Radiology Result Ready'), ('PRESCRIPTION_READY', 'Prescription Ready'), ('PAYMENT_RECEIPT', 'Payment Receipt'), ('SYSTEM_ALERT', 'System Alert')], help_text='Type of notification', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('BOUNCED', 'Bounced')], default='PENDING', help_text='Status of the notification', max_length=20)),
                ('recipient_email', models.EmailField(help_text='Email address of the recipient', max_length=254)),
                ('recipient_name', models.CharField(blank=True, help_text='Name of the recipient', max_length=255)),
                ('subject', models.CharField(help_text='Email subject', max_length=500)),
                ('email_body', models.TextField(help_text='Email body content (stored for audit)')),
                ('sent_at', models.DateTimeField(blank=True, help_text='When the email was sent', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if sending failed')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the notification was created')),
                ('appointment', models.ForeignKey(blank=True, help_text='Related appointment (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_notifications', to='appointments.appointment')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who triggered this notification (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_notifications_created', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(blank=True, help_text='Related visit (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_notifications', to='visits.visit')),
            ],
            options={
                'verbose_name': 'Email Notification',
                'verbose_name_plural': 'Email Notifications',
                'db_table': 'email_notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['notification_type'], name='email_notif_notific_345130_idx'), models.Index(fields=['status'], name='email_notif_status_242435_idx'), models.Index(fields=['recipient_email'], name='email_notif_recipie_7e984a_idx'), models.Index(fields=['created_at'], name='email_notif_created_c1707e_idx')],
            },
        ),
    ]
