# Generated by Django 5.2.7 on 2026-02-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_appointmentreminder'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='appointmentreminder',
            new_name='appointment_appoint_0135cb_idx',
            old_name='appt_reminder_appt_idx',
        ),
        migrations.RenameIndex(
            model_name='appointmentreminder',
            new_name='appointment_status_46b59c_idx',
            old_name='appt_reminder_status_idx',
        ),
        migrations.RenameIndex(
            model_name='appointmentreminder',
            new_name='appointment_channel_c35d5f_idx',
            old_name='appt_reminder_chan_idx',
        ),
        migrations.AlterField(
            model_name='appointmentreminder',
            name='channel',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('email', 'Email')], default='whatsapp', help_text='Channel used (whatsapp, sms, email)', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointmentreminder',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error if sending failed'),
        ),
        migrations.AlterField(
            model_name='appointmentreminder',
            name='hours_before',
            field=models.IntegerField(blank=True, help_text='Reminder sent this many hours before appointment (e.g. 24 or 2)', null=True),
        ),
        migrations.AlterField(
            model_name='appointmentreminder',
            name='sent_at',
            field=models.DateTimeField(blank=True, help_text='When the reminder was sent', null=True),
        ),
        migrations.AlterField(
            model_name='appointmentreminder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', help_text='Delivery status', max_length=20),
        ),
    ]
