# Generated by Django 5.2.7 on 2025-12-24 04:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0003_update_optional_fields_nullable'),
        ('visits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateTimeField(help_text='Date and time of the appointment')),
                ('duration_minutes', models.IntegerField(default=30, help_text='Duration of appointment in minutes')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show')], default='SCHEDULED', help_text='Status of the appointment', max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Reason for appointment or chief complaint')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the appointment')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the appointment was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the appointment was last updated')),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='When the appointment was cancelled', null=True)),
                ('cancellation_reason', models.TextField(blank=True, help_text='Reason for cancellation')),
                ('cancelled_by', models.ForeignKey(blank=True, help_text='User who cancelled this appointment', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments_cancelled', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(help_text='User who created this appointment. PROTECT prevents deletion.', on_delete=django.db.models.deletion.PROTECT, related_name='appointments_created', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(help_text='Doctor assigned to this appointment. PROTECT prevents deletion.', on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(help_text='Patient for this appointment', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient')),
                ('visit', models.ForeignKey(blank=True, help_text='Visit linked to this appointment (optional, set when visit is created)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='visits.visit')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'db_table': 'appointments',
                'ordering': ['appointment_date'],
                'indexes': [models.Index(fields=['patient'], name='appointment_patient_75a4eb_idx'), models.Index(fields=['doctor'], name='appointment_doctor__463335_idx'), models.Index(fields=['appointment_date'], name='appointment_appoint_8b74ac_idx'), models.Index(fields=['status'], name='appointment_status_9fecd6_idx'), models.Index(fields=['visit'], name='appointment_visit_i_224048_idx')],
            },
        ),
    ]
