# Generated by Django 5.2.7 on 2026-06-29 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_service_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='service_area',
        ),
    ]
