# Generated by Django 5.2.7 on 2025-12-30 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('DOCTOR', 'Doctor'), ('NURSE', 'Nurse'), ('LAB_TECH', 'Lab Technician'), ('RADIOLOGY_TECH', 'Radiology Technician'), ('PHARMACIST', 'Pharmacist'), ('RECEPTIONIST', 'Receptionist'), ('PATIENT', 'Patient')], help_text='User role for RBAC enforcement', max_length=50),
        ),
    ]
