# Generated by Django 6.0 on 2025-12-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RadiologyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imaging_type', models.CharField(choices=[('XRAY', 'X-Ray'), ('CT', 'CT Scan'), ('MRI', 'MRI'), ('US', 'Ultrasound')], help_text='Type of imaging study', max_length=10)),
                ('body_part', models.CharField(help_text='Body part to be imaged', max_length=100)),
                ('clinical_indication', models.TextField(help_text='Reason for imaging request')),
                ('priority', models.CharField(choices=[('ROUTINE', 'Routine'), ('URGENT', 'Urgent')], default='ROUTINE', help_text='Priority level of the order', max_length=10)),
                ('status', models.CharField(choices=[('ORDERED', 'Ordered'), ('SCHEDULED', 'Scheduled'), ('PERFORMED', 'Performed'), ('CANCELLED', 'Cancelled')], default='ORDERED', help_text='Status of the radiology order', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the radiology order was created')),
            ],
            options={
                'verbose_name': 'Radiology Order',
                'verbose_name_plural': 'Radiology Orders',
                'db_table': 'radiology_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RadiologyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_type', models.CharField(help_text="Type of radiology study requested (e.g., 'Chest X-Ray', 'CT Scan Head')", max_length=255)),
                ('study_code', models.CharField(blank=True, help_text='Radiology study code/identifier', max_length=100)),
                ('clinical_indication', models.TextField(blank=True, help_text='Clinical indication for the radiology study')),
                ('instructions', models.TextField(blank=True, help_text='Special instructions for the radiology study')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Status of the radiology request', max_length=20)),
                ('report', models.TextField(blank=True, help_text='Radiology report/interpretation (PHI - only Radiology Tech can update)', null=True)),
                ('report_date', models.DateTimeField(blank=True, help_text='When the report was posted', null=True)),
                ('image_count', models.IntegerField(blank=True, help_text='Number of images in the study', null=True)),
                ('image_metadata', models.JSONField(blank=True, default=dict, help_text='Image metadata (e.g., modality, series, slices) - no raw DICOM')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the radiology request was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the radiology request was last updated')),
            ],
            options={
                'verbose_name': 'Radiology Request',
                'verbose_name_plural': 'Radiology Requests',
                'db_table': 'radiology_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RadiologyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.TextField(help_text='Radiology report/interpretation. No diagnosis or clinical interpretation.')),
                ('finding_flag', models.CharField(choices=[('NORMAL', 'Normal'), ('ABNORMAL', 'Abnormal'), ('CRITICAL', 'Critical Finding')], default='NORMAL', help_text='Finding flag for the result', max_length=10)),
                ('image_count', models.IntegerField(default=0, help_text='Number of images in the study')),
                ('image_metadata', models.JSONField(blank=True, default=dict, help_text='Image metadata (e.g., modality, series, slices) - no raw DICOM')),
                ('reported_at', models.DateTimeField(auto_now_add=True, help_text='When the result was reported')),
            ],
            options={
                'verbose_name': 'Radiology Result',
                'verbose_name_plural': 'Radiology Results',
                'db_table': 'radiology_results',
                'ordering': ['-reported_at'],
            },
        ),
    ]
