# Generated by Django 6.0 on 2025-12-22 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0002_initial'),
        ('radiology', '0001_initial'),
        ('visits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='radiologyorder',
            name='ordered_by',
            field=models.ForeignKey(help_text='Doctor who ordered the radiology study. PROTECT prevents deletion.', on_delete=django.db.models.deletion.PROTECT, related_name='radiology_orders_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='radiologyorder',
            name='visit',
            field=models.ForeignKey(help_text='Visit is the single source of clinical truth. Radiology order is visit-scoped.', on_delete=django.db.models.deletion.CASCADE, related_name='radiology_orders', to='visits.visit'),
        ),
        migrations.AddField(
            model_name='radiologyrequest',
            name='consultation',
            field=models.ForeignKey(help_text='Radiology request requires consultation context. Cannot exist without consultation.', on_delete=django.db.models.deletion.CASCADE, related_name='radiology_requests', to='consultations.consultation'),
        ),
        migrations.AddField(
            model_name='radiologyrequest',
            name='ordered_by',
            field=models.ForeignKey(help_text='Doctor who ordered the study', on_delete=django.db.models.deletion.PROTECT, related_name='radiology_requests_ordered', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='radiologyrequest',
            name='reported_by',
            field=models.ForeignKey(blank=True, help_text='Radiology Tech who posted the report', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='radiology_requests_reported', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='radiologyrequest',
            name='visit',
            field=models.ForeignKey(help_text='Visit is the single source of clinical truth. Radiology request is visit-scoped.', on_delete=django.db.models.deletion.CASCADE, related_name='radiology_requests', to='visits.visit'),
        ),
        migrations.AddField(
            model_name='radiologyresult',
            name='radiology_order',
            field=models.OneToOneField(help_text='Radiology order this result belongs to. One result per order.', on_delete=django.db.models.deletion.CASCADE, related_name='result', to='radiology.radiologyorder'),
        ),
        migrations.AddField(
            model_name='radiologyresult',
            name='reported_by',
            field=models.ForeignKey(help_text='Radiology Tech who reported this result. PROTECT prevents deletion.', on_delete=django.db.models.deletion.PROTECT, related_name='radiology_results_reported', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='radiologyorder',
            index=models.Index(fields=['visit'], name='radiology_o_visit_i_8fb3e6_idx'),
        ),
        migrations.AddIndex(
            model_name='radiologyorder',
            index=models.Index(fields=['status'], name='radiology_o_status_6b01fe_idx'),
        ),
        migrations.AddIndex(
            model_name='radiologyorder',
            index=models.Index(fields=['ordered_by'], name='radiology_o_ordered_a51691_idx'),
        ),
        migrations.AddIndex(
            model_name='radiologyorder',
            index=models.Index(fields=['imaging_type'], name='radiology_o_imaging_f9f5f1_idx'),
        ),
        migrations.AddIndex(
            model_name='radiologyrequest',
            index=models.Index(fields=['visit'], name='radiology_r_visit_i_c8601d_idx'),
        ),
        migrations.AddIndex(
            model_name='radiologyrequest',
            index=models.Index(fields=['consultation'], name='radiology_r_consult_354a69_idx'),
        ),
        migrations.AddIndex(
            model_name='radiologyrequest',
            index=models.Index(fields=['status'], name='radiology_r_status_33b273_idx'),
        ),
        migrations.AddIndex(
            model_name='radiologyrequest',
            index=models.Index(fields=['ordered_by'], name='radiology_r_ordered_829f6a_idx'),
        ),
        migrations.AddIndex(
            model_name='radiologyresult',
            index=models.Index(fields=['radiology_order'], name='radiology_r_radiolo_5e5285_idx'),
        ),
        migrations.AddIndex(
            model_name='radiologyresult',
            index=models.Index(fields=['reported_by'], name='radiology_r_reporte_8fe1db_idx'),
        ),
        migrations.AddIndex(
            model_name='radiologyresult',
            index=models.Index(fields=['reported_at'], name='radiology_r_reporte_967960_idx'),
        ),
    ]
