# Generated by Django 6.0 on 2025-12-24 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiology', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RadiologyStudyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_code', models.CharField(help_text='Unique code for the radiology study (e.g., CXR, CT-HEAD, MRI-BRAIN)', max_length=50, unique=True)),
                ('study_name', models.CharField(help_text='Full name of the radiology study', max_length=200)),
                ('category', models.CharField(choices=[('X_RAY', 'X-Ray'), ('CT_SCAN', 'CT Scan'), ('MRI', 'MRI'), ('ULTRASOUND', 'Ultrasound'), ('MAMMOGRAPHY', 'Mammography'), ('DEXA_SCAN', 'DEXA Scan'), ('NUCLEAR_MEDICINE', 'Nuclear Medicine'), ('FLUOROSCOPY', 'Fluoroscopy'), ('ANGIOGRAPHY', 'Angiography'), ('ECHOCARDIOGRAM', 'Echocardiogram'), ('OTHER', 'Other')], help_text='Category of the radiology study', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Description of what the study examines')),
                ('protocol', models.TextField(blank=True, help_text='Protocol or procedure details for performing the study')),
                ('preparation_instructions', models.TextField(blank=True, help_text='Patient preparation instructions (e.g., fasting, contrast)')),
                ('contrast_required', models.BooleanField(default=False, help_text='Whether contrast agent is required')),
                ('contrast_type', models.CharField(blank=True, help_text='Type of contrast if required (e.g., IV, Oral, Rectal)', max_length=100)),
                ('estimated_duration_minutes', models.IntegerField(blank=True, help_text='Estimated duration of the study in minutes', null=True)),
                ('body_part', models.CharField(blank=True, help_text='Body part or region examined (e.g., Head, Chest, Abdomen)', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this study type is currently available for ordering')),
                ('requires_sedation', models.BooleanField(default=False, help_text='Whether sedation is required for this study')),
                ('radiation_dose', models.CharField(blank=True, help_text='Typical radiation dose (for studies involving radiation)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the study type was added to the catalog')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the study type was last updated')),
                ('created_by', models.ForeignKey(help_text='User who created this study type in the catalog', on_delete=django.db.models.deletion.PROTECT, related_name='radiology_study_types_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Radiology Study Type',
                'verbose_name_plural': 'Radiology Study Types',
                'db_table': 'radiology_study_types',
                'ordering': ['category', 'study_name'],
                'indexes': [models.Index(fields=['study_code'], name='radiology_s_study_c_bda2a2_idx'), models.Index(fields=['category'], name='radiology_s_categor_6705a9_idx'), models.Index(fields=['is_active'], name='radiology_s_is_acti_c77c3d_idx'), models.Index(fields=['study_name'], name='radiology_s_study_n_5ebec4_idx')],
            },
        ),
    ]
