# Generated by Django 5.2.7 on 2026-01-08 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiology', '0004_alter_radiologyrequest_study_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RadiologyTestTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Template name (e.g., 'Chest X-Ray', 'CT Scan Head')", max_length=200)),
                ('category', models.CharField(blank=True, help_text="Template category (e.g., 'X-Ray', 'CT Scan', 'Ultrasound', 'MRI')", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of when to use this template')),
                ('imaging_type', models.CharField(choices=[('XRAY', 'X-Ray'), ('CT', 'CT Scan'), ('MRI', 'MRI'), ('US', 'Ultrasound')], help_text='Type of imaging study', max_length=10)),
                ('body_part', models.CharField(help_text="Body part to be imaged (e.g., 'Chest', 'Head', 'Abdomen')", max_length=100)),
                ('study_code', models.CharField(blank=True, help_text='Radiology study code/identifier', max_length=100)),
                ('default_clinical_indication', models.TextField(blank=True, help_text='Default clinical indication text (can be edited when applying template)')),
                ('default_priority', models.CharField(choices=[('ROUTINE', 'Routine'), ('URGENT', 'Urgent')], default='ROUTINE', help_text='Default priority level', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this template is active and available for use')),
                ('usage_count', models.IntegerField(default=0, help_text='Number of times this template has been used')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='User who created this template', on_delete=django.db.models.deletion.PROTECT, related_name='radiology_test_templates_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Radiology Test Template',
                'verbose_name_plural': 'Radiology Test Templates',
                'db_table': 'radiology_test_templates',
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='radiology_t_categor_c44eaa_idx'), models.Index(fields=['imaging_type'], name='radiology_t_imaging_4cdb2b_idx'), models.Index(fields=['created_by'], name='radiology_t_created_d34b38_idx')],
            },
        ),
    ]
