# Generated by Django 5.2.7 on 2026-01-10 16:09

import apps.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0005_alter_consultation_visit'),
        ('radiology', '0005_add_test_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiologyrequest',
            name='consultation',
            field=models.ForeignKey(help_text='Radiology request requires consultation context. Cannot exist without consultation.', on_delete=django.db.models.deletion.CASCADE, related_name='radiology_requests', to='consultations.consultation', validators=[apps.core.validators.validate_consultation_required]),
        ),
    ]
