# Generated by Django 6.0 on 2026-01-10 17:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiology', '0006_alter_radiologyrequest_consultation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineImageMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Unique identifier for the image (generated client-side, UUID-based)', unique=True)),
                ('filename', models.CharField(help_text='Original filename of the image', max_length=255)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('mime_type', models.CharField(help_text="MIME type of the image (e.g., 'image/jpeg', 'application/dicom')", max_length=100)),
                ('checksum', models.CharField(db_index=True, help_text='SHA-256 checksum of the image file (validated server-side)', max_length=64)),
                ('image_metadata', models.JSONField(blank=True, default=dict, help_text='Image metadata (DICOM tags, JPEG EXIF, etc.) - no raw binary')),
                ('status', models.CharField(choices=[('PENDING', 'Pending - Metadata not yet uploaded'), ('METADATA_UPLOADED', 'Metadata Uploaded - Waiting for binary upload'), ('BINARY_UPLOADED', 'Binary Uploaded - Waiting for server ACK'), ('ACK_RECEIVED', 'ACK Received - Safe to delete local copy'), ('FAILED', 'Failed - Requires manual intervention')], db_index=True, default='PENDING', help_text='Current sync status of this image', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When metadata was queued (client-side timestamp)')),
                ('metadata_uploaded_at', models.DateTimeField(blank=True, help_text='When metadata was successfully uploaded to server', null=True)),
                ('binary_uploaded_at', models.DateTimeField(blank=True, help_text='When binary was successfully uploaded to server', null=True)),
                ('ack_received_at', models.DateTimeField(blank=True, help_text='When server ACK was received (safe to delete local copy)', null=True)),
                ('failed_at', models.DateTimeField(blank=True, help_text='When upload failed (if status is FAILED)', null=True)),
                ('failure_reason', models.TextField(blank=True, help_text='Reason for failure (if status is FAILED)')),
                ('retry_count', models.IntegerField(default=0, help_text='Number of times upload has been retried')),
                ('last_retry_at', models.DateTimeField(blank=True, help_text='When upload was last retried', null=True)),
                ('radiology_order', models.ForeignKey(help_text='Radiology order this image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='offline_image_metadata', to='radiology.radiologyorder')),
            ],
            options={
                'verbose_name': 'Offline Image Metadata',
                'verbose_name_plural': 'Offline Image Metadata',
                'db_table': 'radiology_offline_image_metadata',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RadiologyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.FileField(help_text='Image file (DICOM or JPEG) - stored outside DB', upload_to='radiology/images/%Y/%m/%d/')),
                ('checksum', models.CharField(db_index=True, help_text='SHA-256 checksum (validated server-side)', max_length=64)),
                ('image_metadata', models.JSONField(blank=True, default=dict, help_text='Image metadata (DICOM tags, JPEG EXIF, etc.)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='When image was successfully uploaded')),
                ('validated_at', models.DateTimeField(blank=True, help_text='When checksum was validated', null=True)),
                ('offline_metadata', models.OneToOneField(help_text='Link to offline metadata that was uploaded', on_delete=django.db.models.deletion.CASCADE, related_name='server_image', to='radiology.offlineimagemetadata')),
                ('radiology_order', models.ForeignKey(help_text='Radiology order this image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='radiology.radiologyorder')),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded this image (Radiology Tech)', on_delete=django.db.models.deletion.PROTECT, related_name='radiology_images_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Radiology Image',
                'verbose_name_plural': 'Radiology Images',
                'db_table': 'radiology_images',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='offlineimagemetadata',
            index=models.Index(fields=['status'], name='radiology_o_status_1d95fa_idx'),
        ),
        migrations.AddIndex(
            model_name='offlineimagemetadata',
            index=models.Index(fields=['radiology_order'], name='radiology_o_radiolo_d8f801_idx'),
        ),
        migrations.AddIndex(
            model_name='offlineimagemetadata',
            index=models.Index(fields=['image_uuid'], name='radiology_o_image_u_f8a7db_idx'),
        ),
        migrations.AddIndex(
            model_name='offlineimagemetadata',
            index=models.Index(fields=['checksum'], name='radiology_o_checksu_1a2f42_idx'),
        ),
        migrations.AddIndex(
            model_name='offlineimagemetadata',
            index=models.Index(fields=['created_at'], name='radiology_o_created_187d48_idx'),
        ),
        migrations.AddIndex(
            model_name='radiologyimage',
            index=models.Index(fields=['radiology_order'], name='radiology_i_radiolo_acadbf_idx'),
        ),
        migrations.AddIndex(
            model_name='radiologyimage',
            index=models.Index(fields=['checksum'], name='radiology_i_checksu_b36b5e_idx'),
        ),
        migrations.AddIndex(
            model_name='radiologyimage',
            index=models.Index(fields=['uploaded_at'], name='radiology_i_uploade_5168e7_idx'),
        ),
        migrations.AddConstraint(
            model_name='radiologyimage',
            constraint=models.UniqueConstraint(fields=('checksum',), name='unique_radiology_image_checksum'),
        ),
    ]
