# Generated by Django 5.2.7 on 2026-01-10 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiology', '0007_offlineimagemetadata_radiologyimage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RadiologySeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_uid', models.CharField(db_index=True, help_text='DICOM SeriesInstanceUID or generated UUID for series identification', max_length=255, unique=True)),
                ('series_number', models.IntegerField(blank=True, help_text='Series number (from DICOM)', null=True)),
                ('series_description', models.CharField(blank=True, help_text='Series description', max_length=255)),
                ('modality', models.CharField(blank=True, help_text='Modality (e.g., CR, CT, MR, US)', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When series was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When series was last updated')),
            ],
            options={
                'verbose_name': 'Radiology Series',
                'verbose_name_plural': 'Radiology Series',
                'db_table': 'radiology_series',
                'ordering': ['series_number', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='RadiologyStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_uid', models.CharField(db_index=True, help_text='DICOM StudyInstanceUID or generated UUID for study identification', max_length=255, unique=True)),
                ('study_date', models.DateField(blank=True, help_text='Study date (from DICOM or imaging date)', null=True)),
                ('study_description', models.CharField(blank=True, help_text='Study description', max_length=255)),
                ('modality', models.CharField(blank=True, help_text='Modality (e.g., CR, CT, MR, US)', max_length=10)),
                ('patient_name', models.CharField(blank=True, help_text='Patient name (snapshot from visit)', max_length=255)),
                ('patient_id', models.CharField(blank=True, help_text='Patient ID (snapshot from visit)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When study was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When study was last updated')),
            ],
            options={
                'verbose_name': 'Radiology Study',
                'verbose_name_plural': 'Radiology Studies',
                'db_table': 'radiology_studies',
                'ordering': ['-study_date', '-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='radiologyimage',
            options={'ordering': ['instance_number', 'uploaded_at'], 'verbose_name': 'Radiology Image', 'verbose_name_plural': 'Radiology Images'},
        ),
        migrations.RemoveIndex(
            model_name='radiologyimage',
            name='radiology_i_radiolo_acadbf_idx',
        ),
        migrations.RemoveField(
            model_name='radiologyimage',
            name='image_file',
        ),
        migrations.RemoveField(
            model_name='radiologyimage',
            name='radiology_order',
        ),
        migrations.AddField(
            model_name='radiologyimage',
            name='file_key',
            field=models.CharField(blank=True, db_index=True, help_text='File key/path in storage (S3 key, MinIO key, or filesystem path)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='radiologyimage',
            name='file_size',
            field=models.BigIntegerField(blank=True, help_text='File size in bytes', null=True),
        ),
        migrations.AddField(
            model_name='radiologyimage',
            name='filename',
            field=models.CharField(blank=True, help_text='Original filename', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='radiologyimage',
            name='image_uid',
            field=models.CharField(blank=True, db_index=True, help_text='DICOM SOPInstanceUID or generated UUID for image identification', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='radiologyimage',
            name='instance_number',
            field=models.IntegerField(blank=True, help_text='Instance number (from DICOM)', null=True),
        ),
        migrations.AddField(
            model_name='radiologyimage',
            name='mime_type',
            field=models.CharField(blank=True, help_text="MIME type (e.g., 'application/dicom', 'image/jpeg')", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='radiologyimage',
            name='checksum',
            field=models.CharField(blank=True, db_index=True, help_text='SHA-256 checksum (validated server-side)', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='radiologyimage',
            name='offline_metadata',
            field=models.OneToOneField(blank=True, help_text='Link to offline metadata (if uploaded via offline sync)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='server_image', to='radiology.offlineimagemetadata'),
        ),
        migrations.AddField(
            model_name='radiologyimage',
            name='series',
            field=models.ForeignKey(blank=True, help_text='Series this image belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='radiology.radiologyseries'),
        ),
        migrations.AddIndex(
            model_name='radiologyimage',
            index=models.Index(fields=['series'], name='radiology_i_series__06bf01_idx'),
        ),
        migrations.AddIndex(
            model_name='radiologyimage',
            index=models.Index(fields=['image_uid'], name='radiology_i_image_u_b5d80a_idx'),
        ),
        migrations.AddIndex(
            model_name='radiologyimage',
            index=models.Index(fields=['file_key'], name='radiology_i_file_ke_dc4fca_idx'),
        ),
        migrations.AddField(
            model_name='radiologystudy',
            name='radiology_order',
            field=models.OneToOneField(help_text='Radiology order this study belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='study', to='radiology.radiologyorder'),
        ),
        migrations.AddField(
            model_name='radiologyseries',
            name='study',
            field=models.ForeignKey(help_text='Study this series belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='series', to='radiology.radiologystudy'),
        ),
        migrations.AddIndex(
            model_name='radiologystudy',
            index=models.Index(fields=['study_uid'], name='radiology_s_study_u_0e8792_idx'),
        ),
        migrations.AddIndex(
            model_name='radiologystudy',
            index=models.Index(fields=['radiology_order'], name='radiology_s_radiolo_c68803_idx'),
        ),
        migrations.AddIndex(
            model_name='radiologystudy',
            index=models.Index(fields=['study_date'], name='radiology_s_study_d_6bbb98_idx'),
        ),
        migrations.AddIndex(
            model_name='radiologyseries',
            index=models.Index(fields=['series_uid'], name='radiology_s_series__e11514_idx'),
        ),
        migrations.AddIndex(
            model_name='radiologyseries',
            index=models.Index(fields=['study'], name='radiology_s_study_i_976552_idx'),
        ),
        migrations.AddIndex(
            model_name='radiologyseries',
            index=models.Index(fields=['series_number'], name='radiology_s_series__38d1c5_idx'),
        ),
        migrations.AddConstraint(
            model_name='radiologyseries',
            constraint=models.UniqueConstraint(fields=('study', 'series_uid'), name='unique_series_per_study'),
        ),
    ]
