# Generated by Django 5.2.7 on 2026-01-11 10:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiology', '0008_radiologyseries_radiologystudy_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUploadSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Unique identifier for this upload session', unique=True)),
                ('device_id', models.CharField(blank=True, help_text='Device identifier (for tracking which device uploaded)', max_length=255)),
                ('device_info', models.JSONField(blank=True, default=dict, help_text='Device information (OS, browser, etc.)')),
                ('status', models.CharField(choices=[('QUEUED', 'Queued - Ready to upload'), ('UPLOADING', 'Uploading - Currently syncing'), ('SYNCED', 'Synced - All images uploaded and ACK received'), ('FAILED', 'Failed - Requires manual intervention'), ('PARTIAL', 'Partial - Some images failed')], db_index=True, default='QUEUED', help_text='Current status of the upload session', max_length=20)),
                ('total_images', models.PositiveIntegerField(default=0, help_text='Total number of images in this session')),
                ('images_uploaded', models.PositiveIntegerField(default=0, help_text='Number of images successfully uploaded')),
                ('images_failed', models.PositiveIntegerField(default=0, help_text='Number of images that failed to upload')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the session was created')),
                ('started_at', models.DateTimeField(blank=True, help_text='When the upload started', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the upload completed (successfully or failed)', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if upload failed')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this session', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload_sessions', to=settings.AUTH_USER_MODEL)),
                ('radiology_order', models.ForeignKey(help_text='Radiology order this session belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='upload_sessions', to='radiology.radiologyorder')),
            ],
            options={
                'verbose_name': 'Image Upload Session',
                'verbose_name_plural': 'Image Upload Sessions',
                'db_table': 'image_upload_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImageUploadItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.PositiveIntegerField(help_text='Sequence number of this image in the session')),
                ('upload_status', models.CharField(choices=[('PENDING', 'Pending'), ('METADATA_UPLOADED', 'Metadata Uploaded'), ('BINARY_UPLOADED', 'Binary Uploaded'), ('ACK_RECEIVED', 'ACK Received'), ('FAILED', 'Failed')], default='PENDING', help_text='Upload status of this specific image', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if upload failed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.OneToOneField(help_text='Offline image metadata for this item', on_delete=django.db.models.deletion.CASCADE, related_name='upload_item', to='radiology.offlineimagemetadata')),
                ('session', models.ForeignKey(help_text='Upload session this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='upload_items', to='radiology.imageuploadsession')),
            ],
            options={
                'verbose_name': 'Image Upload Item',
                'verbose_name_plural': 'Image Upload Items',
                'db_table': 'image_upload_items',
                'ordering': ['session', 'sequence_number'],
            },
        ),
        migrations.AddIndex(
            model_name='imageuploadsession',
            index=models.Index(fields=['session_uuid'], name='image_uploa_session_8a6597_idx'),
        ),
        migrations.AddIndex(
            model_name='imageuploadsession',
            index=models.Index(fields=['radiology_order', 'status'], name='image_uploa_radiolo_550a3f_idx'),
        ),
        migrations.AddIndex(
            model_name='imageuploadsession',
            index=models.Index(fields=['status', 'created_at'], name='image_uploa_status_b4121f_idx'),
        ),
        migrations.AddIndex(
            model_name='imageuploaditem',
            index=models.Index(fields=['session', 'sequence_number'], name='image_uploa_session_b84d16_idx'),
        ),
        migrations.AddIndex(
            model_name='imageuploaditem',
            index=models.Index(fields=['upload_status'], name='image_uploa_upload__207bfa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='imageuploaditem',
            unique_together={('session', 'sequence_number')},
        ),
    ]
