# Generated by Django 5.2.7 on 2026-01-11 11:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiology', '0009_imageuploadsession_imageuploaditem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='imageuploaditem',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='imageuploaditem',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='imageuploaditem',
            name='session',
        ),
        migrations.RemoveIndex(
            model_name='imageuploadsession',
            name='image_uploa_session_8a6597_idx',
        ),
        migrations.RemoveIndex(
            model_name='imageuploadsession',
            name='image_uploa_status_b4121f_idx',
        ),
        migrations.RemoveField(
            model_name='imageuploadsession',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='imageuploadsession',
            name='device_id',
        ),
        migrations.RemoveField(
            model_name='imageuploadsession',
            name='device_info',
        ),
        migrations.RemoveField(
            model_name='imageuploadsession',
            name='images_failed',
        ),
        migrations.RemoveField(
            model_name='imageuploadsession',
            name='images_uploaded',
        ),
        migrations.RemoveField(
            model_name='imageuploadsession',
            name='session_uuid',
        ),
        migrations.RemoveField(
            model_name='imageuploadsession',
            name='started_at',
        ),
        migrations.RemoveField(
            model_name='imageuploadsession',
            name='total_images',
        ),
        migrations.AddField(
            model_name='imageuploadsession',
            name='binary_uploaded',
            field=models.BooleanField(default=False, help_text='Whether binary data has been uploaded to server'),
        ),
        migrations.AddField(
            model_name='imageuploadsession',
            name='binary_uploaded_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when binary data was uploaded', null=True),
        ),
        migrations.AddField(
            model_name='imageuploadsession',
            name='bytes_uploaded',
            field=models.PositiveIntegerField(default=0, help_text='Number of bytes uploaded so far'),
        ),
        migrations.AddField(
            model_name='imageuploadsession',
            name='checksum',
            field=models.CharField(blank=True, help_text='SHA-256 checksum of the image file', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='imageuploadsession',
            name='content_type',
            field=models.CharField(blank=True, help_text='MIME type (e.g., image/jpeg, image/dicom)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='imageuploadsession',
            name='error_code',
            field=models.CharField(blank=True, help_text='Error code for programmatic handling', max_length=50),
        ),
        migrations.AddField(
            model_name='imageuploadsession',
            name='file_name',
            field=models.CharField(blank=True, help_text='Original filename', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='imageuploadsession',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True),
        ),
        migrations.AddField(
            model_name='imageuploadsession',
            name='last_retry_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last retry attempt', null=True),
        ),
        migrations.AddField(
            model_name='imageuploadsession',
            name='local_file_path',
            field=models.CharField(blank=True, help_text='Local file path where image is stored temporarily', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='imageuploadsession',
            name='local_file_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, help_text='UUID for local file identification', unique=True),
        ),
        migrations.AddField(
            model_name='imageuploadsession',
            name='max_retries',
            field=models.PositiveIntegerField(default=5, help_text='Maximum number of retry attempts'),
        ),
        migrations.AddField(
            model_name='imageuploadsession',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional metadata about the image'),
        ),
        migrations.AddField(
            model_name='imageuploadsession',
            name='metadata_uploaded',
            field=models.BooleanField(default=False, help_text='Whether metadata has been uploaded to server'),
        ),
        migrations.AddField(
            model_name='imageuploadsession',
            name='metadata_uploaded_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when metadata was uploaded', null=True),
        ),
        migrations.AddField(
            model_name='imageuploadsession',
            name='retry_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of retry attempts'),
        ),
        migrations.AddField(
            model_name='imageuploadsession',
            name='server_ack_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when server acknowledgment was received', null=True),
        ),
        migrations.AddField(
            model_name='imageuploadsession',
            name='server_ack_received',
            field=models.BooleanField(default=False, help_text='Whether server has acknowledged successful upload'),
        ),
        migrations.AddField(
            model_name='imageuploadsession',
            name='server_image_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID of the image record on the server after successful upload', null=True),
        ),
        migrations.AddField(
            model_name='imageuploadsession',
            name='session_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Unique session identifier for this upload', unique=True),
        ),
        migrations.AddField(
            model_name='imageuploadsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When the upload session was last updated'),
        ),
        migrations.AddField(
            model_name='imageuploadsession',
            name='upload_progress_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Upload progress percentage (0-100)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='imageuploadsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the upload session was created'),
        ),
        migrations.AlterField(
            model_name='imageuploadsession',
            name='created_by',
            field=models.ForeignKey(help_text='User who initiated the upload', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_upload_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='imageuploadsession',
            name='radiology_order',
            field=models.ForeignKey(help_text='Radiology order this image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='image_upload_sessions', to='radiology.radiologyrequest'),
        ),
        migrations.AlterField(
            model_name='imageuploadsession',
            name='status',
            field=models.CharField(choices=[('QUEUED', 'Queued'), ('METADATA_UPLOADING', 'Metadata Uploading'), ('METADATA_UPLOADED', 'Metadata Uploaded'), ('BINARY_UPLOADING', 'Binary Uploading'), ('SYNCED', 'Synced'), ('ACK_RECEIVED', 'Acknowledged'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='QUEUED', help_text='Current upload status', max_length=50),
        ),
        migrations.AddIndex(
            model_name='imageuploadsession',
            index=models.Index(fields=['session_id'], name='image_uploa_session_971ae6_idx'),
        ),
        migrations.AddIndex(
            model_name='imageuploadsession',
            index=models.Index(fields=['local_file_uuid'], name='image_uploa_local_f_54801b_idx'),
        ),
        migrations.AddIndex(
            model_name='imageuploadsession',
            index=models.Index(fields=['status'], name='image_uploa_status_51a70f_idx'),
        ),
        migrations.AddIndex(
            model_name='imageuploadsession',
            index=models.Index(fields=['created_at'], name='image_uploa_created_55ee09_idx'),
        ),
        migrations.DeleteModel(
            name='ImageUploadItem',
        ),
    ]
