# Generated by Django 6.0 on 2026-06-02 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radiology', '0013_radiologystudytype_organization'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='radiologystudytype',
            new_name='radiology_s_organiz_9a708b_idx',
            old_name='rad_study_type_org_idx',
        ),
    ]
