# Generated by Django 6.0 on 2026-07-01 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radiology', '0015_radiologystudy_radiology_request'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='radiologystudy',
            name='radiology_s_radiolo_idx',
        ),
    ]
