# Generated by Django 6.0 on 2025-12-24 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0002_initial'),
        ('visits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DischargeSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chief_complaint', models.TextField(help_text='Chief complaint at admission')),
                ('admission_date', models.DateTimeField(help_text='Date and time of admission')),
                ('discharge_date', models.DateTimeField(help_text='Date and time of discharge')),
                ('diagnosis', models.TextField(help_text='Primary and secondary diagnoses')),
                ('procedures_performed', models.TextField(blank=True, help_text='Procedures performed during visit')),
                ('treatment_summary', models.TextField(help_text='Summary of treatment provided')),
                ('medications_on_discharge', models.TextField(blank=True, help_text='Medications prescribed at discharge')),
                ('follow_up_instructions', models.TextField(help_text='Follow-up care instructions')),
                ('condition_at_discharge', models.CharField(choices=[('STABLE', 'Stable'), ('IMPROVED', 'Improved'), ('UNCHANGED', 'Unchanged'), ('DETERIORATED', 'Deteriorated'), ('CRITICAL', 'Critical')], default='STABLE', help_text='Patient condition at discharge', max_length=50)),
                ('discharge_disposition', models.CharField(choices=[('HOME', 'Home'), ('TRANSFER', 'Transfer to Another Facility'), ('AMA', 'Against Medical Advice'), ('EXPIRED', 'Expired'), ('OTHER', 'Other')], default='HOME', help_text='Discharge disposition', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the discharge summary was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the discharge summary was last updated')),
                ('consultation', models.ForeignKey(help_text='Consultation for this visit', on_delete=django.db.models.deletion.PROTECT, related_name='discharge_summaries', to='consultations.consultation')),
                ('created_by', models.ForeignKey(help_text='Doctor who created the discharge summary', on_delete=django.db.models.deletion.PROTECT, related_name='discharge_summaries_created', to=settings.AUTH_USER_MODEL)),
                ('visit', models.OneToOneField(help_text='Visit this discharge summary belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='discharge_summary', to='visits.visit')),
            ],
            options={
                'verbose_name': 'Discharge Summary',
                'verbose_name_plural': 'Discharge Summaries',
                'db_table': 'discharge_summaries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['visit'], name='discharge_s_visit_i_acc812_idx'), models.Index(fields=['consultation'], name='discharge_s_consult_83283b_idx'), models.Index(fields=['created_at'], name='discharge_s_created_2cdb77_idx')],
            },
        ),
    ]
