# Generated by Django 5.2.7 on 2026-01-09 18:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discharges', '0001_initial'),
        ('visits', '0005_migrate_old_payment_statuses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.CharField(help_text="Bed number or identifier (e.g., 'A1', 'B5', 'ICU-1')", max_length=50)),
                ('bed_type', models.CharField(choices=[('STANDARD', 'Standard'), ('PRIVATE', 'Private'), ('SEMI_PRIVATE', 'Semi-Private'), ('ICU', 'ICU'), ('ISOLATION', 'Isolation'), ('MATERNITY', 'Maternity')], default='STANDARD', help_text='Type of bed', max_length=50)),
                ('is_available', models.BooleanField(default=True, help_text='Whether this bed is currently available')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this bed is active (not decommissioned)')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this bed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bed',
                'verbose_name_plural': 'Beds',
                'db_table': 'beds',
                'ordering': ['ward', 'bed_number'],
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Ward name (e.g., 'General Ward', 'ICU', 'Maternity')", max_length=255, unique=True)),
                ('code', models.CharField(help_text="Ward code (e.g., 'GW', 'ICU', 'MAT')", max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the ward')),
                ('capacity', models.IntegerField(default=0, help_text='Total number of beds in this ward')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this ward is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ward',
                'verbose_name_plural': 'Wards',
                'db_table': 'wards',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_type', models.CharField(choices=[('EMERGENCY', 'Emergency'), ('ELECTIVE', 'Elective'), ('OBSERVATION', 'Observation'), ('DAY_CARE', 'Day Care')], default='ELECTIVE', help_text='Type of admission', max_length=50)),
                ('admission_source', models.CharField(choices=[('OUTPATIENT', 'Outpatient Department'), ('EMERGENCY', 'Emergency Department'), ('REFERRAL', 'Referred from Another Facility'), ('TRANSFER', 'Transfer from Another Ward'), ('DIRECT', 'Direct Admission')], default='OUTPATIENT', help_text='Source of admission', max_length=50)),
                ('admission_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time of admission')),
                ('admission_status', models.CharField(choices=[('ADMITTED', 'Admitted'), ('DISCHARGED', 'Discharged'), ('TRANSFERRED', 'Transferred'), ('ABSENT', 'Absent Without Leave')], default='ADMITTED', help_text='Current admission status', max_length=50)),
                ('discharge_date', models.DateTimeField(blank=True, help_text='Date and time of discharge (set when discharged)', null=True)),
                ('chief_complaint', models.TextField(help_text='Chief complaint at admission')),
                ('admission_notes', models.TextField(blank=True, help_text='Additional notes about the admission')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admitting_doctor', models.ForeignKey(help_text='Doctor who admitted the patient', on_delete=django.db.models.deletion.PROTECT, related_name='admissions_created', to=settings.AUTH_USER_MODEL)),
                ('discharge_summary', models.OneToOneField(blank=True, help_text='Discharge summary linked to this admission', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_admission', to='discharges.dischargesummary')),
                ('transferred_from', models.ForeignKey(blank=True, help_text='Previous admission if transferred from another ward/bed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_to', to='discharges.admission')),
                ('visit', models.OneToOneField(help_text='Visit this admission belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='admission', to='visits.visit')),
                ('bed', models.ForeignKey(help_text='Bed patient is assigned to', on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='discharges.bed')),
                ('ward', models.ForeignKey(help_text='Ward patient is admitted to', on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='discharges.ward')),
            ],
            options={
                'verbose_name': 'Admission',
                'verbose_name_plural': 'Admissions',
                'db_table': 'admissions',
                'ordering': ['-admission_date'],
            },
        ),
        migrations.AddField(
            model_name='dischargesummary',
            name='admission',
            field=models.OneToOneField(blank=True, help_text='Admission record linked to this discharge (if patient was admitted)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_discharge_summary', to='discharges.admission'),
        ),
        migrations.AddField(
            model_name='bed',
            name='ward',
            field=models.ForeignKey(help_text='Ward this bed belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='discharges.ward'),
        ),
        migrations.AddIndex(
            model_name='bed',
            index=models.Index(fields=['ward', 'is_available'], name='beds_ward_id_d76208_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bed',
            unique_together={('ward', 'bed_number')},
        ),
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['visit'], name='admissions_visit_i_8372e3_idx'),
        ),
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['ward', 'admission_status'], name='admissions_ward_id_ea37d9_idx'),
        ),
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['bed', 'admission_status'], name='admissions_bed_id_3b8101_idx'),
        ),
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['admission_status'], name='admissions_admissi_7cade7_idx'),
        ),
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['admission_date'], name='admissions_admissi_aeb84d_idx'),
        ),
    ]
