# Generated by Django 5.2.7 on 2026-06-29 20:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('OTP_REQUESTED', 'OTP Requested'), ('OTP_SENT', 'OTP Sent'), ('OTP_VERIFIED', 'OTP Verified'), ('OTP_FAILED', 'OTP Verification Failed'), ('LOGIN_SUCCESS', 'Login Success'), ('LOGIN_FAILED', 'Login Failed'), ('LOGOUT', 'Logout'), ('TOKEN_REFRESHED', 'Token Refreshed'), ('ACCOUNT_LOCKED', 'Account Locked'), ('ACCOUNT_UNLOCKED', 'Account Unlocked'), ('BIOMETRIC_REGISTERED', 'Biometric Registered'), ('BIOMETRIC_LOGIN_SUCCESS', 'Biometric Login Success'), ('BIOMETRIC_LOGIN_FAILED', 'Biometric Login Failed')], help_text='Action that was performed', max_length=50)),
                ('identifier', models.CharField(blank=True, help_text='Email or phone used for login attempt', max_length=255)),
                ('success', models.BooleanField(default=True, help_text='Whether action was successful')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of request', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string')),
                ('device_type', models.CharField(blank=True, choices=[('web', 'Web'), ('ios', 'iOS'), ('android', 'Android'), ('unknown', 'Unknown')], help_text='Device type', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When action occurred')),
                ('user', models.ForeignKey(blank=True, help_text='User (null if login failed before user identified)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Login Audit Log',
                'verbose_name_plural': 'Login Audit Logs',
                'db_table': 'login_audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='login_audit_user_id_135fce_idx'), models.Index(fields=['action'], name='login_audit_action_d44610_idx'), models.Index(fields=['ip_address'], name='login_audit_ip_addr_75d2a6_idx'), models.Index(fields=['-timestamp'], name='login_audit_timesta_1cd250_idx')],
            },
        ),
        migrations.CreateModel(
            name='LoginOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(help_text='6-digit OTP code', max_length=6, validators=[django.core.validators.RegexValidator('^\\d{6}$', 'OTP must be 6 digits')])),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp')], help_text='Channel OTP was sent through', max_length=20)),
                ('recipient', models.CharField(help_text='Email or phone number OTP was sent to', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When OTP was generated')),
                ('expires_at', models.DateTimeField(help_text='When OTP expires (5 minutes from creation)')),
                ('is_used', models.BooleanField(default=False, help_text='Whether OTP has been used')),
                ('used_at', models.DateTimeField(blank=True, help_text='When OTP was used', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address that requested OTP', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string')),
                ('user', models.ForeignKey(help_text='User this OTP is for', on_delete=django.db.models.deletion.CASCADE, related_name='login_otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Login OTP',
                'verbose_name_plural': 'Login OTPs',
                'db_table': 'login_otps',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='login_otps_user_id_c07118_idx'), models.Index(fields=['otp_code'], name='login_otps_otp_cod_cf405f_idx'), models.Index(fields=['is_used'], name='login_otps_is_used_846b06_idx'), models.Index(fields=['expires_at'], name='login_otps_expires_373f3e_idx')],
            },
        ),
    ]
