# Generated by Django 6.0 on 2025-12-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=10)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('BANK_TRANSFER', 'Bank Transfer'), ('MOBILE_MONEY', 'Mobile Money'), ('INSURANCE', 'Insurance')], help_text='Method of payment', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CLEARED', 'Cleared'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', help_text='Payment status', max_length=20)),
                ('transaction_reference', models.CharField(blank=True, help_text='Transaction reference number', max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Payment notes or remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When payment was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When payment was last updated')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
