# Generated by Django 6.0 on 2025-12-22 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('visits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='processed_by',
            field=models.ForeignKey(help_text='Receptionist who processed this payment. PROTECT prevents deletion.', on_delete=django.db.models.deletion.PROTECT, related_name='payments_processed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='visit',
            field=models.ForeignKey(help_text='Visit this payment belongs to. Payment is visit-scoped.', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='visits.visit'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['visit'], name='payments_visit_i_e68895_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='payments_status_d621e5_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_method'], name='payments_payment_ee488d_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['created_at'], name='payments_created_e3a130_idx'),
        ),
    ]
