# Generated by Django 5.2.7 on 2025-12-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('BANK_TRANSFER', 'Bank Transfer'), ('MOBILE_MONEY', 'Mobile Money'), ('INSURANCE', 'Insurance'), ('WALLET', 'Wallet'), ('PAYSTACK', 'Paystack')], help_text='Method of payment', max_length=20),
        ),
    ]
