# Generated by Django 5.2.7 on 2025-12-31 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_add_paystack_payment_method'),
        ('visits', '0002_add_visit_type_chief_complaint_appointment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HMOProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the HMO/Insurance provider', max_length=255, unique=True)),
                ('code', models.CharField(blank=True, help_text='Provider code/identifier', max_length=50, null=True, unique=True)),
                ('contact_person', models.CharField(blank=True, help_text='Contact person name', max_length=255)),
                ('contact_phone', models.CharField(blank=True, help_text='Contact phone number', max_length=50)),
                ('contact_email', models.EmailField(blank=True, help_text='Contact email address', max_length=254)),
                ('address', models.TextField(blank=True, help_text='Provider address')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the provider is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='Receptionist who created this provider entry', on_delete=django.db.models.deletion.PROTECT, related_name='hmo_providers_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'HMO Provider',
                'verbose_name_plural': 'HMO Providers',
                'db_table': 'hmo_providers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VisitInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(help_text="Patient's insurance policy number", max_length=100)),
                ('coverage_type', models.CharField(choices=[('FULL', 'Full Coverage'), ('PARTIAL', 'Partial Coverage')], default='FULL', help_text='Type of coverage: FULL or PARTIAL', max_length=20)),
                ('coverage_percentage', models.DecimalField(decimal_places=2, default=100.0, help_text='Coverage percentage (0-100). For FULL coverage, this is 100.', max_digits=5)),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', help_text='Insurance approval status', max_length=20)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount approved by insurance (if approved)', max_digits=10, null=True)),
                ('approval_reference', models.CharField(blank=True, help_text='Insurance approval reference number', max_length=255)),
                ('approval_date', models.DateTimeField(blank=True, help_text='Date of insurance approval', null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection (if rejected)')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about insurance coverage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='Receptionist who created this insurance record', on_delete=django.db.models.deletion.PROTECT, related_name='visit_insurances_created', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(help_text='HMO/Insurance provider', on_delete=django.db.models.deletion.PROTECT, related_name='visit_insurances', to='billing.hmoprovider')),
                ('visit', models.OneToOneField(help_text='Visit this insurance record belongs to. MUST be visit-scoped.', on_delete=django.db.models.deletion.CASCADE, related_name='insurance', to='visits.visit')),
            ],
            options={
                'verbose_name': 'Visit Insurance',
                'verbose_name_plural': 'Visit Insurances',
                'db_table': 'visit_insurances',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='hmoprovider',
            index=models.Index(fields=['name'], name='hmo_provide_name_ab3ecc_idx'),
        ),
        migrations.AddIndex(
            model_name='hmoprovider',
            index=models.Index(fields=['code'], name='hmo_provide_code_101043_idx'),
        ),
        migrations.AddIndex(
            model_name='hmoprovider',
            index=models.Index(fields=['is_active'], name='hmo_provide_is_acti_b32f30_idx'),
        ),
        migrations.AddIndex(
            model_name='visitinsurance',
            index=models.Index(fields=['visit'], name='visit_insur_visit_i_880919_idx'),
        ),
        migrations.AddIndex(
            model_name='visitinsurance',
            index=models.Index(fields=['provider'], name='visit_insur_provide_bb5b8f_idx'),
        ),
        migrations.AddIndex(
            model_name='visitinsurance',
            index=models.Index(fields=['approval_status'], name='visit_insur_approva_91ae3c_idx'),
        ),
        migrations.AddIndex(
            model_name='visitinsurance',
            index=models.Index(fields=['coverage_type'], name='visit_insur_coverag_2523d6_idx'),
        ),
    ]
