# Generated by Django 5.2.7 on 2025-12-31 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_hmoprovider_visitinsurance_and_more'),
        ('consultations', '0002_initial'),
        ('laboratory', '0003_labtestcatalog'),
        ('pharmacy', '0005_drug_cost_price_drug_sales_price'),
        ('radiology', '0004_alter_radiologyrequest_study_type'),
        ('visits', '0002_add_visit_type_chief_complaint_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partial'), ('CLEARED', 'Cleared'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', help_text='Payment status', max_length=20),
        ),
        migrations.CreateModel(
            name='VisitCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('CONSULTATION', 'Consultation'), ('LAB', 'Lab Order'), ('RADIOLOGY', 'Radiology Order'), ('DRUG', 'Drug Prescription'), ('PROCEDURE', 'Injection / Dressing'), ('MISC', 'Misc Services')], help_text='Charge category (system-determined from clinical action)', max_length=20)),
                ('description', models.CharField(help_text="Description of the charge (e.g., 'Consultation Fee', 'Lab Test: CBC')", max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Charge amount', max_digits=10)),
                ('created_by_system', models.BooleanField(default=True, help_text='Always True - charges are system-generated, not manually created')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When charge was created (system-generated)')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When charge was last updated')),
                ('consultation', models.ForeignKey(blank=True, help_text='Related consultation (if charge is CONSULTATION)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges', to='consultations.consultation')),
                ('lab_order', models.ForeignKey(blank=True, help_text='Related lab order (if charge is LAB)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges', to='laboratory.laborder')),
                ('prescription', models.ForeignKey(blank=True, help_text='Related prescription (if charge is DRUG)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges', to='pharmacy.prescription')),
                ('radiology_order', models.ForeignKey(blank=True, help_text='Related radiology order (if charge is RADIOLOGY)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges', to='radiology.radiologyorder')),
                ('visit', models.ForeignKey(help_text='Visit this charge belongs to. All charges are visit-scoped.', on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='visits.visit')),
            ],
            options={
                'verbose_name': 'Visit Charge',
                'verbose_name_plural': 'Visit Charges',
                'db_table': 'visit_charges',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['visit'], name='visit_charg_visit_i_6f4d9f_idx'), models.Index(fields=['category'], name='visit_charg_categor_56813c_idx'), models.Index(fields=['created_at'], name='visit_charg_created_3200a2_idx')],
            },
        ),
    ]
