# Generated by Django 5.2.7 on 2025-12-31 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_alter_payment_status_visitcharge'),
        ('visits', '0002_add_visit_type_chief_complaint_appointment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paystack_reference', models.CharField(db_index=True, help_text='Paystack transaction reference (unique identifier)', max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount (in NGN)', max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('INITIALIZED', 'Initialized'), ('VERIFIED', 'Verified'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Payment intent status', max_length=20)),
                ('paystack_authorization_url', models.URLField(blank=True, help_text='Paystack authorization URL (from initialization)', null=True)),
                ('paystack_access_code', models.CharField(blank=True, help_text='Paystack access code (from initialization)', max_length=255, null=True)),
                ('paystack_transaction_id', models.CharField(blank=True, help_text='Paystack transaction ID (from verification)', max_length=255, null=True)),
                ('paystack_customer_email', models.EmailField(blank=True, help_text='Customer email from Paystack (not PHI - generic payment email)', max_length=254, null=True)),
                ('verified_at', models.DateTimeField(blank=True, help_text='When payment was verified (server-side)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When payment intent was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When payment intent was last updated')),
                ('created_by', models.ForeignKey(help_text='Receptionist who created this payment intent', on_delete=django.db.models.deletion.PROTECT, related_name='payment_intents_created', to=settings.AUTH_USER_MODEL)),
                ('payment', models.OneToOneField(blank=True, help_text='Payment record created after verification (immutable once set)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_intent', to='billing.payment')),
                ('visit', models.ForeignKey(help_text='Visit this payment intent belongs to. PaymentIntent is visit-scoped.', on_delete=django.db.models.deletion.CASCADE, related_name='payment_intents', to='visits.visit')),
            ],
            options={
                'verbose_name': 'Payment Intent',
                'verbose_name_plural': 'Payment Intents',
                'db_table': 'payment_intents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['visit'], name='payment_int_visit_i_439695_idx'), models.Index(fields=['paystack_reference'], name='payment_int_paystac_bd7c0d_idx'), models.Index(fields=['status'], name='payment_int_status_0f02ee_idx'), models.Index(fields=['created_at'], name='payment_int_created_25a39a_idx')],
            },
        ),
    ]
