# Generated by Django 5.2.7 on 2026-01-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_paymentintent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('POS', 'POS (Point of Sale)'), ('TRANSFER', 'Bank Transfer'), ('PAYSTACK', 'Paystack'), ('WALLET', 'Wallet'), ('INSURANCE', 'Insurance/HMO')], help_text='Method of payment', max_length=20),
        ),
    ]
