# Generated by Django 5.2.7 on 2026-01-02 16:23

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_update_payment_status_flow'),
        ('patients', '0006_add_emergency_contact_fields'),
        ('visits', '0003_update_payment_status_flow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_insurance_backed', models.BooleanField(default=False, help_text='Whether this bill is backed by insurance. Insurance bills cannot accept Paystack/Cash.')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total bill amount (sum of all bill items)', max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount paid (sum of all payments)', max_digits=10)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Outstanding balance (total_amount - amount_paid)', max_digits=10)),
                ('status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('INSURANCE_PENDING', 'Insurance Pending'), ('INSURANCE_CLAIMED', 'Insurance Claimed'), ('SETTLED', 'Settled')], default='UNPAID', help_text='Bill payment status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When bill was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When bill was last updated')),
                ('visit', models.OneToOneField(help_text='Visit this bill belongs to. One bill per visit.', on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='visits.visit')),
            ],
            options={
                'verbose_name': 'Bill',
                'verbose_name_plural': 'Bills',
                'db_table': 'bills',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BillPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=10)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('POS', 'POS (Point of Sale)'), ('TRANSFER', 'Bank Transfer'), ('PAYSTACK', 'Paystack'), ('WALLET', 'Wallet'), ('INSURANCE', 'Insurance/HMO')], help_text='Method of payment', max_length=20)),
                ('transaction_reference', models.CharField(blank=True, help_text='Transaction reference number', max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Payment notes or remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When payment was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When payment was last updated')),
                ('bill', models.ForeignKey(help_text='Bill this payment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.bill')),
                ('processed_by', models.ForeignKey(help_text='Receptionist who processed this payment', on_delete=django.db.models.deletion.PROTECT, related_name='bill_payments_processed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bill_payments',
            },
        ),
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(help_text='Insurance policy number', max_length=255)),
                ('coverage_type', models.CharField(choices=[('FULL', 'Full Coverage'), ('PARTIAL', 'Partial Coverage')], default='FULL', help_text='Type of coverage', max_length=50)),
                ('coverage_percentage', models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Coverage percentage (0-100)', max_digits=5)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the policy is currently active')),
                ('valid_from', models.DateField(help_text='Policy validity start date')),
                ('valid_to', models.DateField(blank=True, help_text='Policy validity end date (if applicable)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When policy was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When policy was last updated')),
                ('patient', models.ForeignKey(help_text='Patient this policy belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='insurance_policies', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Insurance Policy',
                'verbose_name_plural': 'Insurance Policies',
                'db_table': 'insurance_policies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='bill',
            name='insurance_policy',
            field=models.ForeignKey(blank=True, help_text='Insurance policy for this bill (if insurance-backed)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='billing.insurancepolicy'),
        ),
        migrations.CreateModel(
            name='InsuranceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the insurance provider', max_length=255, unique=True)),
                ('code', models.CharField(blank=True, help_text='Provider code/identifier', max_length=50, null=True, unique=True)),
                ('contact_person', models.CharField(blank=True, help_text='Contact person name', max_length=255)),
                ('contact_phone', models.CharField(blank=True, help_text='Contact phone number', max_length=50)),
                ('contact_email', models.EmailField(blank=True, help_text='Contact email address', max_length=254)),
                ('address', models.TextField(blank=True, help_text='Provider address')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the provider is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When provider was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When provider was last updated')),
            ],
            options={
                'verbose_name': 'Insurance Provider',
                'verbose_name_plural': 'Insurance Providers',
                'db_table': 'insurance_providers',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='insurance_p_name_dda073_idx'), models.Index(fields=['code'], name='insurance_p_code_3033f3_idx'), models.Index(fields=['is_active'], name='insurance_p_is_acti_6ed3fc_idx')],
            },
        ),
        migrations.AddField(
            model_name='insurancepolicy',
            name='provider',
            field=models.ForeignKey(help_text='Insurance provider', on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='billing.insuranceprovider'),
        ),
        migrations.CreateModel(
            name='BillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('CONSULTATION', 'Consultation'), ('LAB', 'Laboratory'), ('RADIOLOGY', 'Radiology'), ('PHARMACY', 'Pharmacy'), ('PROCEDURE', 'Procedure'), ('MISC', 'Miscellaneous')], help_text='Department that provided this service', max_length=50)),
                ('service_name', models.CharField(help_text='Name of the service/item', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Item amount', max_digits=10)),
                ('status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid'), ('INSURANCE', 'Insurance')], default='UNPAID', help_text='Item payment status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When item was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When item was last updated')),
                ('bill', models.ForeignKey(help_text='Bill this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.bill')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_items_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bill Item',
                'verbose_name_plural': 'Bill Items',
                'db_table': 'bill_items',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['bill'], name='bill_items_bill_id_2050b1_idx'), models.Index(fields=['department'], name='bill_items_departm_3eeca8_idx'), models.Index(fields=['status'], name='bill_items_status_d9c072_idx'), models.Index(fields=['created_at'], name='bill_items_created_0aed48_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['visit'], name='bills_visit_i_a04b2c_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['status'], name='bills_status_d22f38_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['is_insurance_backed'], name='bills_is_insu_a70a02_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['created_at'], name='bills_created_15ebce_idx'),
        ),
        migrations.AddIndex(
            model_name='insurancepolicy',
            index=models.Index(fields=['patient'], name='insurance_p_patient_d2a95b_idx'),
        ),
        migrations.AddIndex(
            model_name='insurancepolicy',
            index=models.Index(fields=['provider'], name='insurance_p_provide_b9f121_idx'),
        ),
        migrations.AddIndex(
            model_name='insurancepolicy',
            index=models.Index(fields=['policy_number'], name='insurance_p_policy__67856c_idx'),
        ),
        migrations.AddIndex(
            model_name='insurancepolicy',
            index=models.Index(fields=['is_active'], name='insurance_p_is_acti_de1bda_idx'),
        ),
    ]
