# Generated by Django 5.2.7 on 2026-01-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_add_bill_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabServicePriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_code', models.CharField(db_index=True, help_text='Unique service code/identifier', max_length=100, unique=True)),
                ('service_name', models.CharField(help_text='Name of the service', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Service price', max_digits=10)),
                ('description', models.TextField(blank=True, help_text='Service description')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the service is currently available')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When service was added to price list')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When service was last updated')),
            ],
            options={
                'verbose_name': 'Lab Service Price',
                'verbose_name_plural': 'Lab Service Prices',
                'db_table': 'lab_service_prices',
                'indexes': [models.Index(fields=['service_code'], name='lab_service_service_97c89c_idx'), models.Index(fields=['is_active'], name='lab_service_is_acti_a268d0_idx')],
            },
        ),
        migrations.CreateModel(
            name='PharmacyServicePriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_code', models.CharField(db_index=True, help_text='Unique service code/identifier', max_length=100, unique=True)),
                ('service_name', models.CharField(help_text='Name of the service', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Service price', max_digits=10)),
                ('description', models.TextField(blank=True, help_text='Service description')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the service is currently available')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When service was added to price list')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When service was last updated')),
            ],
            options={
                'verbose_name': 'Pharmacy Service Price',
                'verbose_name_plural': 'Pharmacy Service Prices',
                'db_table': 'pharmacy_service_prices',
                'indexes': [models.Index(fields=['service_code'], name='pharmacy_se_service_bffeac_idx'), models.Index(fields=['is_active'], name='pharmacy_se_is_acti_c8fa16_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProcedureServicePriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_code', models.CharField(db_index=True, help_text='Unique service code/identifier', max_length=100, unique=True)),
                ('service_name', models.CharField(help_text='Name of the service', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Service price', max_digits=10)),
                ('description', models.TextField(blank=True, help_text='Service description')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the service is currently available')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When service was added to price list')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When service was last updated')),
            ],
            options={
                'verbose_name': 'Procedure Service Price',
                'verbose_name_plural': 'Procedure Service Prices',
                'db_table': 'procedure_service_prices',
                'indexes': [models.Index(fields=['service_code'], name='procedure_s_service_3fc18a_idx'), models.Index(fields=['is_active'], name='procedure_s_is_acti_3fcb04_idx')],
            },
        ),
        migrations.CreateModel(
            name='RadiologyServicePriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_code', models.CharField(db_index=True, help_text='Unique service code/identifier', max_length=100, unique=True)),
                ('service_name', models.CharField(help_text='Name of the service', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Service price', max_digits=10)),
                ('description', models.TextField(blank=True, help_text='Service description')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the service is currently available')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When service was added to price list')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When service was last updated')),
            ],
            options={
                'verbose_name': 'Radiology Service Price',
                'verbose_name_plural': 'Radiology Service Prices',
                'db_table': 'radiology_service_prices',
                'indexes': [models.Index(fields=['service_code'], name='radiology_s_service_097792_idx'), models.Index(fields=['is_active'], name='radiology_s_is_acti_317a69_idx')],
            },
        ),
    ]
