# Generated by Django 5.2.7 on 2026-01-03 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_add_price_lists'),
        ('visits', '0005_migrate_old_payment_statuses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this bill', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['created_by'], name='bills_created_2a9e2c_idx'),
        ),
        migrations.AddIndex(
            model_name='billitem',
            index=models.Index(fields=['created_by'], name='bill_items_created_4f4756_idx'),
        ),
        migrations.AddConstraint(
            model_name='bill',
            constraint=models.CheckConstraint(condition=models.Q(('visit__isnull', False)), name='bill_requires_visit'),
        ),
        migrations.AddConstraint(
            model_name='billitem',
            constraint=models.CheckConstraint(condition=models.Q(('bill__isnull', False)), name='bill_item_requires_bill'),
        ),
    ]
