# Generated by Django 5.2.7 on 2026-01-09 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_bill_created_by_bill_bills_created_2a9e2c_idx_and_more'),
        ('visits', '0005_migrate_old_payment_statuses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('RECEIPT', 'Receipt'), ('INVOICE', 'Invoice'), ('STATEMENT', 'Billing Statement')], help_text='Type of document', max_length=20, unique=True)),
                ('current_number', models.IntegerField(default=0, help_text='Current sequence number')),
                ('prefix', models.CharField(help_text='Prefix for document number (e.g., REC, INV)', max_length=10)),
                ('year', models.IntegerField(help_text='Year for this sequence (allows yearly reset)')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
            ],
            options={
                'db_table': 'document_number_sequences',
                'unique_together': {('document_type', 'year')},
            },
        ),
        migrations.CreateModel(
            name='InvoiceReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('RECEIPT', 'Receipt'), ('INVOICE', 'Invoice'), ('STATEMENT', 'Billing Statement')], help_text='Type of document (RECEIPT, INVOICE, STATEMENT)', max_length=20)),
                ('document_number', models.CharField(help_text='Sequential document number (e.g., REC-0001, INV-0001)', max_length=50, unique=True)),
                ('document_data', models.JSONField(help_text='Complete document data (charges, payments, etc.)')),
                ('pdf_file', models.FileField(blank=True, help_text='Generated PDF file', null=True, upload_to='invoices_receipts/%Y/%m/')),
                ('qr_code_data', models.TextField(blank=True, help_text='QR code data for document verification')),
                ('generated_at', models.DateTimeField(auto_now_add=True, help_text='When this document was generated')),
                ('emailed_to', models.EmailField(blank=True, help_text='Email address document was sent to', max_length=254, null=True)),
                ('sms_sent_to', models.CharField(blank=True, help_text='Phone number SMS was sent to', max_length=20, null=True)),
                ('emailed_at', models.DateTimeField(blank=True, help_text='When document was emailed', null=True)),
                ('sms_sent_at', models.DateTimeField(blank=True, help_text='When SMS was sent', null=True)),
                ('generated_by', models.ForeignKey(help_text='User who generated this document', on_delete=django.db.models.deletion.PROTECT, related_name='generated_documents', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(blank=True, help_text='Payment this receipt is for (if applicable)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_receipts', to='billing.payment')),
                ('visit', models.ForeignKey(help_text='Visit this document belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='invoice_receipts', to='visits.visit')),
            ],
            options={
                'db_table': 'invoice_receipts',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['document_type', 'document_number'], name='invoice_rec_documen_4040b6_idx'), models.Index(fields=['visit', 'document_type'], name='invoice_rec_visit_i_985d0a_idx'), models.Index(fields=['generated_at'], name='invoice_rec_generat_d6a2fa_idx')],
            },
        ),
    ]
