# Generated by Django 5.2.7 on 2026-01-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_documentnumbersequence_invoicereceipt'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('CONSULTATION', 'Consultation'), ('LAB', 'Laboratory'), ('PHARMACY', 'Pharmacy'), ('RADIOLOGY', 'Radiology'), ('PROCEDURE', 'Procedure')], db_index=True, help_text='Department that provides this service', max_length=50)),
                ('service_code', models.CharField(db_index=True, help_text="Unique, human-readable service code (e.g., 'CONS-001', 'CBC-001')", max_length=100, unique=True)),
                ('name', models.CharField(help_text="Service name (e.g., 'General Consultation', 'Complete Blood Count')", max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Service price/amount', max_digits=10)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the service')),
                ('category', models.CharField(choices=[('CONSULTATION', 'Consultation'), ('LAB', 'Laboratory Test'), ('DRUG', 'Drug/Medication'), ('PROCEDURE', 'Procedure'), ('RADIOLOGY', 'Radiology Study')], help_text='Service category', max_length=50)),
                ('workflow_type', models.CharField(choices=[('GOPD_CONSULT', 'GOPD Consultation'), ('LAB_ORDER', 'Laboratory Order'), ('DRUG_DISPENSE', 'Drug Dispensing'), ('PROCEDURE', 'Procedure'), ('RADIOLOGY_STUDY', 'Radiology Study'), ('INJECTION', 'Injection'), ('DRESSING', 'Dressing'), ('VACCINATION', 'Vaccination'), ('PHYSIOTHERAPY', 'Physiotherapy'), ('OTHER', 'Other')], help_text='Type of workflow this service triggers', max_length=50)),
                ('requires_visit', models.BooleanField(default=True, help_text='Whether this service requires an active visit')),
                ('requires_consultation', models.BooleanField(default=False, help_text='Whether this service requires a consultation')),
                ('auto_bill', models.BooleanField(default=True, help_text='Whether to automatically create a bill when service is ordered')),
                ('bill_timing', models.CharField(choices=[('BEFORE', 'Before Service'), ('AFTER', 'After Service')], default='AFTER', help_text='When to bill for this service (BEFORE or AFTER service delivery)', max_length=10)),
                ('allowed_roles', models.JSONField(default=list, help_text="List of user roles allowed to order this service (e.g., ['DOCTOR', 'NURSE'])")),
                ('is_active', models.BooleanField(default=True, help_text='Whether this service is currently active/available')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this service was added to catalog')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this service was last updated')),
            ],
            options={
                'verbose_name': 'Service Catalog',
                'verbose_name_plural': 'Service Catalog',
                'db_table': 'service_catalog',
                'ordering': ['department', 'service_code'],
                'indexes': [models.Index(fields=['service_code'], name='service_cat_service_1d5b2a_idx'), models.Index(fields=['department'], name='service_cat_departm_e55195_idx'), models.Index(fields=['department', 'is_active'], name='service_cat_departm_046e53_idx'), models.Index(fields=['workflow_type'], name='service_cat_workflo_dcbc78_idx'), models.Index(fields=['is_active'], name='service_cat_is_acti_40b383_idx')],
            },
        ),
    ]
