# Generated by Django 5.2.7 on 2026-01-10 14:19

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_servicecatalog_auto_assign_doctor'),
        ('consultations', '0004_consultation_status_alter_consultation_created_by_and_more'),
        ('visits', '0005_migrate_old_payment_statuses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_service_code', models.CharField(db_index=True, help_text='Service code at time of billing (snapshot from ServiceCatalog.service_code)', max_length=100)),
                ('source_service_name', models.CharField(help_text='Service name at time of billing (snapshot from ServiceCatalog.name)', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Billing amount (snapshot from ServiceCatalog.amount at time of billing)', max_digits=10)),
                ('bill_status', models.CharField(choices=[('PENDING', 'Pending'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid')], db_index=True, default='PENDING', help_text='Payment status of this billing line item', max_length=20)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount paid against this line item', max_digits=10)),
                ('outstanding_amount', models.DecimalField(decimal_places=2, help_text='Outstanding amount (amount - amount_paid)', max_digits=10)),
                ('payment_method', models.CharField(blank=True, choices=[('CASH', 'Cash'), ('WALLET', 'Wallet'), ('HMO', 'HMO/Insurance'), ('PAYSTACK', 'Paystack')], help_text='Payment method used (if paid)', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this billing line item was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this billing line item was last updated')),
                ('paid_at', models.DateTimeField(blank=True, help_text='When this billing line item was fully paid', null=True)),
                ('consultation', models.ForeignKey(blank=True, help_text='Consultation this billing line item is associated with (optional, for consultation services)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_line_items', to='consultations.consultation')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this billing line item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_line_items_created', to=settings.AUTH_USER_MODEL)),
                ('service_catalog', models.ForeignKey(help_text='ServiceCatalog service that generated this billing line item', on_delete=django.db.models.deletion.CASCADE, related_name='billing_line_items', to='billing.servicecatalog')),
                ('visit', models.ForeignKey(help_text='Visit this billing line item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='billing_line_items', to='visits.visit')),
            ],
            options={
                'verbose_name': 'Billing Line Item',
                'verbose_name_plural': 'Billing Line Items',
                'db_table': 'billing_line_items',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['service_catalog'], name='billing_lin_service_dce314_idx'), models.Index(fields=['visit'], name='billing_lin_visit_i_61db93_idx'), models.Index(fields=['consultation'], name='billing_lin_consult_cfff9a_idx'), models.Index(fields=['source_service_code'], name='billing_lin_source__750a2a_idx'), models.Index(fields=['bill_status'], name='billing_lin_bill_st_0a4966_idx'), models.Index(fields=['created_at'], name='billing_lin_created_7a5c04_idx'), models.Index(fields=['visit', 'bill_status'], name='billing_lin_visit_i_05f0c9_idx'), models.Index(fields=['service_catalog', 'visit'], name='billing_lin_service_c7023f_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('service_catalog__isnull', False), ('visit__isnull', False)), name='billing_line_item_requires_service_and_visit'), models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='billing_line_item_amount_positive'), models.CheckConstraint(condition=models.Q(('outstanding_amount__gte', 0)), name='billing_line_item_outstanding_non_negative'), models.CheckConstraint(condition=models.Q(('amount_paid__lte', models.F('amount'))), name='billing_line_item_paid_not_exceed_amount')],
            },
        ),
    ]
