# Generated by Django 5.2.7 on 2026-01-10 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_billinglineitem_modified_by_and_more'),
        ('visits', '0005_migrate_old_payment_statuses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeakRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('LAB_RESULT', 'Lab Result'), ('RADIOLOGY_REPORT', 'Radiology Report'), ('DRUG_DISPENSE', 'Drug Dispense'), ('PROCEDURE', 'Procedure')], db_index=True, help_text='Type of entity that triggered the leak detection', max_length=50)),
                ('entity_id', models.PositiveIntegerField(db_index=True, help_text='ID of the entity that triggered the leak (LabResult.id, RadiologyRequest.id, etc.)')),
                ('service_code', models.CharField(db_index=True, help_text='Service code from ServiceCatalog (if available)', max_length=100)),
                ('service_name', models.CharField(blank=True, help_text='Service name from ServiceCatalog (if available)', max_length=255)),
                ('estimated_amount', models.DecimalField(decimal_places=2, help_text='Estimated revenue loss (from ServiceCatalog.amount if available)', max_digits=10)),
                ('detected_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the leak was first detected')),
                ('resolved_at', models.DateTimeField(blank=True, db_index=True, help_text='When the leak was resolved (manually)', null=True)),
                ('resolution_notes', models.TextField(blank=True, help_text='Notes about how the leak was resolved')),
                ('detection_context', models.JSONField(blank=True, default=dict, help_text='Additional context about the detection (e.g., why no bill was found)')),
                ('resolved_by', models.ForeignKey(blank=True, help_text='User who resolved the leak', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaks_resolved', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(help_text='Visit where the leak was detected', on_delete=django.db.models.deletion.CASCADE, related_name='leak_records', to='visits.visit')),
            ],
            options={
                'verbose_name': 'Revenue Leak Record',
                'verbose_name_plural': 'Revenue Leak Records',
                'db_table': 'leak_records',
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='leak_record_entity__5aa6c6_idx'), models.Index(fields=['visit'], name='leak_record_visit_i_25ecc6_idx'), models.Index(fields=['detected_at'], name='leak_record_detecte_f8d1f5_idx'), models.Index(fields=['resolved_at'], name='leak_record_resolve_6c644d_idx'), models.Index(fields=['service_code'], name='leak_record_service_38b91f_idx'), models.Index(fields=['entity_type', 'resolved_at'], name='leak_record_entity__415b01_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('resolved_at__isnull', True)), fields=('entity_type', 'entity_id'), name='unique_unresolved_leak_per_entity')],
            },
        ),
    ]
