# Generated by Django 5.2.7 on 2026-01-11 13:08

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_leakrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EndOfDayReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reconciliation_date', models.DateField(db_index=True, help_text='Date of reconciliation (one per day)', unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('FINALIZED', 'Finalized'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', help_text='Reconciliation status', max_length=20)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total revenue for the day', max_digits=12)),
                ('total_cash', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total cash payments', max_digits=12)),
                ('total_wallet', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total wallet payments', max_digits=12)),
                ('total_paystack', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total Paystack payments', max_digits=12)),
                ('total_hmo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total HMO payments', max_digits=12)),
                ('total_insurance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total insurance payments', max_digits=12)),
                ('total_outstanding', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total outstanding balances', max_digits=12)),
                ('outstanding_visits_count', models.PositiveIntegerField(default=0, help_text='Number of visits with outstanding balances')),
                ('revenue_leaks_detected', models.PositiveIntegerField(default=0, help_text='Number of revenue leaks detected')),
                ('revenue_leaks_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount of revenue leaks', max_digits=12)),
                ('total_visits', models.PositiveIntegerField(default=0, help_text='Total number of visits for the day')),
                ('active_visits_closed', models.PositiveIntegerField(default=0, help_text='Number of active visits closed during reconciliation')),
                ('has_mismatches', models.BooleanField(default=False, help_text='Whether there are payment mismatches')),
                ('mismatch_details', models.JSONField(blank=True, default=dict, help_text='Details of payment mismatches')),
                ('prepared_at', models.DateTimeField(auto_now_add=True, help_text='When the reconciliation was prepared')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When the reconciliation was reviewed', null=True)),
                ('finalized_at', models.DateTimeField(blank=True, help_text='When the reconciliation was finalized', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the reconciliation')),
                ('reconciliation_details', models.JSONField(blank=True, default=dict, help_text='Detailed breakdown of reconciliation')),
                ('finalized_by', models.ForeignKey(blank=True, help_text='User who finalized the reconciliation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliations_finalized', to=settings.AUTH_USER_MODEL)),
                ('prepared_by', models.ForeignKey(help_text='User who prepared the reconciliation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliations_prepared', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='User who reviewed the reconciliation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliations_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'End of Day Reconciliation',
                'verbose_name_plural': 'End of Day Reconciliations',
                'db_table': 'end_of_day_reconciliation',
                'ordering': ['-reconciliation_date'],
                'indexes': [models.Index(fields=['reconciliation_date'], name='end_of_day__reconci_d92959_idx'), models.Index(fields=['status'], name='end_of_day__status_d73496_idx'), models.Index(fields=['prepared_at'], name='end_of_day__prepare_20e658_idx')],
            },
        ),
    ]
