# Generated by Django 5.2.7

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        ('billing', '0019_set_restricted_service_flags'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(max_length=100)),
                ('coverage_details', models.JSONField(blank=True, default=dict, help_text='Coverage limits, type, etc.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_policies', to='patients.patient')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claim_policies', to='billing.hmoprovider')),
            ],
            options={
                'verbose_name': 'Claim Policy',
                'verbose_name_plural': 'Claim Policies',
                'db_table': 'claim_policies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services', models.JSONField(default=list, help_text='List of services: consultations, labs, medications, procedures')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('response_payload', models.JSONField(blank=True, default=dict, help_text='Insurer response (stub)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='patients.patient')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='billing.claimpolicy')),
            ],
            options={
                'verbose_name': 'Claim',
                'verbose_name_plural': 'Claims',
                'db_table': 'insurance_claims',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='claimpolicy',
            index=models.Index(fields=['patient'], name='claim_polic_patient_6a8c0d_idx'),
        ),
        migrations.AddIndex(
            model_name='claimpolicy',
            index=models.Index(fields=['provider'], name='claim_polic_provider_b2e8f2_idx'),
        ),
        migrations.AddIndex(
            model_name='claimpolicy',
            index=models.Index(fields=['is_active'], name='claim_polic_is_acti_9c4a1b_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['patient'], name='insurance_c_patient_6a8c0d_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['policy'], name='insurance_c_policy__b2e8f2_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['status'], name='insurance_c_status_9c4a1b_idx'),
        ),
    ]
