# Generated by Django 5.2.7 on 2026-05-09 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0020_claimpolicy_claim'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='claim',
            new_name='insurance_c_patient_374c53_idx',
            old_name='insurance_c_patient_6a8c0d_idx',
        ),
        migrations.RenameIndex(
            model_name='claim',
            new_name='insurance_c_policy__49fbba_idx',
            old_name='insurance_c_policy__b2e8f2_idx',
        ),
        migrations.RenameIndex(
            model_name='claim',
            new_name='insurance_c_status_0f3899_idx',
            old_name='insurance_c_status_9c4a1b_idx',
        ),
        migrations.RenameIndex(
            model_name='claimpolicy',
            new_name='claim_polic_patient_02e31d_idx',
            old_name='claim_polic_patient_6a8c0d_idx',
        ),
        migrations.RenameIndex(
            model_name='claimpolicy',
            new_name='claim_polic_provide_36871e_idx',
            old_name='claim_polic_provider_b2e8f2_idx',
        ),
        migrations.RenameIndex(
            model_name='claimpolicy',
            new_name='claim_polic_is_acti_c497ac_idx',
            old_name='claim_polic_is_acti_9c4a1b_idx',
        ),
        migrations.AlterField(
            model_name='servicecatalog',
            name='workflow_type',
            field=models.CharField(choices=[('GOPD_CONSULT', 'GOPD Consultation'), ('LAB_ORDER', 'Laboratory Order'), ('DRUG_DISPENSE', 'Drug Dispensing'), ('PROCEDURE', 'Procedure'), ('RADIOLOGY_STUDY', 'Radiology Study'), ('IVF', 'IVF'), ('INJECTION', 'Injection'), ('DRESSING', 'Dressing'), ('VACCINATION', 'Vaccination'), ('PHYSIOTHERAPY', 'Physiotherapy'), ('OTHER', 'Other')], help_text='Type of workflow this service triggers', max_length=50),
        ),
    ]
