# Generated by Django 5.2.7 on 2026-06-29 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0024_nhia_tariff'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='nhiatariff',
            new_name='billing_nhi_categor_0c3213_idx',
            old_name='billing_nhi_categor_8f3a21_idx',
        ),
    ]
