# Generated by Django 5.2.7 on 2026-06-29 22:28

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0025_rename_billing_nhi_categor_8f3a21_idx_billing_nhi_categor_0c3213_idx'),
        ('organizations', '0008_alter_saassubscriptionpayment_options'),
        ('visits', '0011_guide_and_sandbox_visit_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='visitinsurance',
            name='billing_scheme',
            field=models.CharField(choices=[('FEE_FOR_SERVICE', 'Fee for Service'), ('CAPITATION', 'Capitation'), ('RETAINER', 'Corporate Retainer')], default='FEE_FOR_SERVICE', help_text='HMO billing scheme: fee-for-service, capitation, or retainer', max_length=20),
        ),
        migrations.AddField(
            model_name='visitinsurance',
            name='employer_name',
            field=models.CharField(blank=True, help_text='Employer or retainer organization name', max_length=255),
        ),
        migrations.AddField(
            model_name='visitinsurance',
            name='pre_auth_decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitinsurance',
            name='pre_auth_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visitinsurance',
            name='pre_auth_number',
            field=models.CharField(blank=True, help_text='HMO pre-authorization reference number', max_length=128),
        ),
        migrations.AddField(
            model_name='visitinsurance',
            name='pre_auth_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitinsurance',
            name='pre_auth_status',
            field=models.CharField(choices=[('NOT_REQUIRED', 'Not Required'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='NOT_REQUIRED', help_text='Pre-authorization status for this visit', max_length=20),
        ),
        migrations.CreateModel(
            name='NHIAClaimSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('VALIDATED', 'Validated'), ('EXPORTED', 'Exported'), ('SUBMITTED', 'Submitted'), ('PAID', 'Paid'), ('DENIED', 'Denied'), ('RESUBMITTED', 'Resubmitted')], default='DRAFT', max_length=20)),
                ('claim_reference', models.CharField(blank=True, db_index=True, max_length=64)),
                ('total_amount_ngn', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('line_count', models.PositiveIntegerField(default=0)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('claim_pack_snapshot', models.JSONField(blank=True, default=dict)),
                ('denial_reason', models.TextField(blank=True)),
                ('nhia_portal_reference', models.CharField(blank=True, max_length=128)),
                ('paid_amount_ngn', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('exported_at', models.DateTimeField(blank=True, null=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nhia_claims_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nhia_claim_submissions', to='organizations.organization')),
                ('resubmission_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resubmissions', to='billing.nhiaclaimsubmission')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nhia_claims_updated', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nhia_claim_submissions', to='visits.visit')),
            ],
            options={
                'db_table': 'nhia_claim_submissions',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['status'], name='nhia_claim__status_7bacc8_idx'), models.Index(fields=['organization', 'status'], name='nhia_claim__organiz_d7124f_idx'), models.Index(fields=['-updated_at'], name='nhia_claim__updated_c2a577_idx')],
            },
        ),
    ]
