# Generated by Django 5.2.7 on 2026-06-29 22:32

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0026_visitinsurance_billing_scheme_and_more'),
        ('visits', '0011_guide_and_sandbox_visit_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('BANK_TRANSFER', 'Bank Transfer'), ('USSD', 'USSD'), ('POS', 'POS'), ('CASH', 'Cash')], max_length=20)),
                ('reference', models.CharField(db_index=True, max_length=128)),
                ('amount_ngn', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('payer_name', models.CharField(blank=True, max_length=255)),
                ('bank_name', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('MATCHED', 'Matched'), ('DISPUTED', 'Disputed')], default='PENDING', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('matched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliations', to='billing.payment')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_reconciliations_recorded', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_reconciliations', to='visits.visit')),
            ],
            options={
                'db_table': 'billing_payment_reconciliation',
                'ordering': ['-created_at'],
            },
        ),
    ]
