# Generated by Django 6.0 on 2025-12-22 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0001_initial'),
        ('visits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='created_by',
            field=models.ForeignKey(help_text='Doctor who documented this consultation.', on_delete=django.db.models.deletion.PROTECT, related_name='consultations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consultation',
            name='visit',
            field=models.OneToOneField(help_text='Visit is the single source of clinical truth. Consultation is strictly visit-scoped.', on_delete=django.db.models.deletion.CASCADE, related_name='consultation', to='visits.visit'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['visit'], name='consultatio_visit_i_df6c84_idx'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['created_by'], name='consultatio_created_50b5dc_idx'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['created_at'], name='consultatio_created_c723b7_idx'),
        ),
    ]
