# Generated by Django 5.2.7 on 2026-01-08 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_type', models.CharField(choices=[('ICD11', 'ICD-11'), ('ICD10', 'ICD-10')], default='ICD11', help_text='Type of diagnosis code', max_length=10)),
                ('code', models.CharField(help_text="Diagnosis code (e.g., 'CA40.Z' for ICD-11)", max_length=20)),
                ('description', models.CharField(help_text='Description of the diagnosis code', max_length=500)),
                ('is_primary', models.BooleanField(default=False, help_text='True if this is the primary diagnosis')),
                ('confidence', models.DecimalField(blank=True, decimal_places=2, help_text='AI confidence score (0-100) if code was AI-generated', max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When code was assigned')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When code was last updated')),
                ('consultation', models.ForeignKey(help_text='Consultation this code belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_codes', to='consultations.consultation')),
                ('created_by', models.ForeignKey(help_text='User who assigned this code', on_delete=django.db.models.deletion.PROTECT, related_name='diagnosis_codes_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Diagnosis Code',
                'verbose_name_plural': 'Diagnosis Codes',
                'db_table': 'diagnosis_codes',
                'ordering': ['-is_primary', 'created_at'],
                'indexes': [models.Index(fields=['consultation'], name='diagnosis_c_consult_2c84dc_idx'), models.Index(fields=['code'], name='diagnosis_c_code_68b8b4_idx'), models.Index(fields=['is_primary'], name='diagnosis_c_is_prim_10e127_idx'), models.Index(fields=['code_type'], name='diagnosis_c_code_ty_37cf37_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('consultation', 'is_primary'), name='unique_primary_diagnosis')],
            },
        ),
    ]
