# Generated by Django 5.2.7 on 2026-01-10 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0003_add_diagnosis_codes'),
        ('visits', '0005_migrate_old_payment_statuses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed')], default='PENDING', help_text='Consultation status. PENDING: awaiting payment/assignment, ACTIVE: in progress, CLOSED: completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Doctor who documented this consultation. Can be auto-assigned from ServiceCatalog.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consultations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['status'], name='consultatio_status_beb187_idx'),
        ),
    ]
