# Generated by Django 5.2.7 on 2026-01-10 15:41

import apps.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0004_consultation_status_alter_consultation_created_by_and_more'),
        ('visits', '0005_migrate_old_payment_statuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='visit',
            field=models.OneToOneField(help_text='Visit is the single source of clinical truth. Consultation is strictly visit-scoped.', on_delete=django.db.models.deletion.CASCADE, related_name='consultation', to='visits.visit', validators=[apps.core.validators.validate_visit_required]),
        ),
    ]
