# Generated by Django 6.0 on 2025-12-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Patient first name (PHI)', max_length=255)),
                ('last_name', models.CharField(help_text='Patient last name (PHI)', max_length=255)),
                ('middle_name', models.CharField(blank=True, help_text='Patient middle name (PHI)', max_length=255)),
                ('date_of_birth', models.DateField(blank=True, help_text='Patient date of birth (PHI)', null=True)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other'), ('PREFER_NOT_TO_SAY', 'Prefer not to say')], help_text='Patient gender', max_length=20)),
                ('phone', models.CharField(blank=True, help_text='Patient phone number (PHI)', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Patient email address (PHI)', max_length=254)),
                ('address', models.TextField(blank=True, help_text='Patient address (PHI)')),
                ('national_id', models.CharField(blank=True, help_text='National ID number (PHI, unique)', max_length=50, null=True, unique=True)),
                ('patient_id', models.CharField(help_text='Internal patient ID (unique identifier)', max_length=50, unique=True)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], help_text='Blood group', max_length=10)),
                ('allergies', models.TextField(blank=True, help_text='Known allergies (PHI)')),
                ('medical_history', models.TextField(blank=True, help_text='Medical history summary (PHI)')),
                ('is_active', models.BooleanField(default=True, help_text='Soft delete flag. False means patient record is archived.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When patient was registered')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When patient record was last updated')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'db_table': 'patients',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient_id'], name='patients_patient_e63b14_idx'), models.Index(fields=['national_id'], name='patients_nationa_c07601_idx'), models.Index(fields=['last_name', 'first_name'], name='patients_last_na_ce6411_idx'), models.Index(fields=['phone'], name='patients_phone_ef6690_idx'), models.Index(fields=['is_active'], name='patients_is_acti_4a96f9_idx')],
            },
        ),
    ]
