# Generated by Django 5.2.7 on 2025-12-23 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='allergies',
            field=models.TextField(blank=True, help_text='Known allergies (PHI)', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], help_text='Blood group', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='medical_history',
            field=models.TextField(blank=True, help_text='Medical history summary (PHI)', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='middle_name',
            field=models.CharField(blank=True, help_text='Patient middle name (PHI)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(help_text='Internal patient ID (unique identifier, auto-generated)', max_length=50, unique=True),
        ),
    ]
