# Generated by Django 6.0 on 2025-12-25 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patient_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Whether the patient account has been verified by a Receptionist. Patients must be verified before accessing the portal.'),
        ),
        migrations.AddField(
            model_name='patient',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when patient account was verified', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='Receptionist who verified this patient account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_patients', to=settings.AUTH_USER_MODEL),
        ),
    ]
