# Generated by Django 5.2.7 on 2026-01-05 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_add_emergency_contact_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='has_retainership',
            field=models.BooleanField(default=False, help_text='Whether patient has an active retainership agreement'),
        ),
        migrations.AddField(
            model_name='patient',
            name='retainership_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Retainership amount paid', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='retainership_end_date',
            field=models.DateField(blank=True, help_text='Retainership end date (if applicable)', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='retainership_start_date',
            field=models.DateField(blank=True, help_text='Retainership start date', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='retainership_type',
            field=models.CharField(blank=True, help_text="Type of retainership (e.g., 'Monthly', 'Quarterly', 'Annual', 'Corporate')", max_length=100, null=True),
        ),
    ]
