# Generated by Django 5.2.7 on 2026-02-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_add_retainership_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='portal_enabled',
            field=models.BooleanField(default=False, help_text='Whether patient portal access is enabled for this patient'),
        ),
    ]
