# Generated by Django 5.2.7 on 2026-05-09 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_national_health_id'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='patient',
            name='patients_nationa_health_idx',
        ),
        migrations.AlterField(
            model_name='patient',
            name='id_verified',
            field=models.BooleanField(default=False, help_text='Whether National Health ID has been verified via external check'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='national_health_id',
            field=models.CharField(blank=True, help_text='National Health ID (e.g. NIN/NHIA Nigeria); unique, nullable', max_length=50, null=True, unique=True),
        ),
    ]
