# Generated by Django 6.0 on 2026-06-02 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_patient_id_unique_per_organization'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='patient',
            name='patients_nationa_health_idx',
        ),
        migrations.RenameIndex(
            model_name='patient',
            new_name='patients_organiz_ceae0f_idx',
            old_name='patients_organiz_idx',
        ),
        migrations.AlterField(
            model_name='patient',
            name='id_verified',
            field=models.BooleanField(default=False, help_text='Whether National Health ID has been verified via external check'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='national_health_id',
            field=models.CharField(blank=True, help_text='National Health ID (e.g. NIN/NHIA Nigeria); unique, nullable', max_length=50, null=True, unique=True),
        ),
    ]
