# Generated by Django 6.0 on 2026-07-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0013_patientallergy'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='patientallergy',
            new_name='patient_all_patient_8c3cd4_idx',
            old_name='patient_all_patient_8a1f2d_idx',
        ),
        migrations.RenameIndex(
            model_name='patientallergy',
            new_name='patient_all_allerge_0a86a6_idx',
            old_name='patient_all_allerge_91c4e2_idx',
        ),
        migrations.AlterField(
            model_name='patientallergy',
            name='allergen',
            field=models.CharField(help_text='Allergen name (e.g. Penicillin)', max_length=255),
        ),
        migrations.AlterField(
            model_name='patientallergy',
            name='reaction',
            field=models.TextField(blank=True, help_text='Reaction description'),
        ),
    ]
