# Generated by Django 5.2.7 on 2026-06-29 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('visits', '0011_guide_and_sandbox_visit_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGuideProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_steps', models.JSONField(blank=True, default=list, help_text='Guide step IDs completed by the user')),
                ('dismissed_hints', models.JSONField(blank=True, default=list, help_text='JIT hint IDs the user dismissed')),
                ('role_launch_completed', models.JSONField(blank=True, default=dict, help_text='Role launch completion, e.g. {"DOCTOR": true}')),
                ('guide_preferences', models.JSONField(blank=True, default=dict, help_text='Guide UI preferences (enabled, reduced motion, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guide_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Guide Progress',
                'verbose_name_plural': 'User Guide Progress',
                'db_table': 'guide_user_progress',
            },
        ),
        migrations.CreateModel(
            name='VisitWorkflowProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pack_id', models.CharField(help_text='Workflow pack identifier (intake, charting, close_visit)', max_length=50)),
                ('completed_steps', models.JSONField(blank=True, default=list)),
                ('skipped_steps', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_updates', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_progress', to='visits.visit')),
            ],
            options={
                'db_table': 'guide_visit_workflow_progress',
                'indexes': [models.Index(fields=['visit', 'pack_id'], name='guide_visit_visit_i_522112_idx')],
                'unique_together': {('visit', 'pack_id')},
            },
        ),
    ]
