# Generated by Django 5.2.7 on 2026-06-29 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0002_guide_event'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='guideevent',
            new_name='guide_event_organiz_c6095c_idx',
            old_name='guide_event_org_created_idx',
        ),
        migrations.RenameIndex(
            model_name='guideevent',
            new_name='guide_event_event_t_03dd58_idx',
            old_name='guide_event_type_created_idx',
        ),
        migrations.RenameIndex(
            model_name='guideevent',
            new_name='guide_event_article_7444b1_idx',
            old_name='guide_event_article_idx',
        ),
    ]
