# Generated by Django 6.0 on 2025-12-26 08:06

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0005_add_patient_verification'),
        ('visits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Channel name', max_length=50, unique=True)),
                ('channel_type', models.CharField(choices=[('PAYSTACK', 'Paystack'), ('MOBILE_MONEY', 'Mobile Money'), ('BANK_TRANSFER', 'Bank Transfer'), ('CASH', 'Cash'), ('CARD', 'Card'), ('INSURANCE', 'Insurance')], help_text='Type of payment channel', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether channel is active')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Channel-specific configuration (API keys, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Channel',
                'verbose_name_plural': 'Payment Channels',
                'db_table': 'payment_channels',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current wallet balance', max_digits=10)),
                ('currency', models.CharField(default='NGN', help_text='Currency code (e.g., NGN, USD)', max_length=3)),
                ('is_active', models.BooleanField(default=True, help_text='Whether wallet is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When wallet was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When wallet was last updated')),
                ('patient', models.OneToOneField(help_text='Patient this wallet belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
                'db_table': 'wallets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], help_text='Type of transaction', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount', max_digits=10)),
                ('balance_after', models.DecimalField(decimal_places=2, help_text='Wallet balance after this transaction', max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='COMPLETED', help_text='Transaction status', max_length=20)),
                ('gateway_transaction_id', models.CharField(blank=True, help_text='Transaction ID from payment gateway (e.g., Paystack reference)', max_length=255)),
                ('gateway_response', models.JSONField(blank=True, default=dict, help_text='Response from payment gateway')),
                ('description', models.TextField(blank=True, help_text='Transaction description')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When transaction was created')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who initiated the transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to=settings.AUTH_USER_MODEL)),
                ('payment_channel', models.ForeignKey(blank=True, help_text='Payment channel used', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='wallet.paymentchannel')),
                ('visit', models.ForeignKey(blank=True, help_text='Visit this transaction is related to (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='visits.visit')),
                ('wallet', models.ForeignKey(help_text='Wallet this transaction belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallet.wallet')),
            ],
            options={
                'verbose_name': 'Wallet Transaction',
                'verbose_name_plural': 'Wallet Transactions',
                'db_table': 'wallet_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['patient'], name='wallets_patient_95e3e8_idx'),
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['is_active'], name='wallets_is_acti_3744ed_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['wallet', 'created_at'], name='wallet_tran_wallet__aa27da_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['visit'], name='wallet_tran_visit_i_740903_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['status'], name='wallet_tran_status_c987ce_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['gateway_transaction_id'], name='wallet_tran_gateway_71c1f4_idx'),
        ),
    ]
