# Generated by Django 6.0 on 2025-12-22 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', help_text='Visit status. CLOSED visits are immutable.', max_length=20)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('CLEARED', 'Cleared')], default='PENDING', help_text='Payment status. Must be CLEARED for clinical actions.', max_length=20)),
                ('closed_at', models.DateTimeField(blank=True, help_text='When the visit was closed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the visit was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the visit was last updated')),
                ('closed_by', models.ForeignKey(blank=True, help_text='Doctor who closed this visit', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_visits', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(help_text='Patient for this visit', on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Visit',
                'verbose_name_plural': 'Visits',
                'db_table': 'visits',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient'], name='visits_patient_b32649_idx'), models.Index(fields=['status'], name='visits_status_79e0cd_idx'), models.Index(fields=['payment_status'], name='visits_payment_66a3b8_idx'), models.Index(fields=['created_at'], name='visits_created_17ceaf_idx')],
            },
        ),
    ]
