# Generated by Django 5.2.7 on 2026-01-11 09:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0005_migrate_old_payment_statuses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('VISIT_CREATED', 'Visit Created'), ('CONSULTATION_STARTED', 'Consultation Started'), ('CONSULTATION_CLOSED', 'Consultation Closed'), ('SERVICE_SELECTED', 'Service Selected'), ('LAB_ORDERED', 'Lab Ordered'), ('LAB_RESULT_POSTED', 'Lab Result Posted'), ('RADIOLOGY_ORDERED', 'Radiology Ordered'), ('RADIOLOGY_REPORT_POSTED', 'Radiology Report Posted'), ('DRUG_DISPENSED', 'Drug Dispensed'), ('PAYMENT_CONFIRMED', 'Payment Confirmed'), ('PROCEDURE_ORDERED', 'Procedure Ordered'), ('PROCEDURE_COMPLETED', 'Procedure Completed')], help_text='Type of timeline event', max_length=50)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='When the event occurred')),
                ('actor_role', models.CharField(blank=True, help_text='Role of the actor at the time of the event', max_length=50)),
                ('description', models.TextField(help_text='Human-readable description of the event')),
                ('source_type', models.CharField(blank=True, help_text="Type of source object (e.g., 'consultation', 'lab_order')", max_length=100)),
                ('source_id', models.PositiveIntegerField(blank=True, help_text='ID of the source object', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional event metadata (e.g., service name, amount)')),
                ('deduplication_key', models.CharField(db_index=True, help_text='Unique key to prevent duplicate events (format: visit_id:event_type:source_id)', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this timeline event was created')),
                ('actor', models.ForeignKey(blank=True, help_text='User who triggered this event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_events', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(help_text='Visit this event belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='visits.visit')),
            ],
            options={
                'verbose_name': 'Timeline Event',
                'verbose_name_plural': 'Timeline Events',
                'db_table': 'timeline_events',
                'ordering': ['timestamp', 'created_at'],
                'indexes': [models.Index(fields=['visit', 'timestamp'], name='timeline_ev_visit_i_3e6b2a_idx'), models.Index(fields=['event_type'], name='timeline_ev_event_t_a263b2_idx'), models.Index(fields=['deduplication_key'], name='timeline_ev_dedupli_17fcd9_idx')],
            },
        ),
    ]
