# Generated by Django 6.0 on 2026-06-02 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0007_add_organization'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='visit',
            new_name='visits_organiz_de1917_idx',
            old_name='visits_organiz_idx',
        ),
    ]
