# Generated by Django 5.2.7 on 2026-05-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0007_visit_assigned_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='service_area',
            field=models.CharField(blank=True, help_text='Legacy clinic desk / charge item name (LIFEWAY visit ClinicID -> tblChargeItem.Name)', max_length=200, null=True),
        ),
    ]
