# Generated by Django 5.2.7 on 2026-06-29 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0010_rename_visits_organiz_idx_visits_organiz_de1917_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='assigned_doctor',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='service_area',
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_type',
            field=models.CharField(blank=True, choices=[('CONSULTATION', 'Consultation'), ('FOLLOW_UP', 'Follow-up'), ('EMERGENCY', 'Emergency'), ('ROUTINE', 'Routine'), ('SPECIALIST', 'Specialist'), ('SANDBOX', 'Sandbox (Guide Practice)')], help_text='Type of visit', max_length=50, null=True),
        ),
    ]
