# Generated migration for IVF module

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IVFCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_number', models.PositiveIntegerField(default=1, help_text='Sequential cycle number for this patient')),
                ('cycle_type', models.CharField(choices=[('FRESH_IVF', 'Fresh IVF Cycle'), ('FET', 'Frozen Embryo Transfer'), ('IUI', 'Intrauterine Insemination'), ('ICSI', 'Intracytoplasmic Sperm Injection'), ('EGG_DONATION', 'Egg Donation Cycle'), ('SPERM_DONATION', 'Sperm Donation Cycle'), ('SURROGACY', 'Surrogacy Cycle'), ('EGG_FREEZING', 'Egg Freezing (Oocyte Cryopreservation)'), ('SPERM_FREEZING', 'Sperm Freezing')], default='FRESH_IVF', help_text='Type of IVF cycle', max_length=20)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('STIMULATION', 'Ovarian Stimulation'), ('RETRIEVAL', 'Egg Retrieval'), ('FERTILIZATION', 'Fertilization'), ('CULTURE', 'Embryo Culture'), ('TRANSFER', 'Embryo Transfer'), ('LUTEAL', 'Luteal Phase Support'), ('PREGNANCY_TEST', 'Pregnancy Test'), ('PREGNANT', 'Pregnant'), ('NOT_PREGNANT', 'Not Pregnant'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='PLANNED', help_text='Current cycle status', max_length=20)),
                ('planned_start_date', models.DateField(blank=True, help_text='Planned cycle start date', null=True)),
                ('actual_start_date', models.DateField(blank=True, help_text='Actual stimulation start date', null=True)),
                ('lmp_date', models.DateField(blank=True, help_text='Last Menstrual Period date', null=True)),
                ('protocol', models.CharField(blank=True, help_text='Stimulation protocol', max_length=100)),
                ('diagnosis', models.TextField(blank=True, help_text='Infertility diagnosis')),
                ('consent_signed', models.BooleanField(default=False, help_text='Patient consent form signed')),
                ('consent_date', models.DateField(blank=True, help_text='Date consent was signed', null=True)),
                ('partner_consent_signed', models.BooleanField(default=False, help_text='Partner consent form signed')),
                ('partner_consent_date', models.DateField(blank=True, help_text='Date partner consent was signed', null=True)),
                ('cancellation_reason', models.CharField(blank=True, choices=[('POOR_RESPONSE', 'Poor Ovarian Response'), ('OHSS_RISK', 'OHSS Risk'), ('NO_FERTILIZATION', 'No Fertilization'), ('NO_VIABLE_EMBRYOS', 'No Viable Embryos'), ('PATIENT_REQUEST', 'Patient Request'), ('MEDICAL_CONTRAINDICATION', 'Medical Contraindication'), ('FINANCIAL', 'Financial Reasons'), ('OTHER', 'Other')], help_text='Reason for cycle cancellation', max_length=30)),
                ('cancellation_notes', models.TextField(blank=True, help_text='Detailed notes on cancellation')),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='When the cycle was cancelled', null=True)),
                ('pregnancy_test_date', models.DateField(blank=True, help_text='Date of pregnancy test', null=True)),
                ('beta_hcg_result', models.DecimalField(blank=True, decimal_places=2, help_text='Beta-hCG result (mIU/mL)', max_digits=10, null=True)),
                ('pregnancy_outcome', models.CharField(blank=True, choices=[('POSITIVE', 'Positive'), ('NEGATIVE', 'Negative'), ('CHEMICAL', 'Chemical Pregnancy'), ('ECTOPIC', 'Ectopic Pregnancy'), ('MISCARRIAGE', 'Miscarriage'), ('ONGOING', 'Ongoing Pregnancy'), ('LIVE_BIRTH', 'Live Birth'), ('STILLBIRTH', 'Stillbirth')], help_text='Final pregnancy outcome', max_length=50)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated total cycle cost (NGN)', max_digits=12, null=True)),
                ('insurance_pre_auth', models.BooleanField(default=False, help_text='Insurance pre-authorization obtained')),
                ('insurance_pre_auth_number', models.CharField(blank=True, help_text='Insurance pre-authorization number', max_length=100)),
                ('clinical_notes', models.TextField(blank=True, help_text='Clinical notes and observations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='User who created this cycle', on_delete=django.db.models.deletion.PROTECT, related_name='ivf_cycles_created', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(blank=True, help_text='Male partner (if applicable)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ivf_cycles_as_partner', to='patients.patient')),
                ('patient', models.ForeignKey(help_text='Primary patient (female partner in heterosexual couples)', on_delete=django.db.models.deletion.PROTECT, related_name='ivf_cycles', to='patients.patient')),
            ],
            options={
                'verbose_name': 'IVF Cycle',
                'verbose_name_plural': 'IVF Cycles',
                'db_table': 'ivf_cycles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OvarianStimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveIntegerField(help_text='Stimulation day number')),
                ('date', models.DateField(help_text='Date of stimulation monitoring')),
                ('estradiol', models.DecimalField(blank=True, decimal_places=2, help_text='Estradiol level (pg/mL)', max_digits=10, null=True)),
                ('lh', models.DecimalField(blank=True, decimal_places=2, help_text='LH level (mIU/mL)', max_digits=10, null=True)),
                ('progesterone', models.DecimalField(blank=True, decimal_places=2, help_text='Progesterone level (ng/mL)', max_digits=10, null=True)),
                ('endometrial_thickness', models.DecimalField(blank=True, decimal_places=1, help_text='Endometrial thickness (mm)', max_digits=5, null=True)),
                ('endometrial_pattern', models.CharField(blank=True, choices=[('TRILAMINAR', 'Trilaminar'), ('HYPERECHOIC', 'Hyperechoic'), ('HYPOECHOIC', 'Hypoechoic'), ('HOMOGENEOUS', 'Homogeneous')], help_text='Endometrial pattern on ultrasound', max_length=20)),
                ('right_ovary_follicles', models.JSONField(blank=True, default=list, help_text='Right ovary follicle sizes (mm) as array')),
                ('left_ovary_follicles', models.JSONField(blank=True, default=list, help_text='Left ovary follicle sizes (mm) as array')),
                ('medications', models.JSONField(blank=True, default=list, help_text="Medications with doses")),
                ('notes', models.TextField(blank=True, help_text='Clinical notes for the day')),
                ('next_appointment', models.DateTimeField(blank=True, help_text='Next monitoring appointment', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stimulation_records', to='ivf.ivfcycle')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stimulation_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ovarian Stimulation Record',
                'verbose_name_plural': 'Ovarian Stimulation Records',
                'db_table': 'ivf_ovarian_stimulation',
                'ordering': ['cycle', 'day'],
                'unique_together': {('cycle', 'day')},
            },
        ),
        migrations.CreateModel(
            name='OocyteRetrieval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_date', models.DateField(help_text='Date of egg retrieval')),
                ('procedure_time', models.TimeField(blank=True, help_text='Time procedure started', null=True)),
                ('trigger_medication', models.CharField(blank=True, help_text='Trigger medication used', max_length=100)),
                ('trigger_time', models.DateTimeField(blank=True, help_text='Time of trigger injection', null=True)),
                ('anesthesia_type', models.CharField(blank=True, choices=[('NONE', 'None'), ('LOCAL', 'Local'), ('CONSCIOUS_SEDATION', 'Conscious Sedation'), ('GENERAL', 'General Anesthesia')], help_text='Type of anesthesia used', max_length=50)),
                ('anesthesiologist', models.CharField(blank=True, help_text='Anesthesiologist name', max_length=100)),
                ('right_ovary_oocytes', models.PositiveIntegerField(default=0, help_text='Oocytes retrieved from right ovary')),
                ('left_ovary_oocytes', models.PositiveIntegerField(default=0, help_text='Oocytes retrieved from left ovary')),
                ('total_oocytes_retrieved', models.PositiveIntegerField(default=0, help_text='Total oocytes retrieved')),
                ('mature_oocytes', models.PositiveIntegerField(default=0, help_text='Number of mature (MII) oocytes')),
                ('immature_oocytes', models.PositiveIntegerField(default=0, help_text='Number of immature oocytes')),
                ('degenerated_oocytes', models.PositiveIntegerField(default=0, help_text='Number of degenerated oocytes')),
                ('complications', models.TextField(blank=True, help_text='Any complications during procedure')),
                ('blood_loss', models.CharField(blank=True, choices=[('MINIMAL', 'Minimal'), ('MODERATE', 'Moderate'), ('SIGNIFICANT', 'Significant')], help_text='Estimated blood loss', max_length=20)),
                ('recovery_notes', models.TextField(blank=True, help_text='Post-procedure recovery notes')),
                ('discharge_time', models.TimeField(blank=True, help_text='Time patient discharged', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cycle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='oocyte_retrieval', to='ivf.ivfcycle')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oocyte_retrievals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Oocyte Retrieval',
                'verbose_name_plural': 'Oocyte Retrievals',
                'db_table': 'ivf_oocyte_retrieval',
            },
        ),
        migrations.CreateModel(
            name='SpermAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_date', models.DateField(help_text='Date of sample collection')),
                ('collection_time', models.TimeField(blank=True, help_text='Time of sample collection', null=True)),
                ('abstinence_days', models.PositiveIntegerField(blank=True, help_text='Days of abstinence before collection', null=True)),
                ('sample_source', models.CharField(choices=[('FRESH', 'Fresh Ejaculate'), ('FROZEN', 'Frozen Sample'), ('TESE', 'Testicular Sperm Extraction'), ('MESA', 'Microsurgical Epididymal Sperm Aspiration'), ('PESA', 'Percutaneous Epididymal Sperm Aspiration'), ('DONOR', 'Donor Sperm')], default='FRESH', help_text='Source of sperm sample', max_length=20)),
                ('volume', models.DecimalField(blank=True, decimal_places=2, help_text='Volume (mL)', max_digits=5, null=True)),
                ('appearance', models.CharField(blank=True, choices=[('NORMAL', 'Normal (Grey-opalescent)'), ('YELLOW', 'Yellow'), ('RED_BROWN', 'Red/Brown (Haemospermia)'), ('CLEAR', 'Clear')], help_text='Sample appearance', max_length=50)),
                ('liquefaction_time', models.PositiveIntegerField(blank=True, help_text='Liquefaction time (minutes)', null=True)),
                ('ph', models.DecimalField(blank=True, decimal_places=1, help_text='pH', max_digits=3, null=True)),
                ('viscosity', models.CharField(blank=True, choices=[('NORMAL', 'Normal'), ('INCREASED', 'Increased')], help_text='Viscosity assessment', max_length=20)),
                ('concentration', models.DecimalField(blank=True, decimal_places=2, help_text='Sperm concentration (million/mL)', max_digits=10, null=True)),
                ('total_sperm_count', models.DecimalField(blank=True, decimal_places=2, help_text='Total sperm count (million)', max_digits=10, null=True)),
                ('progressive_motility', models.DecimalField(blank=True, decimal_places=2, help_text='Progressive motility (%)', max_digits=5, null=True)),
                ('non_progressive_motility', models.DecimalField(blank=True, decimal_places=2, help_text='Non-progressive motility (%)', max_digits=5, null=True)),
                ('immotile', models.DecimalField(blank=True, decimal_places=2, help_text='Immotile sperm (%)', max_digits=5, null=True)),
                ('total_motility', models.DecimalField(blank=True, decimal_places=2, help_text='Total motility (%)', max_digits=5, null=True)),
                ('normal_forms', models.DecimalField(blank=True, decimal_places=2, help_text='Normal morphology (%)', max_digits=5, null=True)),
                ('head_defects', models.DecimalField(blank=True, decimal_places=2, help_text='Head defects (%)', max_digits=5, null=True)),
                ('midpiece_defects', models.DecimalField(blank=True, decimal_places=2, help_text='Midpiece defects (%)', max_digits=5, null=True)),
                ('tail_defects', models.DecimalField(blank=True, decimal_places=2, help_text='Tail defects (%)', max_digits=5, null=True)),
                ('vitality', models.DecimalField(blank=True, decimal_places=2, help_text='Vitality/Live sperm (%)', max_digits=5, null=True)),
                ('round_cells', models.DecimalField(blank=True, decimal_places=2, help_text='Round cells (million/mL)', max_digits=10, null=True)),
                ('wbc_count', models.DecimalField(blank=True, decimal_places=2, help_text='WBC count (million/mL)', max_digits=10, null=True)),
                ('dna_fragmentation_index', models.DecimalField(blank=True, decimal_places=2, help_text='DNA Fragmentation Index (DFI) %', max_digits=5, null=True)),
                ('assessment', models.CharField(blank=True, choices=[('NORMOZOOSPERMIA', 'Normozoospermia'), ('OLIGOZOOSPERMIA', 'Oligozoospermia'), ('ASTHENOZOOSPERMIA', 'Asthenozoospermia'), ('TERATOZOOSPERMIA', 'Teratozoospermia'), ('OLIGOASTHENOZOOSPERMIA', 'Oligoasthenozoospermia'), ('OLIGOASTHENOTERATOZOOSPERMIA', 'Oligoasthenoteratozoospermia (OAT)'), ('AZOOSPERMIA', 'Azoospermia'), ('CRYPTOZOOSPERMIA', 'Cryptozoospermia'), ('NECROZOOSPERMIA', 'Necrozoospermia')], help_text='Overall assessment', max_length=50)),
                ('recommendation', models.TextField(blank=True, help_text='Clinical recommendation')),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analyzed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sperm_analyses', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sperm_analyses', to='ivf.ivfcycle')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sperm_analyses', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Sperm Analysis',
                'verbose_name_plural': 'Sperm Analyses',
                'db_table': 'ivf_sperm_analysis',
                'ordering': ['-collection_date'],
            },
        ),
        migrations.CreateModel(
            name='Embryo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embryo_number', models.PositiveIntegerField(help_text='Embryo number within the cycle')),
                ('lab_id', models.CharField(help_text='Unique laboratory identifier', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('FERTILIZED', 'Fertilized (2PN)'), ('CLEAVING', 'Cleaving'), ('MORULA', 'Morula'), ('BLASTOCYST', 'Blastocyst'), ('TRANSFERRED', 'Transferred'), ('FROZEN', 'Frozen (Cryopreserved)'), ('THAWED', 'Thawed'), ('DISCARDED', 'Discarded'), ('DONATED', 'Donated'), ('ARRESTED', 'Arrested Development')], default='FERTILIZED', help_text='Current embryo status', max_length=20)),
                ('fertilization_method', models.CharField(choices=[('IVF', 'Conventional IVF'), ('ICSI', 'ICSI'), ('SPLIT', 'Split (IVF + ICSI)'), ('IMSI', 'IMSI')], default='IVF', help_text='Method of fertilization', max_length=20)),
                ('fertilization_date', models.DateField(help_text='Date of fertilization (Day 0)')),
                ('fertilization_time', models.TimeField(blank=True, help_text='Time of insemination/ICSI', null=True)),
                ('day1_pn_status', models.CharField(blank=True, choices=[('2PN', '2 Pronuclei (Normal)'), ('1PN', '1 Pronucleus'), ('3PN', '3 Pronuclei (Abnormal)'), ('0PN', 'No Pronuclei'), ('DEGENERATED', 'Degenerated')], help_text='Pronuclear status at Day 1', max_length=15)),
                ('day2_cell_count', models.PositiveIntegerField(blank=True, help_text='Cell count at Day 2', null=True)),
                ('day3_cell_count', models.PositiveIntegerField(blank=True, help_text='Cell count at Day 3', null=True)),
                ('day3_grade', models.CharField(blank=True, help_text='Day 3 embryo grade', max_length=10)),
                ('fragmentation', models.PositiveIntegerField(blank=True, help_text='Fragmentation percentage', null=True)),
                ('blastocyst_day', models.PositiveIntegerField(blank=True, choices=[(5, 'Day 5'), (6, 'Day 6'), (7, 'Day 7')], help_text='Day blastocyst formed', null=True)),
                ('blastocyst_grade', models.CharField(blank=True, help_text='Blastocyst grade', max_length=10)),
                ('expansion_grade', models.CharField(blank=True, choices=[('1', '1 - Early blastocyst'), ('2', '2 - Blastocyst'), ('3', '3 - Full blastocyst'), ('4', '4 - Expanded blastocyst'), ('5', '5 - Hatching blastocyst'), ('6', '6 - Hatched blastocyst')], help_text='Blastocyst expansion grade', max_length=5)),
                ('icm_grade', models.CharField(blank=True, choices=[('A', 'A - Many cells, tightly packed'), ('B', 'B - Several cells, loosely grouped'), ('C', 'C - Few cells')], help_text='Inner Cell Mass (ICM) grade', max_length=5)),
                ('trophectoderm_grade', models.CharField(blank=True, choices=[('A', 'A - Many cells, cohesive layer'), ('B', 'B - Few cells, loose epithelium'), ('C', 'C - Very few cells')], help_text='Trophectoderm (TE) grade', max_length=5)),
                ('pgt_performed', models.BooleanField(default=False, help_text='PGT performed on this embryo')),
                ('pgt_result', models.CharField(blank=True, choices=[('EUPLOID', 'Euploid (Normal)'), ('ANEUPLOID', 'Aneuploid (Abnormal)'), ('MOSAIC', 'Mosaic'), ('NO_RESULT', 'No Result'), ('PENDING', 'Pending')], help_text='PGT result', max_length=50)),
                ('pgt_details', models.TextField(blank=True, help_text='Detailed PGT findings')),
                ('frozen_date', models.DateField(blank=True, help_text='Date embryo was frozen', null=True)),
                ('storage_location', models.CharField(blank=True, help_text='Cryostorage tank/canister/position', max_length=100)),
                ('straw_id', models.CharField(blank=True, help_text='Cryostraw identifier', max_length=50)),
                ('thaw_date', models.DateField(blank=True, help_text='Date embryo was thawed', null=True)),
                ('survived_thaw', models.BooleanField(blank=True, help_text='Did embryo survive thawing?', null=True)),
                ('disposition', models.CharField(blank=True, choices=[('TRANSFERRED', 'Transferred'), ('STORAGE', 'In Storage'), ('DISCARDED_QUALITY', 'Discarded - Poor Quality'), ('DISCARDED_CONSENT', 'Discarded - Per Consent'), ('DISCARDED_EXPIRED', 'Discarded - Storage Expired'), ('DONATED_RESEARCH', 'Donated to Research'), ('DONATED_PATIENT', 'Donated to Another Patient')], help_text='Final embryo disposition', max_length=50)),
                ('disposition_date', models.DateField(blank=True, help_text='Date of disposition', null=True)),
                ('disposition_notes', models.TextField(blank=True, help_text='Notes on disposition')),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='embryos_created', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embryos', to='ivf.ivfcycle')),
            ],
            options={
                'verbose_name': 'Embryo',
                'verbose_name_plural': 'Embryos',
                'db_table': 'ivf_embryos',
                'ordering': ['cycle', 'embryo_number'],
                'unique_together': {('cycle', 'embryo_number')},
            },
        ),
        migrations.CreateModel(
            name='EmbryoTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateField(help_text='Date of embryo transfer')),
                ('transfer_time', models.TimeField(blank=True, help_text='Time of transfer', null=True)),
                ('transfer_type', models.CharField(choices=[('FRESH', 'Fresh Transfer'), ('FROZEN', 'Frozen Embryo Transfer (FET)')], default='FRESH', help_text='Type of transfer', max_length=20)),
                ('embryos_transferred_count', models.PositiveIntegerField(default=1, help_text='Number of embryos transferred')),
                ('embryo_stage', models.CharField(blank=True, choices=[('CLEAVAGE', 'Cleavage Stage (Day 2-3)'), ('BLASTOCYST', 'Blastocyst (Day 5-6)')], help_text='Stage of embryos transferred', max_length=20)),
                ('catheter_type', models.CharField(blank=True, help_text='Transfer catheter used', max_length=100)),
                ('ultrasound_guided', models.BooleanField(default=True, help_text='Transfer performed under ultrasound guidance')),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MODERATE', 'Moderate'), ('DIFFICULT', 'Difficult')], default='EASY', help_text='Technical difficulty', max_length=20)),
                ('endometrial_thickness', models.DecimalField(blank=True, decimal_places=1, help_text='Endometrial thickness at transfer (mm)', max_digits=5, null=True)),
                ('uterine_position', models.CharField(blank=True, choices=[('ANTEVERTED', 'Anteverted'), ('RETROVERTED', 'Retroverted'), ('MIDPOSITION', 'Mid-position')], help_text='Uterine position', max_length=20)),
                ('distance_from_fundus', models.DecimalField(blank=True, decimal_places=1, help_text='Distance of catheter tip from fundus (cm)', max_digits=4, null=True)),
                ('blood_on_catheter', models.BooleanField(default=False, help_text='Blood observed on catheter')),
                ('mucus_on_catheter', models.BooleanField(default=False, help_text='Mucus observed on catheter')),
                ('embryos_retained', models.BooleanField(default=False, help_text='Were any embryos retained in catheter?')),
                ('bed_rest_duration', models.PositiveIntegerField(default=30, help_text='Recommended bed rest (minutes)')),
                ('medications_prescribed', models.JSONField(blank=True, default=list, help_text='Post-transfer medications')),
                ('notes', models.TextField(blank=True, help_text='Procedure notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embryo_transfers', to='ivf.ivfcycle')),
                ('embryos', models.ManyToManyField(help_text='Embryos transferred', related_name='transfers', to='ivf.embryo')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='embryo_transfers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Embryo Transfer',
                'verbose_name_plural': 'Embryo Transfers',
                'db_table': 'ivf_embryo_transfers',
                'ordering': ['-transfer_date'],
            },
        ),
        migrations.CreateModel(
            name='IVFMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(help_text='Medication name', max_length=100)),
                ('category', models.CharField(choices=[('GNRH_AGONIST', 'GnRH Agonist'), ('GNRH_ANTAGONIST', 'GnRH Antagonist'), ('GONADOTROPIN', 'Gonadotropin (FSH/LH)'), ('HCG', 'hCG Trigger'), ('PROGESTERONE', 'Progesterone Support'), ('ESTROGEN', 'Estrogen'), ('ANTIBIOTIC', 'Antibiotic'), ('OTHER', 'Other')], help_text='Medication category', max_length=20)),
                ('dose', models.DecimalField(decimal_places=2, help_text='Dose amount', max_digits=10)),
                ('unit', models.CharField(help_text='Dose unit', max_length=20)),
                ('route', models.CharField(choices=[('SUBCUTANEOUS', 'Subcutaneous'), ('INTRAMUSCULAR', 'Intramuscular'), ('ORAL', 'Oral'), ('VAGINAL', 'Vaginal'), ('TRANSDERMAL', 'Transdermal')], help_text='Route of administration', max_length=30)),
                ('frequency', models.CharField(help_text='Frequency', max_length=50)),
                ('start_date', models.DateField(help_text='Start date')),
                ('end_date', models.DateField(blank=True, help_text='End date', null=True)),
                ('instructions', models.TextField(blank=True, help_text='Special instructions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='ivf.ivfcycle')),
                ('prescribed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ivf_medications_prescribed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'IVF Medication',
                'verbose_name_plural': 'IVF Medications',
                'db_table': 'ivf_medications',
                'ordering': ['cycle', 'start_date'],
            },
        ),
        migrations.CreateModel(
            name='IVFOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinical_pregnancy', models.BooleanField(default=False, help_text='Clinical pregnancy confirmed')),
                ('clinical_pregnancy_date', models.DateField(blank=True, help_text='Date clinical pregnancy confirmed', null=True)),
                ('fetal_heartbeat', models.BooleanField(default=False, help_text='Fetal heartbeat detected')),
                ('fetal_heartbeat_date', models.DateField(blank=True, help_text='Date fetal heartbeat detected', null=True)),
                ('gestational_sacs', models.PositiveIntegerField(default=0, help_text='Number of gestational sacs')),
                ('fetal_poles', models.PositiveIntegerField(default=0, help_text='Number of fetal poles with heartbeat')),
                ('miscarriage', models.BooleanField(default=False, help_text='Miscarriage occurred')),
                ('miscarriage_date', models.DateField(blank=True, help_text='Date of miscarriage', null=True)),
                ('miscarriage_gestational_age', models.PositiveIntegerField(blank=True, help_text='Gestational age at miscarriage (weeks)', null=True)),
                ('ectopic', models.BooleanField(default=False, help_text='Ectopic pregnancy')),
                ('delivery_date', models.DateField(blank=True, help_text='Date of delivery', null=True)),
                ('gestational_age_at_delivery', models.PositiveIntegerField(blank=True, help_text='Gestational age at delivery (weeks)', null=True)),
                ('delivery_type', models.CharField(blank=True, choices=[('VAGINAL', 'Vaginal Delivery'), ('CESAREAN_ELECTIVE', 'Elective Cesarean Section'), ('CESAREAN_EMERGENCY', 'Emergency Cesarean Section')], help_text='Type of delivery', max_length=30)),
                ('live_births', models.PositiveIntegerField(default=0, help_text='Number of live births')),
                ('stillbirths', models.PositiveIntegerField(default=0, help_text='Number of stillbirths')),
                ('neonatal_deaths', models.PositiveIntegerField(default=0, help_text='Number of neonatal deaths')),
                ('birth_weights', models.JSONField(blank=True, default=list, help_text='Birth weights in grams')),
                ('maternal_complications', models.TextField(blank=True, help_text='Maternal complications')),
                ('neonatal_complications', models.TextField(blank=True, help_text='Neonatal complications')),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cycle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outcome', to='ivf.ivfcycle')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ivf_outcomes_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'IVF Outcome',
                'verbose_name_plural': 'IVF Outcomes',
                'db_table': 'ivf_outcomes',
            },
        ),
        migrations.CreateModel(
            name='IVFConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_type', models.CharField(choices=[('TREATMENT', 'IVF Treatment Consent'), ('EGG_RETRIEVAL', 'Egg Retrieval Consent'), ('SPERM_COLLECTION', 'Sperm Collection Consent'), ('EMBRYO_TRANSFER', 'Embryo Transfer Consent'), ('EMBRYO_FREEZING', 'Embryo Cryopreservation Consent'), ('EMBRYO_DISPOSITION', 'Embryo Disposition Consent'), ('EGG_FREEZING', 'Egg Freezing Consent'), ('SPERM_FREEZING', 'Sperm Freezing Consent'), ('PGT', 'Genetic Testing Consent'), ('DONOR_EGG', 'Donor Egg Consent'), ('DONOR_SPERM', 'Donor Sperm Consent'), ('SURROGACY', 'Surrogacy Agreement Consent')], help_text='Type of consent', max_length=30)),
                ('signed', models.BooleanField(default=False, help_text='Has been signed')),
                ('signed_date', models.DateField(blank=True, help_text='Date signed', null=True)),
                ('signed_time', models.TimeField(blank=True, help_text='Time signed', null=True)),
                ('witness_name', models.CharField(blank=True, help_text='Witness name', max_length=100)),
                ('witness_signature', models.BooleanField(default=False, help_text='Witness signed')),
                ('document_path', models.FileField(blank=True, help_text='Scanned consent document', null=True, upload_to='ivf_consents/')),
                ('revoked', models.BooleanField(default=False, help_text='Consent has been revoked')),
                ('revoked_date', models.DateField(blank=True, help_text='Date consent was revoked', null=True)),
                ('revocation_reason', models.TextField(blank=True, help_text='Reason for revocation')),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='ivf.ivfcycle')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ivf_consents', to='patients.patient')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ivf_consents_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'IVF Consent',
                'verbose_name_plural': 'IVF Consents',
                'db_table': 'ivf_consents',
                'ordering': ['-created_at'],
                'unique_together': {('cycle', 'consent_type', 'patient')},
            },
        ),
        migrations.AddIndex(
            model_name='ivfcycle',
            index=models.Index(fields=['patient'], name='ivf_cycles_patient_01ada8_idx'),
        ),
        migrations.AddIndex(
            model_name='ivfcycle',
            index=models.Index(fields=['partner'], name='ivf_cycles_partner_9461b3_idx'),
        ),
        migrations.AddIndex(
            model_name='ivfcycle',
            index=models.Index(fields=['status'], name='ivf_cycles_status_5c0f0c_idx'),
        ),
        migrations.AddIndex(
            model_name='ivfcycle',
            index=models.Index(fields=['cycle_type'], name='ivf_cycles_cycle_t_62d2af_idx'),
        ),
        migrations.AddIndex(
            model_name='ivfcycle',
            index=models.Index(fields=['created_at'], name='ivf_cycles_created_13f3f9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ivfcycle',
            unique_together={('patient', 'cycle_number')},
        ),
    ]
