# Generated by Django 6.0 on 2026-01-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivf', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ivfcycle',
            new_name='ivf_cycles_patient_5803be_idx',
            old_name='ivf_cycles_patient_01ada8_idx',
        ),
        migrations.RenameIndex(
            model_name='ivfcycle',
            new_name='ivf_cycles_partner_b24523_idx',
            old_name='ivf_cycles_partner_9461b3_idx',
        ),
        migrations.RenameIndex(
            model_name='ivfcycle',
            new_name='ivf_cycles_status_e54afd_idx',
            old_name='ivf_cycles_status_5c0f0c_idx',
        ),
        migrations.RenameIndex(
            model_name='ivfcycle',
            new_name='ivf_cycles_cycle_t_c1dcef_idx',
            old_name='ivf_cycles_cycle_t_62d2af_idx',
        ),
        migrations.RenameIndex(
            model_name='ivfcycle',
            new_name='ivf_cycles_created_e55891_idx',
            old_name='ivf_cycles_created_13f3f9_idx',
        ),
        migrations.AlterField(
            model_name='embryo',
            name='blastocyst_grade',
            field=models.CharField(blank=True, help_text='Blastocyst grade (e.g., 4AA, 3BB)', max_length=10),
        ),
        migrations.AlterField(
            model_name='embryo',
            name='day3_grade',
            field=models.CharField(blank=True, help_text='Day 3 embryo grade (e.g., 8A, 6B)', max_length=10),
        ),
        migrations.AlterField(
            model_name='ivfcycle',
            name='protocol',
            field=models.CharField(blank=True, help_text='Stimulation protocol (e.g., Long GnRH agonist, Antagonist, Mini-IVF)', max_length=100),
        ),
        migrations.AlterField(
            model_name='ivfmedication',
            name='end_date',
            field=models.DateField(blank=True, help_text='End date (if known)', null=True),
        ),
        migrations.AlterField(
            model_name='ivfmedication',
            name='frequency',
            field=models.CharField(help_text='Frequency (e.g., Once daily, Twice daily)', max_length=50),
        ),
        migrations.AlterField(
            model_name='ivfmedication',
            name='unit',
            field=models.CharField(help_text='Dose unit (e.g., IU, mg, mcg)', max_length=20),
        ),
        migrations.AlterField(
            model_name='ivfoutcome',
            name='birth_weights',
            field=models.JSONField(blank=True, default=list, help_text='Birth weights in grams [3200, 2800]'),
        ),
        migrations.AlterField(
            model_name='ivfoutcome',
            name='clinical_pregnancy',
            field=models.BooleanField(default=False, help_text='Clinical pregnancy confirmed (gestational sac on ultrasound)'),
        ),
        migrations.AlterField(
            model_name='ivfoutcome',
            name='maternal_complications',
            field=models.TextField(blank=True, help_text='Maternal complications during pregnancy/delivery'),
        ),
        migrations.AlterField(
            model_name='oocyteretrieval',
            name='trigger_medication',
            field=models.CharField(blank=True, help_text='Trigger medication used (e.g., hCG, GnRH agonist)', max_length=100),
        ),
        migrations.AlterField(
            model_name='ovarianstimulation',
            name='medications',
            field=models.JSONField(blank=True, default=list, help_text="Medications with doses [{'name': 'Gonal-F', 'dose': 150, 'unit': 'IU'}]"),
        ),
        migrations.AlterField(
            model_name='spermanalysis',
            name='concentration',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Sperm concentration (million/mL) - WHO ref: >= 16 million/mL', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='spermanalysis',
            name='liquefaction_time',
            field=models.PositiveIntegerField(blank=True, help_text='Liquefaction time (minutes) - Normal: < 60 min', null=True),
        ),
        migrations.AlterField(
            model_name='spermanalysis',
            name='normal_forms',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Normal morphology (%) - WHO ref: >= 4%', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='spermanalysis',
            name='ph',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='pH - WHO ref: >= 7.2', max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='spermanalysis',
            name='progressive_motility',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Progressive motility (%) - WHO ref: >= 30%', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='spermanalysis',
            name='total_motility',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total motility (%) - WHO ref: >= 42%', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='spermanalysis',
            name='total_sperm_count',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total sperm count (million) - WHO ref: >= 39 million', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='spermanalysis',
            name='vitality',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Vitality/Live sperm (%) - WHO ref: >= 54%', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='spermanalysis',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Volume (mL) - WHO ref: >= 1.4 mL', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='spermanalysis',
            name='wbc_count',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='WBC count (million/mL) - Normal: < 1 million/mL', max_digits=10, null=True),
        ),
    ]
