# Generated by Django 6.0 on 2025-12-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_id', models.IntegerField(help_text='Visit ID - offline actions MUST be visit-scoped')),
                ('resource_type', models.CharField(choices=[('CONSULTATION', 'Consultation'), ('LAB_ORDER', 'Lab Order'), ('RADIOLOGY_ORDER', 'Radiology Order'), ('PRESCRIPTION', 'Prescription')], help_text='Type of resource being drafted', max_length=50)),
                ('draft_data', models.JSONField(help_text='Draft data (encrypted, visit-scoped)')),
                ('synced', models.BooleanField(default=False, help_text='Whether this draft has been synced')),
                ('synced_at', models.DateTimeField(blank=True, help_text='When the draft was synced', null=True)),
                ('expires_at', models.DateTimeField(help_text='When this draft expires (auto-cleanup)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When draft was created')),
            ],
            options={
                'verbose_name': 'Offline Draft',
                'verbose_name_plural': 'Offline Drafts',
                'db_table': 'offline_drafts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_id', models.IntegerField(help_text='Visit ID - sync actions MUST be visit-scoped')),
                ('action_type', models.CharField(choices=[('CREATE_CONSULTATION', 'Create Consultation'), ('UPDATE_CONSULTATION', 'Update Consultation'), ('CREATE_LAB_ORDER', 'Create Lab Order'), ('CREATE_RADIOLOGY_ORDER', 'Create Radiology Order'), ('CREATE_PRESCRIPTION', 'Create Prescription')], help_text='Type of action to sync', max_length=50)),
                ('action_data', models.JSONField(help_text='Action data to sync (visit-scoped)')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SYNCING', 'Syncing'), ('SYNCED', 'Synced'), ('FAILED', 'Failed')], default='PENDING', help_text='Sync status', max_length=20)),
                ('synced_at', models.DateTimeField(blank=True, help_text='When the action was synced', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if sync failed')),
                ('retry_count', models.IntegerField(default=0, help_text='Number of sync retry attempts')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When sync item was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When sync item was last updated')),
            ],
            options={
                'verbose_name': 'Sync Queue Item',
                'verbose_name_plural': 'Sync Queue Items',
                'db_table': 'sync_queue',
                'ordering': ['-created_at'],
            },
        ),
    ]
