# Generated by Django 6.0 on 2025-12-22 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offline', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='offlinedraft',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this draft', on_delete=django.db.models.deletion.CASCADE, related_name='offline_drafts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='syncqueue',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this sync item', on_delete=django.db.models.deletion.CASCADE, related_name='sync_queue_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='offlinedraft',
            index=models.Index(fields=['visit_id'], name='offline_dra_visit_i_d34ea4_idx'),
        ),
        migrations.AddIndex(
            model_name='offlinedraft',
            index=models.Index(fields=['resource_type'], name='offline_dra_resourc_a571bb_idx'),
        ),
        migrations.AddIndex(
            model_name='offlinedraft',
            index=models.Index(fields=['created_by'], name='offline_dra_created_3f3d48_idx'),
        ),
        migrations.AddIndex(
            model_name='offlinedraft',
            index=models.Index(fields=['synced'], name='offline_dra_synced_a3018b_idx'),
        ),
        migrations.AddIndex(
            model_name='offlinedraft',
            index=models.Index(fields=['expires_at'], name='offline_dra_expires_ff3164_idx'),
        ),
        migrations.AddIndex(
            model_name='syncqueue',
            index=models.Index(fields=['visit_id'], name='sync_queue_visit_i_6f95da_idx'),
        ),
        migrations.AddIndex(
            model_name='syncqueue',
            index=models.Index(fields=['action_type'], name='sync_queue_action__c440c5_idx'),
        ),
        migrations.AddIndex(
            model_name='syncqueue',
            index=models.Index(fields=['status'], name='sync_queue_status_b33545_idx'),
        ),
        migrations.AddIndex(
            model_name='syncqueue',
            index=models.Index(fields=['created_by'], name='sync_queue_created_2ecaf0_idx'),
        ),
        migrations.AddIndex(
            model_name='syncqueue',
            index=models.Index(fields=['created_at'], name='sync_queue_created_0b1bd8_idx'),
        ),
    ]
