# Generated by Django 5.2.7 on 2026-02-07 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offline', '0003_synclog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='synclog',
            new_name='sync_logs_user_id_90da59_idx',
            old_name='sync_logs_user_device_idx',
        ),
        migrations.RenameIndex(
            model_name='synclog',
            new_name='sync_logs_last_sy_849653_idx',
            old_name='sync_logs_last_sync_idx',
        ),
    ]
