# Generated by Django 5.2.7 on 2026-06-29 22:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offline', '0004_rename_sync_logs_user_device_idx_sync_logs_user_id_90da59_idx_and_more'),
        ('organizations', '0008_alter_saassubscriptionpayment_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicOfflineQueueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=128)),
                ('action', models.CharField(choices=[('REGISTER_PATIENT', 'Register Patient'), ('CHECK_IN_VISIT', 'Check In Visit'), ('RECORD_VITALS', 'Record Vitals'), ('QUEUE_NOTE', 'Queue Note')], max_length=32)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SYNCED', 'Synced'), ('FAILED', 'Failed')], default='PENDING', max_length=16)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offline_queue_entries', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offline_queue_entries', to='organizations.organization')),
            ],
            options={
                'db_table': 'offline_clinic_queue',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['device_id', 'status'], name='offline_cli_device__846439_idx'), models.Index(fields=['organization', 'status'], name='offline_cli_organiz_ddaa5b_idx')],
            },
        ),
    ]
