# Generated by Django 5.2.7 on 2026-06-29 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalHealthHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hub_type', models.CharField(choices=[('NHIA_PORTAL', 'NHIA Claims Portal'), ('NATIONAL_EPRESCRIPTION', 'National E-Prescription Hub'), ('LAB_EXCHANGE', 'National Lab Exchange')], max_length=32, unique=True)),
                ('base_url', models.URLField(blank=True)),
                ('api_key_env', models.CharField(blank=True, help_text='Name of environment variable holding API key', max_length=64)),
                ('is_enabled', models.BooleanField(default=False)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'integrations_external_health_hub',
            },
        ),
    ]
