# Generated by Django 6.0 on 2025-12-24 15:24

import apps.documents.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('visits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('LAB_REPORT', 'Lab Report'), ('RADIOLOGY_REPORT', 'Radiology Report'), ('CONSULTATION_NOTE', 'Consultation Note'), ('PRESCRIPTION', 'Prescription'), ('REFERRAL_LETTER', 'Referral Letter'), ('DISCHARGE_SUMMARY', 'Discharge Summary'), ('CONSENT_FORM', 'Consent Form'), ('INSURANCE_CARD', 'Insurance Card'), ('ID_DOCUMENT', 'ID Document'), ('OTHER', 'Other')], help_text='Type of medical document', max_length=50)),
                ('title', models.CharField(help_text='Document title/name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Document description or notes')),
                ('file', models.FileField(help_text='Document file', upload_to=apps.documents.models.document_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png', 'tiff', 'dcm'])])),
                ('file_size', models.BigIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('mime_type', models.CharField(blank=True, help_text='MIME type of the file', max_length=100)),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag - documents cannot be permanently deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='When document was soft-deleted', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who deleted this document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_deleted', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded this document', on_delete=django.db.models.deletion.PROTECT, related_name='documents_uploaded', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(help_text='Visit this document belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='visits.visit')),
            ],
            options={
                'verbose_name': 'Medical Document',
                'verbose_name_plural': 'Medical Documents',
                'db_table': 'medical_documents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['visit', '-created_at'], name='medical_doc_visit_i_c2e1bb_idx'), models.Index(fields=['document_type', 'is_deleted'], name='medical_doc_documen_e72352_idx'), models.Index(fields=['uploaded_by'], name='medical_doc_uploade_55ae1a_idx')],
            },
        ),
    ]
