# Generated by Django 6.0 on 2025-12-22 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug', models.CharField(help_text='Name of the medication/drug', max_length=255)),
                ('drug_code', models.CharField(blank=True, help_text='Drug code/identifier (e.g., NDC code)', max_length=100)),
                ('dosage', models.CharField(help_text="Dosage instructions (e.g., '500mg twice daily')", max_length=255)),
                ('frequency', models.CharField(blank=True, help_text="Frequency of administration (e.g., 'BID', 'TID', 'QID')", max_length=100)),
                ('duration', models.CharField(blank=True, help_text="Duration of treatment (e.g., '7 days', '2 weeks')", max_length=100)),
                ('quantity', models.CharField(blank=True, help_text="Quantity prescribed (e.g., '30 tablets', '1 bottle')", max_length=100)),
                ('instructions', models.TextField(blank=True, help_text='Additional instructions for the patient')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DISPENSED', 'Dispensed'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Status of the prescription', max_length=20)),
                ('dispensed', models.BooleanField(default=False, help_text='Whether the medication has been dispensed')),
                ('dispensed_date', models.DateTimeField(blank=True, help_text='When the medication was dispensed', null=True)),
                ('dispensing_notes', models.TextField(blank=True, help_text='Notes from pharmacist during dispensing')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the prescription was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the prescription was last updated')),
                ('consultation', models.ForeignKey(help_text='Prescription requires consultation context. Cannot exist without consultation.', on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='consultations.consultation')),
            ],
            options={
                'verbose_name': 'Prescription',
                'verbose_name_plural': 'Prescriptions',
                'db_table': 'prescriptions',
                'ordering': ['-created_at'],
            },
        ),
    ]
