# Generated by Django 6.0 on 2025-12-22 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pharmacy', '0001_initial'),
        ('visits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='dispensed_by',
            field=models.ForeignKey(blank=True, help_text='Pharmacist who dispensed the medication', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions_dispensed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescription',
            name='prescribed_by',
            field=models.ForeignKey(help_text='Doctor who prescribed the medication', on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions_prescribed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescription',
            name='visit',
            field=models.ForeignKey(help_text='Visit is the single source of clinical truth. Prescription is visit-scoped.', on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='visits.visit'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['visit'], name='prescriptio_visit_i_edfe6f_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['consultation'], name='prescriptio_consult_82e09d_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['status'], name='prescriptio_status_1d7db8_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['prescribed_by'], name='prescriptio_prescri_5f3cbf_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['dispensed'], name='prescriptio_dispens_031176_idx'),
        ),
    ]
