# Generated by Django 5.2.7 on 2025-12-23 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the drug/medication (e.g., 'Paracetamol', 'Amoxicillin')", max_length=255, unique=True)),
                ('generic_name', models.CharField(blank=True, help_text='Generic name of the drug', max_length=255)),
                ('drug_code', models.CharField(blank=True, help_text='Drug code/identifier (e.g., NDC code, internal code)', max_length=100, null=True, unique=True)),
                ('drug_class', models.CharField(blank=True, help_text="Drug classification (e.g., 'Antibiotic', 'Analgesic', 'Antihypertensive')", max_length=255)),
                ('dosage_forms', models.CharField(blank=True, help_text="Available dosage forms (e.g., 'Tablet, Capsule, Syrup')", max_length=255)),
                ('common_dosages', models.CharField(blank=True, help_text="Common dosages (e.g., '250mg, 500mg, 1000mg')", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the drug, indications, etc.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the drug is currently available/active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the drug entry was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the drug entry was last updated')),
                ('created_by', models.ForeignKey(help_text='Pharmacist who created this drug entry', on_delete=django.db.models.deletion.PROTECT, related_name='drugs_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Drug',
                'verbose_name_plural': 'Drugs',
                'db_table': 'drugs',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='drugs_name_775e1b_idx'), models.Index(fields=['drug_code'], name='drugs_drug_co_65d97b_idx'), models.Index(fields=['is_active'], name='drugs_is_acti_e467d9_idx'), models.Index(fields=['created_by'], name='drugs_created_834a0a_idx')],
            },
        ),
    ]
