# Generated by Django 5.2.7 on 2025-12-24 04:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_drug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stock', models.DecimalField(decimal_places=2, default=0, help_text='Current stock quantity', max_digits=10)),
                ('unit', models.CharField(default='units', help_text="Unit of measurement (e.g., 'tablets', 'bottles', 'vials', 'units')", max_length=50)),
                ('reorder_level', models.DecimalField(decimal_places=2, default=0, help_text='Reorder level - alert when stock falls below this', max_digits=10)),
                ('batch_number', models.CharField(blank=True, help_text='Batch or lot number (optional)', max_length=100)),
                ('expiry_date', models.DateField(blank=True, help_text='Expiry date (optional)', null=True)),
                ('location', models.CharField(blank=True, help_text="Storage location (e.g., 'Shelf A1', 'Refrigerator 1')", max_length=255)),
                ('last_restocked_at', models.DateTimeField(blank=True, help_text='When the inventory was last restocked', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the inventory record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the inventory record was last updated')),
                ('drug', models.OneToOneField(help_text='Drug for this inventory record', on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='pharmacy.drug')),
                ('last_restocked_by', models.ForeignKey(blank=True, help_text='User who last restocked this inventory', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_restocked', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Drug Inventory',
                'verbose_name_plural': 'Drug Inventories',
                'db_table': 'drug_inventory',
                'ordering': ['drug__name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out'), ('ADJUSTMENT', 'Adjustment'), ('DISPENSED', 'Dispensed'), ('RETURNED', 'Returned'), ('EXPIRED', 'Expired'), ('DAMAGED', 'Damaged')], help_text='Type of stock movement', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity moved (positive for IN, negative for OUT)', max_digits=10)),
                ('reference_number', models.CharField(blank=True, help_text='Reference number (e.g., invoice number, adjustment ID)', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this movement')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the movement was recorded')),
                ('created_by', models.ForeignKey(help_text='User who created this movement', on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('inventory', models.ForeignKey(help_text='Inventory record for this movement', on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='pharmacy.druginventory')),
                ('prescription', models.ForeignKey(blank=True, help_text='Prescription linked to this movement (if dispensed)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='pharmacy.prescription')),
            ],
            options={
                'verbose_name': 'Stock Movement',
                'verbose_name_plural': 'Stock Movements',
                'db_table': 'stock_movements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='druginventory',
            index=models.Index(fields=['drug'], name='drug_invent_drug_id_db679d_idx'),
        ),
        migrations.AddIndex(
            model_name='druginventory',
            index=models.Index(fields=['current_stock'], name='drug_invent_current_229b35_idx'),
        ),
        migrations.AddIndex(
            model_name='druginventory',
            index=models.Index(fields=['reorder_level'], name='drug_invent_reorder_4c5d6e_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['inventory'], name='stock_movem_invento_29e2b8_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['movement_type'], name='stock_movem_movemen_d922c9_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['created_at'], name='stock_movem_created_07bdcc_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['prescription'], name='stock_movem_prescri_707d6f_idx'),
        ),
    ]
