# Generated by Django 5.2.7 on 2026-01-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0005_drug_cost_price_drug_sales_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='is_emergency',
            field=models.BooleanField(default=False, help_text='Emergency flag: Allows dispensing without payment clearance. Requires proper authorization.'),
        ),
    ]
