# Generated by Django 5.2.7

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pharmacy', '0006_prescription_is_emergency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Brand/generic name', max_length=255)),
                ('generic_name', models.CharField(blank=True, max_length=255)),
                ('drug_class', models.CharField(blank=True, max_length=255)),
                ('contraindications', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drug', models.OneToOneField(blank=True, help_text='Link to pharmacy Drug if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eprescription_medication', to='pharmacy.drug')),
            ],
            options={
                'db_table': 'eprescription_medications',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EPrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('override_reason', models.TextField(blank=True, help_text='Doctor reason if interaction warning was overridden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eprescriptions', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eprescriptions', to='patients.patient')),
            ],
            options={
                'db_table': 'eprescriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicationInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('Mild', 'Mild'), ('Moderate', 'Moderate'), ('Severe', 'Severe')], default='Moderate', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('medication_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_from', to='pharmacy.medication')),
                ('medication_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_to', to='pharmacy.medication')),
            ],
            options={
                'db_table': 'eprescription_medication_interactions',
                'unique_together': {('medication_a', 'medication_b')},
            },
        ),
        migrations.CreateModel(
            name='EPrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(max_length=255)),
                ('frequency', models.CharField(blank=True, max_length=255)),
                ('duration', models.CharField(blank=True, max_length=255)),
                ('eprescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pharmacy.eprescription')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eprescription_items', to='pharmacy.medication')),
            ],
            options={
                'db_table': 'eprescription_items',
                'unique_together': {('eprescription', 'medication')},
            },
        ),
        migrations.AddIndex(
            model_name='medication',
            index=models.Index(fields=['name'], name='eprescrip_name_8a2c1d_idx'),
        ),
        migrations.AddIndex(
            model_name='medication',
            index=models.Index(fields=['generic_name'], name='eprescrip_generic_3d4e5f_idx'),
        ),
        migrations.AddIndex(
            model_name='eprescription',
            index=models.Index(fields=['patient'], name='eprescrip_patient_6a8c0d_idx'),
        ),
        migrations.AddIndex(
            model_name='eprescription',
            index=models.Index(fields=['doctor'], name='eprescrip_doctor__b2e8f2_idx'),
        ),
        migrations.AddIndex(
            model_name='eprescription',
            index=models.Index(fields=['status'], name='eprescrip_status_9c4a1b_idx'),
        ),
    ]
