# Generated by Django 5.2.7 on 2026-05-09 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0008_prescription_dispensed_quantity'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='eprescription',
            new_name='eprescripti_patient_bda39a_idx',
            old_name='eprescrip_patient_6a8c0d_idx',
        ),
        migrations.RenameIndex(
            model_name='eprescription',
            new_name='eprescripti_doctor__9c90dd_idx',
            old_name='eprescrip_doctor__b2e8f2_idx',
        ),
        migrations.RenameIndex(
            model_name='eprescription',
            new_name='eprescripti_status_583b4f_idx',
            old_name='eprescrip_status_9c4a1b_idx',
        ),
        migrations.RenameIndex(
            model_name='medication',
            new_name='eprescripti_name_655ef1_idx',
            old_name='eprescrip_name_8a2c1d_idx',
        ),
        migrations.RenameIndex(
            model_name='medication',
            new_name='eprescripti_generic_2cdae2_idx',
            old_name='eprescrip_generic_3d4e5f_idx',
        ),
    ]
