# Generated by Django 5.2.7 on 2026-06-29 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0010_rename_drugs_organiz_idx_drugs_organiz_7a3700_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='dispensed_quantity',
            field=models.CharField(blank=True, default='', help_text="Exact quantity dispensed by pharmacist (e.g., '24 tablets', '1 bottle')", max_length=100),
        ),
    ]
