# Generated by Django 5.2.7 on 2026-06-29 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0011_alter_prescription_dispensed_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='NAFDACFormularyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nafdac_reg_no', models.CharField(db_index=True, max_length=64, unique=True)),
                ('product_name', models.CharField(max_length=255)),
                ('active_ingredient', models.CharField(blank=True, max_length=255)),
                ('dosage_form', models.CharField(blank=True, max_length=128)),
                ('strength', models.CharField(blank=True, max_length=128)),
                ('manufacturer', models.CharField(blank=True, max_length=255)),
                ('nhia_tariff_code', models.CharField(blank=True, help_text='Linked NHIA drug tariff code when applicable', max_length=32)),
                ('is_essential_medicine', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pharmacy_nafdac_formulary',
                'ordering': ['product_name'],
                'indexes': [models.Index(fields=['product_name'], name='pharmacy_na_product_28d819_idx'), models.Index(fields=['nhia_tariff_code'], name='pharmacy_na_nhia_ta_0d48ed_idx')],
            },
        ),
    ]
