# Generated by Django 5.2.7 on 2025-12-24 04:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_type', models.CharField(choices=[('FULL', 'Full Backup'), ('INCREMENTAL', 'Incremental Backup'), ('DIFFERENTIAL', 'Differential Backup')], default='FULL', help_text='Type of backup', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Status of the backup operation', max_length=20)),
                ('file_path', models.CharField(blank=True, help_text='Path to backup file (relative or absolute)', max_length=500)),
                ('file_size', models.BigIntegerField(blank=True, help_text='Size of backup file in bytes', null=True)),
                ('is_encrypted', models.BooleanField(default=True, help_text='Whether the backup is encrypted')),
                ('encryption_key_id', models.CharField(blank=True, help_text='Identifier for encryption key (not the key itself)', max_length=255)),
                ('includes_patients', models.BooleanField(default=True, help_text='Whether backup includes patient data')),
                ('includes_visits', models.BooleanField(default=True, help_text='Whether backup includes visit data')),
                ('includes_consultations', models.BooleanField(default=True, help_text='Whether backup includes consultation data')),
                ('includes_lab_data', models.BooleanField(default=True, help_text='Whether backup includes lab data')),
                ('includes_radiology_data', models.BooleanField(default=True, help_text='Whether backup includes radiology data')),
                ('includes_prescriptions', models.BooleanField(default=True, help_text='Whether backup includes prescription data')),
                ('includes_audit_logs', models.BooleanField(default=True, help_text='Whether backup includes audit logs')),
                ('description', models.TextField(blank=True, help_text='Description or notes about this backup')),
                ('error_message', models.TextField(blank=True, help_text='Error message if backup failed')),
                ('started_at', models.DateTimeField(blank=True, help_text='When the backup started', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the backup completed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the backup record was created')),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this backup expires (for retention policies)', null=True)),
                ('created_by', models.ForeignKey(help_text='User who initiated this backup', on_delete=django.db.models.deletion.PROTECT, related_name='backups_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Backup',
                'verbose_name_plural': 'Backups',
                'db_table': 'backups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Restore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Status of the restore operation', max_length=20)),
                ('restore_patients', models.BooleanField(default=True, help_text='Whether to restore patient data')),
                ('restore_visits', models.BooleanField(default=True, help_text='Whether to restore visit data')),
                ('restore_consultations', models.BooleanField(default=True, help_text='Whether to restore consultation data')),
                ('restore_lab_data', models.BooleanField(default=True, help_text='Whether to restore lab data')),
                ('restore_radiology_data', models.BooleanField(default=True, help_text='Whether to restore radiology data')),
                ('restore_prescriptions', models.BooleanField(default=True, help_text='Whether to restore prescription data')),
                ('restore_audit_logs', models.BooleanField(default=False, help_text='Whether to restore audit logs (usually False to preserve current audit trail)')),
                ('description', models.TextField(blank=True, help_text='Description or notes about this restore')),
                ('error_message', models.TextField(blank=True, help_text='Error message if restore failed')),
                ('started_at', models.DateTimeField(blank=True, help_text='When the restore started', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the restore completed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the restore record was created')),
                ('backup', models.ForeignKey(help_text='Backup being restored', on_delete=django.db.models.deletion.PROTECT, related_name='restores', to='backup.backup')),
                ('created_by', models.ForeignKey(help_text='User who initiated this restore', on_delete=django.db.models.deletion.PROTECT, related_name='restores_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Restore',
                'verbose_name_plural': 'Restores',
                'db_table': 'restores',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='backup',
            index=models.Index(fields=['status'], name='backups_status_c02d44_idx'),
        ),
        migrations.AddIndex(
            model_name='backup',
            index=models.Index(fields=['backup_type'], name='backups_backup__1988f1_idx'),
        ),
        migrations.AddIndex(
            model_name='backup',
            index=models.Index(fields=['created_at'], name='backups_created_f8ef12_idx'),
        ),
        migrations.AddIndex(
            model_name='backup',
            index=models.Index(fields=['created_by'], name='backups_created_98f7fe_idx'),
        ),
        migrations.AddIndex(
            model_name='restore',
            index=models.Index(fields=['backup'], name='restores_backup__19ec02_idx'),
        ),
        migrations.AddIndex(
            model_name='restore',
            index=models.Index(fields=['status'], name='restores_status_de0c53_idx'),
        ),
        migrations.AddIndex(
            model_name='restore',
            index=models.Index(fields=['created_at'], name='restores_created_8d7df7_idx'),
        ),
        migrations.AddIndex(
            model_name='restore',
            index=models.Index(fields=['created_by'], name='restores_created_db9ae8_idx'),
        ),
    ]
