# Generated by Django 5.2.7 on 2025-12-23 09:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role', models.CharField(help_text='Role of the user at time of action', max_length=50)),
                ('action', models.CharField(help_text="Action performed (e.g., 'consultation.create', 'consultation.update')", max_length=100)),
                ('visit_id', models.IntegerField(blank=True, help_text='Visit ID if action is visit-scoped', null=True)),
                ('resource_type', models.CharField(help_text="Resource type (e.g., 'consultation', 'lab_order')", max_length=50)),
                ('resource_id', models.IntegerField(blank=True, help_text='ID of the resource affected', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the request', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent / device fingerprint')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When the action occurred')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata (no PHI)')),
                ('user', models.ForeignKey(help_text='User who performed the action', on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='audit_logs_user_id_88267f_idx'), models.Index(fields=['visit_id', 'timestamp'], name='audit_logs_visit_i_a5dcc8_idx'), models.Index(fields=['action', 'timestamp'], name='audit_logs_action_474804_idx'), models.Index(fields=['resource_type', 'resource_id'], name='audit_logs_resourc_bda8a6_idx')],
            },
        ),
    ]
