# Generated by Django 5.2.7 on 2026-06-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_saas_subscription_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='stripe_price_id',
            field=models.CharField(blank=True, help_text='Legacy Stripe Price ID (optional)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='stripe_price_id_yearly',
            field=models.CharField(blank=True, help_text='Legacy Stripe yearly Price ID (optional)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='stripe_customer_id',
            field=models.CharField(blank=True, help_text='Legacy Stripe Customer ID', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, help_text='Legacy Stripe Subscription ID', max_length=255, null=True),
        ),
    ]
