# Generated by Django 5.2.7 on 2026-06-29 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_organization_guide_modules'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saassubscriptionpayment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Legacy subscription payment', 'verbose_name_plural': 'Legacy subscription payments'},
        ),
    ]
