# Generated by Django 5.2.7 on 2025-12-30 22:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('laboratory', '0003_labtestcatalog'),
        ('pharmacy', '0004_druginventory_stockmovement_and_more'),
        ('visits', '0002_add_visit_type_chief_complaint_appointment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabSampleCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_time', models.DateTimeField(default=django.utils.timezone.now, help_text='When the sample was actually collected')),
                ('sample_type', models.CharField(help_text="Type of sample collected (e.g., 'Blood', 'Urine', 'Sputum')", max_length=100)),
                ('collection_site', models.CharField(blank=True, help_text="Collection site (e.g., 'Left arm', 'Midstream urine')", max_length=100)),
                ('status', models.CharField(choices=[('COLLECTED', 'Collected'), ('PARTIAL', 'Partial Collection'), ('FAILED', 'Collection Failed'), ('REFUSED', 'Patient Refused')], default='COLLECTED', help_text='Status of sample collection', max_length=20)),
                ('sample_volume', models.CharField(blank=True, help_text="Volume of sample collected (e.g., '5ml', '10cc')", max_length=50)),
                ('container_type', models.CharField(blank=True, help_text="Type of container used (e.g., 'Vacutainer', 'Sterile cup')", max_length=100)),
                ('collection_notes', models.TextField(blank=True, help_text='Notes about the collection (e.g., patient condition, special circumstances)')),
                ('reason_if_failed', models.TextField(blank=True, help_text='Reason if collection failed (required if status is FAILED)')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, help_text='When this collection record was created')),
                ('collected_by', models.ForeignKey(help_text='Nurse who collected the sample. PROTECT prevents deletion.', on_delete=django.db.models.deletion.PROTECT, related_name='lab_samples_collected', to=settings.AUTH_USER_MODEL)),
                ('lab_order', models.ForeignKey(help_text='Lab order this sample collection is based on. Nurse cannot create lab orders.', on_delete=django.db.models.deletion.PROTECT, related_name='sample_collections', to='laboratory.laborder')),
                ('visit', models.ForeignKey(help_text='Visit this sample collection belongs to. Visit-scoped per EMR rules.', on_delete=django.db.models.deletion.CASCADE, related_name='lab_sample_collections', to='visits.visit')),
            ],
            options={
                'verbose_name': 'Lab Sample Collection',
                'verbose_name_plural': 'Lab Sample Collections',
                'db_table': 'lab_sample_collections',
                'ordering': ['-collection_time'],
                'indexes': [models.Index(fields=['visit', '-collection_time'], name='lab_sample__visit_i_7d98c0_idx'), models.Index(fields=['lab_order'], name='lab_sample__lab_ord_96856e_idx'), models.Index(fields=['collected_by'], name='lab_sample__collect_84cfd5_idx'), models.Index(fields=['status'], name='lab_sample__status_68e6fe_idx')],
            },
        ),
        migrations.CreateModel(
            name='MedicationAdministration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administration_time', models.DateTimeField(default=django.utils.timezone.now, help_text='When the medication was actually administered')),
                ('dose_administered', models.CharField(help_text="Actual dose administered (e.g., '500mg', '1 tablet')", max_length=255)),
                ('route', models.CharField(choices=[('ORAL', 'Oral'), ('IV', 'Intravenous'), ('IM', 'Intramuscular'), ('SC', 'Subcutaneous'), ('TOPICAL', 'Topical'), ('INHALATION', 'Inhalation'), ('RECTAL', 'Rectal'), ('OTHER', 'Other')], default='ORAL', help_text='Route of administration', max_length=50)),
                ('site', models.CharField(blank=True, help_text="Administration site (e.g., 'Left arm', 'Right thigh')", max_length=100)),
                ('status', models.CharField(choices=[('GIVEN', 'Given'), ('REFUSED', 'Refused by Patient'), ('HELD', 'Held (Clinical Reason)'), ('NOT_AVAILABLE', 'Not Available'), ('ERROR', 'Administration Error')], default='GIVEN', help_text='Status of medication administration', max_length=20)),
                ('administration_notes', models.TextField(blank=True, help_text='Notes about the administration (e.g., patient response, site reaction)')),
                ('reason_if_held', models.TextField(blank=True, help_text='Reason if medication was held (required if status is HELD)')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, help_text='When this administration record was created')),
                ('administered_by', models.ForeignKey(help_text='Nurse who administered the medication. PROTECT prevents deletion.', on_delete=django.db.models.deletion.PROTECT, related_name='medications_administered', to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(help_text='Prescription this administration is based on. Nurse cannot create prescriptions.', on_delete=django.db.models.deletion.PROTECT, related_name='administrations', to='pharmacy.prescription')),
                ('visit', models.ForeignKey(help_text='Visit this medication administration belongs to. Visit-scoped per EMR rules.', on_delete=django.db.models.deletion.CASCADE, related_name='medication_administrations', to='visits.visit')),
            ],
            options={
                'verbose_name': 'Medication Administration',
                'verbose_name_plural': 'Medication Administrations',
                'db_table': 'medication_administrations',
                'ordering': ['-administration_time'],
                'indexes': [models.Index(fields=['visit', '-administration_time'], name='medication__visit_i_05594f_idx'), models.Index(fields=['prescription'], name='medication__prescri_57d213_idx'), models.Index(fields=['administered_by'], name='medication__adminis_b26548_idx'), models.Index(fields=['status'], name='medication__status_0275c2_idx')],
            },
        ),
        migrations.CreateModel(
            name='NursingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('GENERAL', 'General Nursing Note'), ('ADMISSION', 'Admission Note'), ('SHIFT_HANDOVER', 'Shift Handover Note'), ('PROCEDURE', 'Procedure Note'), ('WOUND_CARE', 'Wound Care Note'), ('PATIENT_EDUCATION', 'Patient Education Note'), ('ANTENATAL', 'Antenatal Monitoring Note'), ('INPATIENT', 'Inpatient Monitoring Note'), ('OTHER', 'Other')], default='GENERAL', help_text='Type of nursing note', max_length=50)),
                ('note_content', models.TextField(help_text='Nursing note content - observations, care provided, patient response. NO DIAGNOSIS.')),
                ('patient_condition', models.CharField(blank=True, help_text="General patient condition observation (e.g., 'Alert and oriented', 'Resting comfortably')", max_length=100)),
                ('care_provided', models.TextField(blank=True, help_text='Description of nursing care provided')),
                ('patient_response', models.TextField(blank=True, help_text="Patient's response to care provided")),
                ('recorded_at', models.DateTimeField(auto_now_add=True, help_text='When the nursing note was recorded')),
                ('recorded_by', models.ForeignKey(help_text='Nurse who recorded this note. PROTECT prevents deletion.', on_delete=django.db.models.deletion.PROTECT, related_name='nursing_notes_recorded', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(help_text='Visit this nursing note belongs to. Visit-scoped per EMR rules.', on_delete=django.db.models.deletion.CASCADE, related_name='nursing_notes', to='visits.visit')),
            ],
            options={
                'verbose_name': 'Nursing Note',
                'verbose_name_plural': 'Nursing Notes',
                'db_table': 'nursing_notes',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['visit', '-recorded_at'], name='nursing_not_visit_i_276230_idx'), models.Index(fields=['recorded_by'], name='nursing_not_recorde_fc46d6_idx'), models.Index(fields=['note_type'], name='nursing_not_note_ty_52d101_idx')],
            },
        ),
    ]
