# Generated by Django 6.0 on 2025-12-24 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('patients', '0003_update_optional_fields_nullable'),
        ('visits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelemedicineSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twilio_room_sid', models.CharField(help_text='Twilio Room SID', max_length=255, unique=True)),
                ('twilio_room_name', models.CharField(help_text='Twilio Room Name', max_length=255)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed')], default='SCHEDULED', help_text='Status of the telemedicine session', max_length=20)),
                ('scheduled_start', models.DateTimeField(help_text='Scheduled start time')),
                ('actual_start', models.DateTimeField(blank=True, help_text='Actual start time', null=True)),
                ('actual_end', models.DateTimeField(blank=True, help_text='Actual end time', null=True)),
                ('duration_seconds', models.IntegerField(blank=True, help_text='Session duration in seconds', null=True)),
                ('recording_enabled', models.BooleanField(default=False, help_text='Whether session recording is enabled')),
                ('recording_sid', models.CharField(blank=True, help_text='Twilio Recording SID (if recording exists)', max_length=255)),
                ('recording_url', models.URLField(blank=True, help_text='URL to access recording (if available)')),
                ('notes', models.TextField(blank=True, help_text='Session notes or summary')),
                ('error_message', models.TextField(blank=True, help_text='Error message if session failed')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the session was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the session was last updated')),
                ('appointment', models.ForeignKey(blank=True, help_text='Related appointment (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telemedicine_sessions', to='appointments.appointment')),
                ('created_by', models.ForeignKey(help_text='User who created this session', on_delete=django.db.models.deletion.PROTECT, related_name='telemedicine_sessions_created', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(help_text='Doctor participating in the session', on_delete=django.db.models.deletion.PROTECT, related_name='telemedicine_sessions_as_doctor', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(help_text='Patient participating in the session', on_delete=django.db.models.deletion.PROTECT, related_name='telemedicine_sessions', to='patients.patient')),
                ('visit', models.ForeignKey(help_text='Visit this telemedicine session belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='telemedicine_sessions', to='visits.visit')),
            ],
            options={
                'verbose_name': 'Telemedicine Session',
                'verbose_name_plural': 'Telemedicine Sessions',
                'db_table': 'telemedicine_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelemedicineParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twilio_participant_sid', models.CharField(blank=True, help_text='Twilio Participant SID', max_length=255)),
                ('joined_at', models.DateTimeField(blank=True, help_text='When participant joined', null=True)),
                ('left_at', models.DateTimeField(blank=True, help_text='When participant left', null=True)),
                ('connection_quality', models.CharField(blank=True, help_text='Connection quality (good, fair, poor)', max_length=50)),
                ('device_type', models.CharField(blank=True, help_text='Device type (desktop, mobile, tablet)', max_length=50)),
                ('browser', models.CharField(blank=True, help_text='Browser name and version', max_length=100)),
                ('user', models.ForeignKey(help_text='User participating in the session', on_delete=django.db.models.deletion.CASCADE, related_name='telemedicine_participations', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(help_text='Telemedicine session', on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='telemedicine.telemedicinesession')),
            ],
            options={
                'verbose_name': 'Telemedicine Participant',
                'verbose_name_plural': 'Telemedicine Participants',
                'db_table': 'telemedicine_participants',
            },
        ),
        migrations.AddIndex(
            model_name='telemedicinesession',
            index=models.Index(fields=['visit'], name='telemedicin_visit_i_16889d_idx'),
        ),
        migrations.AddIndex(
            model_name='telemedicinesession',
            index=models.Index(fields=['status'], name='telemedicin_status_41707b_idx'),
        ),
        migrations.AddIndex(
            model_name='telemedicinesession',
            index=models.Index(fields=['twilio_room_sid'], name='telemedicin_twilio__9dda23_idx'),
        ),
        migrations.AddIndex(
            model_name='telemedicinesession',
            index=models.Index(fields=['scheduled_start'], name='telemedicin_schedul_caa437_idx'),
        ),
        migrations.AddIndex(
            model_name='telemedicineparticipant',
            index=models.Index(fields=['session'], name='telemedicin_session_b9b05c_idx'),
        ),
        migrations.AddIndex(
            model_name='telemedicineparticipant',
            index=models.Index(fields=['user'], name='telemedicin_user_id_2052ec_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='telemedicineparticipant',
            unique_together={('session', 'user')},
        ),
    ]
