# Generated by Django 5.2.7 on 2026-07-19 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telemedicine', '0005_virtual_clinic_invites'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='telemedicineparticipant',
            new_name='telemedicin_invite__c0641c_idx',
            old_name='telemedicin_invite__7a1b2c_idx',
        ),
    ]
