# Generated by Django 6.0 on 2025-12-22 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('laboratory', '0001_initial'),
        ('visits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='laborder',
            name='ordered_by',
            field=models.ForeignKey(help_text='Doctor who ordered the lab tests. PROTECT prevents deletion.', on_delete=django.db.models.deletion.PROTECT, related_name='lab_orders_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='laborder',
            name='visit',
            field=models.ForeignKey(help_text='Visit is the single source of clinical truth. Lab order is visit-scoped.', on_delete=django.db.models.deletion.PROTECT, related_name='lab_orders', to='visits.visit'),
        ),
        migrations.AddField(
            model_name='labresult',
            name='lab_order',
            field=models.OneToOneField(help_text='Lab order this result belongs to. One result per order.', on_delete=django.db.models.deletion.CASCADE, related_name='result', to='laboratory.laborder'),
        ),
        migrations.AddField(
            model_name='labresult',
            name='recorded_by',
            field=models.ForeignKey(help_text='Lab Tech who recorded this result. PROTECT prevents deletion.', on_delete=django.db.models.deletion.PROTECT, related_name='lab_results_recorded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='laborder',
            index=models.Index(fields=['visit'], name='lab_orders_visit_i_ead2c8_idx'),
        ),
        migrations.AddIndex(
            model_name='laborder',
            index=models.Index(fields=['consultation'], name='lab_orders_consult_44b3bf_idx'),
        ),
        migrations.AddIndex(
            model_name='laborder',
            index=models.Index(fields=['status'], name='lab_orders_status_67ed4e_idx'),
        ),
        migrations.AddIndex(
            model_name='laborder',
            index=models.Index(fields=['ordered_by'], name='lab_orders_ordered_a815b3_idx'),
        ),
        migrations.AddIndex(
            model_name='labresult',
            index=models.Index(fields=['lab_order'], name='lab_results_lab_ord_ce9a03_idx'),
        ),
        migrations.AddIndex(
            model_name='labresult',
            index=models.Index(fields=['recorded_by'], name='lab_results_recorde_ed8b78_idx'),
        ),
        migrations.AddIndex(
            model_name='labresult',
            index=models.Index(fields=['recorded_at'], name='lab_results_recorde_2479b2_idx'),
        ),
    ]
