# Generated by Django 6.0 on 2025-12-24 16:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTestCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_code', models.CharField(help_text='Unique code for the lab test (e.g., CBC, HGB, GLU)', max_length=50, unique=True)),
                ('test_name', models.CharField(help_text='Full name of the lab test', max_length=200)),
                ('category', models.CharField(choices=[('HEMATOLOGY', 'Hematology'), ('CHEMISTRY', 'Chemistry'), ('MICROBIOLOGY', 'Microbiology'), ('IMMUNOLOGY', 'Immunology'), ('SEROLOGY', 'Serology'), ('ENDOCRINOLOGY', 'Endocrinology'), ('TOXICOLOGY', 'Toxicology'), ('URINALYSIS', 'Urinalysis'), ('BLOOD_BANK', 'Blood Bank'), ('MOLECULAR', 'Molecular'), ('OTHER', 'Other')], help_text='Category of the lab test', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Description of what the test measures')),
                ('reference_range_min', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum normal value (for numeric tests)', max_digits=10, null=True)),
                ('reference_range_max', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum normal value (for numeric tests)', max_digits=10, null=True)),
                ('reference_range_text', models.TextField(blank=True, help_text="Textual reference range (e.g., 'Negative', 'Positive', 'Normal')")),
                ('unit', models.CharField(blank=True, help_text='Unit of measurement (e.g., g/dL, mg/dL, cells/μL)', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this test is currently available for ordering')),
                ('requires_fasting', models.BooleanField(default=False, help_text='Whether patient must fast before this test')),
                ('turnaround_time_hours', models.IntegerField(blank=True, help_text='Expected turnaround time in hours', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('specimen_type', models.CharField(blank=True, help_text="Type of specimen required (e.g., 'Blood', 'Urine', 'Stool')", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the test was added to the catalog')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the test was last updated')),
                ('created_by', models.ForeignKey(help_text='User who created this test in the catalog', on_delete=django.db.models.deletion.PROTECT, related_name='lab_tests_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lab Test Catalog',
                'verbose_name_plural': 'Lab Test Catalog',
                'db_table': 'lab_test_catalog',
                'ordering': ['category', 'test_name'],
                'indexes': [models.Index(fields=['test_code'], name='lab_test_ca_test_co_3bd3e2_idx'), models.Index(fields=['category'], name='lab_test_ca_categor_a2a45e_idx'), models.Index(fields=['is_active'], name='lab_test_ca_is_acti_fd7a85_idx'), models.Index(fields=['test_name'], name='lab_test_ca_test_na_5b0683_idx')],
            },
        ),
    ]
