# Generated by Django 6.0 on 2026-06-02 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0007_labtestcatalog_organization'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='labtestcatalog',
            new_name='lab_test_ca_organiz_89689c_idx',
            old_name='lab_test_cat_organiz_idx',
        ),
    ]
